### ISSUE TITLE
Issue with run-meteor-on-google-app-engine

### ISSUE THREAD

**Issue by boredland** [GoogleCloudPlatform/community#1010]
I'm pretty sure that you want to cd into the /app/ folder during the docker build, not "programs" whatever that is. In addition it should use the newest nodejs currently supported by meteor:

```
FROM gcr.io/google_appengine/nodejs
RUN install_node 8.15.1
COPY . /app/
RUN (cd **programs**/server && npm install --unsafe-perm)
CMD node main.js
```

**Comment by ToddKopriva** [comment]
@ace-n , could you have a look at this issue, which includes both a small content bug and a request for an update?

**Comment by ace-n** [comment]
@ToddKopriva thanks for the ping! cc @mylesborins as FYI.

@boredland thanks for reporting! Unfortunately we're not _officially_ maintaining this sample for two reasons:
1. Meteor isn't _that_ common (judging by [downloads from NPM](https://www.npmjs.com/package/meteor)).
2. Most officially-maintained content is in our other repos. The content in this repo is (almost exclusively) maintained by our awesome community members. 😃

You're more than welcome to submit a PR, however! Barring that (and echoing what @fhinkel said internally), it's probably easier to _archive_ this tutorial + mark it as outdated.

**Comment by ToddKopriva** [comment]
Thanks for the response, @ace-n .

I'm going to go with your suggestion (and that of @fhinkel ) and archive this tutorial soon. I'll give it a couple of days, so that @boredland has time to give his opinion.

I'll assign the bug back to myself.

**Comment by boredland** [comment]
I think renoving the article is fine.

Todd Kopriva <notifications@github.com> schrieb am Di., 3. Sep. 2019, 03:19:
