### ISSUE TITLE
issues in understanding-oauth2-and-deploy-a-basic-auth-srv...

### ISSUE THREAD

**Issue by g000m** [GoogleCloudPlatform/community#1015]
I ran into multiple issues working through this tutorial. 

- The tutorial may need to be updated for for more recent GCP standards
- There also appear to be typos in the client entities. 
- function.js lines 97-98 needed req.body changed to req.query
- It's also not specified wether the hostname in auth.pug should be updated to reflect the current user's GCP project id. I did change it with limited success.
- I got stuck at the section Authorization Code (PKCE), getting responses inconsistent with the description.

I stopped after that. I'm not familiar enough with how this should have worked to make a PR.

**Comment by ToddKopriva** [comment]
Thanks for the report, Gabe. I'll have a look.

**Comment by ToddKopriva** [comment]
@michaelawyu , could you take a look at this issue about a document that you submitted?

**Comment by ToddKopriva** [comment]
I'm closing this issue because I'm moving the document to the /archived folder.
