### ISSUE TITLE
cloud-sdk-el7-x86_64 key signature issue

### ISSUE THREAD

**Issue by fahedouch** [GoogleCloudPlatform/community#1018]
Hello GCP people,

I encountered a problem with the repository  cloud-sdk-el7-x86_64.

`https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-sdk
Trying other mirror.`

should i contact the support or they can be notified behind this issue.

Have a nice day.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll try to find the right place for this to be reported.

**Comment by ToddKopriva** [comment]
The right folks within Google are aware of the issue. There are internal bug reports tracking the issue.

I'm going to close this issue report.

Thanks again for letting us know.
