### ISSUE TITLE
Dialogflow Chatbot that can broadcast message to enduser (in facebook/workplace)

### ISSUE THREAD

**Issue by ryantgz** [GoogleCloudPlatform/community#1021]
Hi All,

I am writing this to check if there is anyone able to guide me on creating a dialogflow chatbot that can broadcase message to enduser?

Thank you.
Ryan.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

Here is a good document to read if you want to see what's involved in creating a chatbot with Dialogflow:
https://cloud.google.com/solutions/building-and-deploying-chatbot-dialogflow
