### ISSUE TITLE
Issue with private-forseti-with-scc-integration

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#1029]
@fawix , this bug report came through our internal channels. Could you look at this and determine if there is anything that needs to be updated in your tutorial?

https://cloud.google.com/community/tutorials/private-forseti-with-scc-integration

In the following section, there is a config snippet to configure the link between Forseti violations and CSCC:

Modify the notifier: violation: cscc section of the configuration as follows:

However, there should be more info on the following section:

violation:
  cscc:
    enabled: true
    # Cloud SCC uses a source_id. It is unique per
    # organization and must be generated via a self-registration process.
    # The format is: organizations/ORG_ID/sources/SOURCE_ID
    source_id: [paste_value_from_prior_step]
    # Added the following fields:
    mode: api
    organization_id: organizations/[ORG_ID]

What does it mean "Added the following fields".  We should tell the user why we need to add this, as the official documentation on Forseti doesn't specify these fields (https://forsetisecurity.org/docs/latest/configure/notifier/index.html).

**Comment by fawix** [comment]
@ToddKopriva I think this one was addressed with #1089

**Comment by ToddKopriva** [comment]
Ah, good call, @fawix.
