### ISSUE TITLE
Tutorial Request:  Cross-Project Networking (XPN), VPN, Network Peering, Connectivity

### ISSUE THREAD

**Issue by mitchwyle** [GoogleCloudPlatform/community#103]
Please write a series of comprehensive tutorials that cover the most-frequent use cases associated with safe, simple Google Container Engine (GKE) connectivity between projects.  Include service accounts that are members of both projects in I/AM and Groups.  Include guidance for using VPN, Network Peering, and XPN. 

It is common for docker micro-services to be in separate projects whose end-points should be exposed to all-and-only other micro-services whose service accounts are carefully controlled.  It is very difficult to get XPN to work (bridging networks) in GKE. It is very difficult to learn and understand proper application of network peering https://cloud.google.com/sdk/gcloud/reference/alpha/compute/networks/peerings/
It is unclear how which access and authentication policies should use which method.

**Comment by parthiban-srinivasan** [comment]
Agree! Tutorial for XPN set-up for GCE, GKE & GAE would be helpful

**Comment by tonglil** [comment]
I don't think XPN for GKE works?

**Comment by sirisak1985** [comment]
issue
