### ISSUE TITLE
Help me on setup infrastructure?

### ISSUE THREAD

**Issue by csm789** [GoogleCloudPlatform/community#1032]
My requirement is t setup an organization architecture from start using GCP- Paas?
How to set up an Organization using policies?
Identity and access management MFA?
How to setup Kafka and spark using terraform in Europe-west2?
How to setup node.js, Kafka, and Spark infrastructure CI-CD using terraform?
I really appreciate if you can help me. 
Thank you GCP

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
