### ISSUE TITLE
automated example of creating a firestore database

### ISSUE THREAD

**Issue by erikwalker** [GoogleCloudPlatform/community#1033]
I am interested in figuring out how to automate the creation of firestore database with gcloud commands and or terraform.  All i can see is that it has to be done in the gcp console. Ideally, I would like a way to programmatically do this. I have done extensive research and have not found any resources online to do this. Can someone help to create a basic tutorial on doing this ?

**Comment by ToddKopriva** [comment]
Here you go:
https://cloud.google.com/sdk/gcloud/reference/alpha/firestore/databases/create
