### ISSUE TITLE
Tutorial Request: Cloud Endpoint API Management With NodeJs 

### ISSUE THREAD

**Issue by mojalil** [GoogleCloudPlatform/community#1038]
Having looked though the [quick start doc](https://cloud.google.com/endpoints/docs/quickstart-endpoints) and the [nodejs samples](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/endpoints/getting-started)

It would be nice to have a NodeJS example in the quick start documentation, with authentication and throttling. 

[edit]:  Additionally with a way to do key generation programmatically rather than via the gcp dashboard.

Why this is useful, there is a sizable number of companies and organisations that are opening up their internal data and services to the public, and have their backend running on nodejs. Having a tutorial on cloud endpoints with throttling, key generation would be great.

**Comment by ToddKopriva** [comment]
Thanks for the request. I'll ask and look around to see if I can find anything that already exists that might serve your needs.

**Comment by ToddKopriva** [comment]
@fhinkel , can you recommend any materials that might help @mjdude ?

**Comment by fhinkel** [comment]
@mjdude Thanks for pointing this out. As of now, I don't think we have specific tutorial on this.
