### ISSUE TITLE
Issue with run-laravel-on-appengine-standard Stackdriver custom logger

### ISSUE THREAD

**Issue by ProgrammerZ** [GoogleCloudPlatform/community#1041]
I have an issue with Stackdriver custom logger. 
I have followed the tutorial steps and the logger is working, I'm receiving logs and Exceptions as expected. 
BUT it does not take into account the Log Level which is set in: **`config/logging.php`**
```
'channels' => [

    // Add the following lines to integrate with Stackdriver:
    'stackdriver' => [
        'driver' => 'custom',
        'via' => App\Logging\CreateStackdriverLogger::class,
        'level' => 'error',     // <------ IGNORES THIS SETTING
    ],
```
I'm still receiving all log from debug to emergency

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into this.
