### ISSUE TITLE
Tutorial: Uploading video streams from GCP to Youtube

### ISSUE THREAD

**Issue by phunl** [GoogleCloudPlatform/community#105]
SCENARIO:
Uploading video streams from GCP to YouTube. Use internal YouTube host instead of the default edge one

Customer creating video content on GCP and wants to distribute it thru youtube

**Comment by JimTravis** [comment]
Some details: use core.rtmp.youtube.com instead of rtmp.youtube.com. Allows for fewer instances when streaming to YouTube due to much lower latency and because connections are shorter in duration.
