### ISSUE TITLE
Issue with setting-up-lamp - Setting Up LAMP on Compute Engine

### ISSUE THREAD

**Issue by cool-username** [GoogleCloudPlatform/community#1053]
Issue Description: First and foremost: wonderful instructions! Bravo! Two little things - one: when deploying CentOS 7, why is MySQL not available (and MariaDB is)? Second, when modifying the PhpMyAdmin config file, the user must first install Nano (yum install nano). Thanks so much, Anand

**Comment by ToddKopriva** [comment]
Thanks for the issue report. I'll look into this.

**Comment by ToddKopriva** [comment]
fixed by this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1513
