### ISSUE TITLE
Author filter not working on Community Tutorial

### ISSUE THREAD

**Issue by Timtech4u** [GoogleCloudPlatform/community#1055]
Hi @ToddKopriva , I noticed Author query parameters does not work as it should.
An example is: https://cloud.google.com/community/tutorials?q=timtech4u
The expected behaviour is to return all the tutorials I have written, but it returns all tutorials.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into it.

**Comment by ToddKopriva** [comment]
You are correct that sending the user name as a URL parameter isn't working, but I do see the correct results when I enter your user name in the search field here:
https://cloud.google.com/community/tutorials/

**Comment by Timtech4u** [comment]
> You are correct that sending the user name as a URL parameter isn't working, but I do see the correct results when I enter your user name in the search field here:
> https://cloud.google.com/community/tutorials/

Yes, this works fine. Would nice to know when this is fixed so I can use the URL with author parameter.

**Comment by ToddKopriva** [comment]
We'll update this issue report when there's a change.
