### ISSUE TITLE
cloud-iot-mender-ota image bucket 403 during update-image.sh

### ISSUE THREAD

**Issue by programatt** [GoogleCloudPlatform/community#1056]
Issue Description:

Mender GCP image in bucket returns a 403 Forbidden. Following instructions on https://cloud.google.com/community/tutorials/cloud-iot-mender-ota this is the result I see for 
`bash community/tutorials/cloud-iot-mender-ota/image/update-image.sh` I am running that command from Cloud Shell with my environment variables configured per the tutorial.

    mender-artifact                                              100%[==============================================================================================================================================>]   6.46M  22.9MB/s    in 0.3s    

    2019-10-16 21:05:28 (22.9 MB/s) - ‘mender-artifact’ saved [6778589/6778589]

    --2019-10-16 21:05:28--  https://storage.googleapis.com/mender-gcp-ota-images/gcp-mender-demo-image-raspberrypi3.sdimg
    Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.202.128, 2607:f8b0:4001:c03::80
    Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.202.128|:443... connected.
    HTTP request sent, awaiting response... 403 Forbidden
    2019-10-16 21:05:28 ERROR 403: Forbidden.

Attempting to retrieve the file directly from the browser, it looks like the project the bucket is under has a billing problem?
![image](https://user-images.githubusercontent.com/547550/66972242-9db2b100-f059-11e9-8f70-57c6e8e8b719.png)

**Comment by Kcr19** [comment]
Updated, should work now. Please test and lmk.

**Comment by ToddKopriva** [comment]
Thanks, @Kcr19 .

@programatt , please let us know if it's working for you now.

**Comment by ToddKopriva** [comment]
I'm closing this as fixed, based on the comment from @Kcr19 .

Feel free to re-open this if needed.
