### ISSUE TITLE
Required cloud functions runtime

### ISSUE THREAD

**Issue by tadashigaki** [GoogleCloudPlatform/community#1058]
When I tried cloud-functions-twilio-voice-record tutorial, encountered below error. [1]

`ERROR: (gcloud.beta.functions.deploy) Missing required argument [runtime]: Flag --runtime is required for new functions.`

Runtime flag seems required when functions deploy. [2]

Can I fix this issue?

[1] https://cloud.google.com/community/tutorials/cloud-functions-twilio-voice-record
[2] https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy

**Comment by ToddKopriva** [comment]
Thanks for the report. It looks like this tutorial may need an update. I'll look into this.

**Comment by tadashigaki** [comment]
Thanks!
