### ISSUE TITLE
Stuck - First Cloud SQL connection, generating RSA key pair.

### ISSUE THREAD

**Issue by ishanrakitha** [GoogleCloudPlatform/community#1059]
Spring Boot 2 application stuck in GKE with the following... Unable to connect to CLOUD SQL instance. Please advise.

**Connection string**

`spring.datasource.url=jdbc:mysql://google/food?verifyServerCertificate=false&useSSL=false&requireSSL=false&cloudSqlInstance=<INSTANCE>&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=<USER>&password=<PASS>
`

**Instance Settings**

Unsecured connections are allowed to connect to this instance.

```
App Engine authorization: All apps in this project are authorized by default.
Apps in this project: All authorized.
```

```
com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:183) Connecting to Cloud SQL instance [<INSTANCE CONNECTION NAME>] via SSL socket.  
 
com.google.cloud.sql.core.CoreSocketFactory.getInstance(CoreSocketFactory.java:111) First Cloud SQL connection, generating RSA key pair.  
```

I'm using the following maven dependancy. 

```
        <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>mysql-socket-factory</artifactId>
            <version>1.0.15</version>
        </dependency>
```

Thank You!

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
