### ISSUE TITLE
Tutorial Request - Cloud Function code for sending an email when billing alerts are triggered

### ISSUE THREAD

**Issue by sspage** [GoogleCloudPlatform/community#1062]
If possible, I would like to see a sample for this scenario:

Cloud Function code for sending an email when billing alerts are triggered

**Comment by ToddKopriva** [comment]
Here are a couple of documents that should get you started:

https://cloud.google.com/billing/docs/how-to/notify#write-a-cloud-function

https://cloud.google.com/solutions/automated-email-cloud-billing-summary
