### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by devauen** [GoogleCloudPlatform/community#1064]
./mvnw -Drun.profiles=mysql spring-boot:run

doesn't work for me. I needed to change it to:

./mvnw -Dspring-boot.run.profiles=mysql spring-boot:run

**Comment by ToddKopriva** [comment]
Thanks for the report. It appears that for Spring Boot 2.0 and higher, run has been replaced by spring-boot.run.

I'll make the update.

**Comment by ToddKopriva** [comment]
fixed with #1065
