### ISSUE TITLE
Issue with joomla-on-compute-engine

### ISSUE THREAD

**Issue by adjei7** [GoogleCloudPlatform/community#1067]
Issue Description
Step 3 of 'Setting up the database' may need updating as it references pre mysql8 syntax and code

`GRANT ALL ON YOUR_DATABASE_NAME.* TO 'YOUR_USERNAME'@'localhost' IDENTIFIED BY 'YOUR_PASSWORD';`

no longer words and may need to use something like

`mysql> CREATE USER 'YOUR_USERNAME'@'localhost' IDENTIFIED BY 'YOUR_PASSWORD';`

`mysql> GRANT ALL PRIVILEGES ON YOUR_DATABASE_NAME.* TO 'YOUR_USERNAME'@'localhost' WITH GRANT OPTION;
`

reference:
https://stackoverflow.com/questions/52372165/mysql-error-1064-42000-you-have-an-error-in-your-sql-syntax

**Comment by ToddKopriva** [comment]
Thanks for the report.

If you want to submit a pull request to make this fix, I'll review it and get it merged. If not, then I'll look into making the fixes.

**Comment by ToddKopriva** [comment]
fixed by this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1519
