### ISSUE TITLE
Sample to delete older versions of app engine versions using node js

### ISSUE THREAD

**Issue by smithaprabhu** [GoogleCloudPlatform/community#1075]
from google.appengine.api.modules import modules

# core logic (inside a cron or other handler)
for m in modules.get_modules():
    dv = modules.get_default_version(m)
    for v in modules.get_versions(m):
        if v != dv: modules.stop_version(m, v)

Can a similar code be written in node js ? I didnt get any samples. any samples in this regard greatly appreciated.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
