### ISSUE TITLE
Issue with running-nodejs-on-google-cloud

### ISSUE THREAD

**Issue by forresthopkinsa** [GoogleCloudPlatform/community#1078]
Article is outdated; Node.js is now available on the GAE Standard environment, not just the Flex environment.

**Comment by ToddKopriva** [comment]
Thanks for the report, Forrest.

If you know what needs to be fixed in the tutorial, feel free to submit a pull request to make the fix, and I'll review it and get it merged. If you would rather not do that, then we'll find someone else to make the upodate.

**Comment by tjwebb** [comment]
I think this is a duplicate of #718.

**Comment by ToddKopriva** [comment]
Thanks, Travis.
