### ISSUE TITLE
I am facing issue while connecting to Cloud SQL

### ISSUE THREAD

**Issue by vnc-digital** [GoogleCloudPlatform/community#1079]
Below is my code from application.properties which I got from this [application.properties](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/run-spring-petclinic-on-app-engine-cloudsql/spring-petclinic/src/main/resources/application-mysql-datasource.properties)

`database=mysql
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://google/DatabaseName?cloudSqlInstance=INSTANCE_NAME&socketFactory=com.google.cloud.sql.mysql.SocketFactory
spring.datasource.username=root
spring.datasource.password=MY_PASSWORD
`

And I am getting following error when I ran this  `./mvnw -Drun.profiles=mysql spring-boot:run `command

![image](https://user-images.githubusercontent.com/48463798/69404657-cf3b2e00-0d23-11ea-832f-3d4c62a1dbca.png)

![image](https://user-images.githubusercontent.com/48463798/69404547-91d6a080-0d23-11ea-9330-6e1266c6fa81.png)

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by ToddKopriva** [comment]
fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1065
