### ISSUE TITLE
Issue with tutorials/managing-gcp-projects-with-terraform/index.md

### ISSUE THREAD

**Issue by benbro** [GoogleCloudPlatform/community#1080]
google_project_services used in the tutorial is deprecated and should be replaced with separate google_project_service for each service.

Old
```tf
resource "google_project_services" "project" {
 project = "${google_project.project.project_id}"
 services = [
   "compute.googleapis.com"
 ]
}
```

New
```tf
resource "google_project_service" "project_compute" {
 project = "${google_project.project.project_id}"
  service = "compute.googleapis.com"
}
```

`"${google_project.project.project_id}"` should also be replaced with `google_project.project.project_id` in recent Terraform.

**Comment by QuantumAa** [comment]
Ar 3d fc rra

**Comment by ToddKopriva** [comment]
Thanks for letting us know about the need for this update.

If you know exactly what needs to be fixed, you could create a pull request to make the change yourself, and I'll review it and get it merged. If not, I'll look into making the update.
