### ISSUE TITLE
Issue with tutorials/pubsub-logging-pvm-shutdowns/index.md

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#1081]
https://cloud.google.com/community/tutorials/pubsub-logging-pvm-shutdowns

There are instances in this tutorial of Python packages being installed system-wide (`sudo pip install package_name`), rather than for a particular user. Should these instances be updated to use the `--user` flag instead (`pip install --user package_name`)?

**Comment by mkahn5** [comment]
@ToddKopriva Yes, fine to install for the user instead of system wide.
