### ISSUE TITLE
AWS VPN: not possible to attach 2 x VGW to 1 VPC

### ISSUE THREAD

**Issue by wolruf** [GoogleCloudPlatform/community#1083]
The tutorial https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/using-ha-vpn-with-aws features 2 x VGW (4 x tunnels) with one AWS VPC, which isn't possible. There's a 1:1 VPC/VGW association.

**Comment by ToddKopriva** [comment]
Thanks for the report. If you'd like to make a pull request to make the corretion yourself, I'll get it reviewed and merged. If not, I'll look into getting the correction made.

**Comment by wolruf** [comment]
I won't issue a pull request as I didn't test such a redundant setup with GCP. The network diagram would have to be revamped.

**Comment by ToddKopriva** [comment]
Thanks, @wolruf . I've assigned the issue to the original author of the document.

**Comment by Nogbit** [comment]
It's been some time and others are still using this, can anyone else make the change?

**Comment by jschneider11** [comment]
+Landon Jarzynski <jarzynskil@google.com>

**Comment by ToddKopriva** [comment]
@jarzynskila , could you take a look at this?

**Comment by ToddKopriva** [comment]
This document has been archived.

Here is a newer document on the subject:
https://cloud.google.com/architecture/build-ha-vpn-connections-google-cloud-aws
