### ISSUE TITLE
Managing GCP projects with Terraform is broken in version 3.0

### ISSUE THREAD

**Issue by 4oo** [GoogleCloudPlatform/community#1088]
managing-gcp-projects-with-terraform content is broken. 

https://github.com/GoogleCloudPlatform/community/blob/af5148120947b493d9a19531a763dac4b02b3e00/tutorials/managing-gcp-projects-with-terraform/project.tf#L36

I think it's related to this change that occurred in the terraform version 3 upgrade: https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_project_services

**Comment by ToddKopriva** [comment]
a little extra information from the original bug report:

Description:
terraform error. Invalid resource type "google_project_servuices"

**Comment by 4oo** [comment]
Note that the typo in the extra information ("servuices") is just in the report, and that the actual error message says:
```
Error: Invalid resource type

  on main.tf line 9, in resource "google_project_services" "project_services": 
    9: resource "google_project_services" "project_services" {
 
The provider provider.google does not support resource type "google_project_services".
```
