### ISSUE TITLE
Remove Alpnames from DNSSEC page

### ISSUE THREAD

**Issue by lspgn** [GoogleCloudPlatform/community#1093]
Hello,
I am seeing Alpnames mentioned [here](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/dnssec-cloud-dns-domains/index.md#alpnames). But the company closed earlier this year and all the domains have been transferred to Moniker.
Should it be kept?

Thank you

**Comment by ToddKopriva** [comment]
@dupuy , could you comment on this issue regarding a document that you authored?

**Comment by ToddKopriva** [comment]
Thanks for noting the issue, @lspgn . I removed the reference from the source document here in GitHub. The fix will be republished on cloud.google.com/community soon.
