### ISSUE TITLE
Problem running - source run-gateway

### ISSUE THREAD

**Issue by urosv** [GoogleCloudPlatform/community#1098]
Everything went fine except when running (source run-gateway)
response from RPI

Creating JWT using RS256 from private key file rsa_private.pem
on_publish, userdata None, mid 1
Unable to find key 1
connect status False
on_disconnect 1: Out of memory.
connect status False

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
