### ISSUE TITLE
Need to creat sub domains with docker, nginx-proxy, php-fpm

### ISSUE THREAD

**Issue by dhirajpatra** [GoogleCloudPlatform/community#1117]
Any body can help: Need to creat sub domains with docker, nginx-proxy, php-fpm

localhost -> main word press site
app.localhost -> main php application site 
db.localhost -> phpmyadmin site

Later localhost will be replaced with domaain.com 

I have created docker-compose.yml and related vhost.conf and docker files
Have any body done this with compose files and docker file kindly share.
Thanks

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
