### ISSUE TITLE
Slack Invitation link not available 

### ISSUE THREAD

**Issue by mhamdisemah** [GoogleCloudPlatform/community#1118]
Hi , 
for the Slack Invitation link it is not available here: http://bit.ly/gcp-slack , it shows that i should have a @google.com email

![Capture du 2020-01-06 11-02-41](https://user-images.githubusercontent.com/15904286/71811147-44648780-3074-11ea-92f3-6409b7695d97.png)

**Comment by ToddKopriva** [comment]
Thanks, Mhamdi. I'll look into this.

**Comment by ToddKopriva** [comment]
@mhamdisemah , where did you encounter this bit.ly link?

The Issues section of this GitHub repository is for reporting issues with the community tutorials in this repository. I don't see any places where documents in this repository use this bit.ly link.

**Comment by ToddKopriva** [comment]
Here is a current invitation link for the Google Cloud Slack community:
https://join.slack.com/t/googlecloud-community/shared_invite/enQtODgwMzAyMzg2NTE2LTM5OGMwYmMyMjUxMDJiMmZlNTkyMWQ2YzY3M2VlYzc2OTZkNDkwZDdiMmE2NjdhMzk4Y2ZmZDlhOTM4MmJiZjk

I'm going to close this issue now. Feel free to reopen it if it does, in fact, relate to the tutorials in this repository.

**Comment by arturmkr** [comment]
@ToddKopriva , please send new invitation link.
Invitation link listed above is not working.
