### ISSUE TITLE
Issue with tutorials/network-throughput.md

### ISSUE THREAD

**Issue by jonesrick** [GoogleCloudPlatform/community#1128]
In https://cloud.google.com/community/tutorials/network-throughput there is a section called "TCP window size and RTT not optimized" which reads, in part:

> To fix this issue, you may increase the TCP send and receive windows:
> 
> SO_RCVBUF is influenced by increasing net.core.rmem_default and net.core.rmem_max.
> SO_SNDBUF is influenced by increasing net.core.wmem_default and net.core.wmem_max.

Which is partially correct in the abstract but incomplete, and incorrect for the example iperf3 command-line given earlier on the page.

There are two different sets of sysctls under Linux which affect TCP window sizes.  One is the "net.core" set mentioned above.  It comes into play when applications (eg iperf3) make explicit setsockopt() calls to set SO_SNDBUF and/or SO_RCVBUF.  Making explicit setsockopt() calls for SO_SNDBUF and SO_RCVBUF disables Linux's "autotuning" of socket buffer and thus TCP window size.

The second set come into play when the application does **not** make explicit setsockopt() calls, and so when Linux's autotuning of socket buffer and thus TCP window size is still active:
net.ipv4.tcp_rmem
net.ipv4.tcp_wmem

Given the example iperf3 command line on the page, the "autotuning path" is the path which would be used, because there are no iperf3 command line options used to cause iperf3 to make explicit setsockopt() calls.  So, the operative sysctls would be those of the second set mentioned here.

**Comment by jschneider11** [comment]
I'm forwarding this issue to the internal person who wrote up the guide. I can't find their GitHub username.

**Comment by ToddKopriva** [comment]
Thanks, @jschneider11 .

And thanks to @jonesrick for the report.

**Comment by ToddKopriva** [comment]
@dcavalheiro  , could you have a look at this report about a document that you authored:
https://cloud.google.com/community/tutorials/network-throughput

**Comment by dcavalheiro** [comment]
Yes, sure I will make the corrections
Thanks for the message

**Comment by dcavalheiro** [comment]
Interesting, I thought the update done by Bernie had my part...
let me fix this
*PS: Cloud Support is hiring! See our team's openings in Google Careers
<https://careers.google.com/jobs/results/?company=Google&employment_type=FULL_TIME&hl=en_US&jlo=en_US&q=%22cloud%20technical%20solutions%20engineer%22&sort_by=relevance>
or Grow
<https://grow.googleplex.com/jobs/search?query=%22cloud%20technical%20solutions%20engineer%22>*


Daniel Cavalheiro

Technical Solutions Architect | Google Cloud Support | CA-WAT-BRT2-2G1116-F
Working from Home :)

*51 Breithaupt St, Kitchener, ON N2H 5G5, Canada*

dcavalheiro@google.com | (519) 880-3438

**Comment by dcavalheiro** [comment]
Changes made at:

https://github.com/GoogleCloudPlatform/community/compare/master...dcavalheiro:patch-3

**Comment by ToddKopriva** [comment]
Thanks, Daniel. If you create a pull request, I'll review it and get it merged.

**Comment by ToddKopriva** [comment]
fixed by #1285
