### ISSUE TITLE
Read specific logs from App through gcloud app logs tail 

### ISSUE THREAD

**Issue by mflash123** [GoogleCloudPlatform/community#1129]
Issue Description : gcloud app logs tail  doesnt log specific logs, created by APP

I have Laravel with stackdriver logs enabled.
Ex: 
```
Route::get('/', function () {
    Log::info("Hello Stackdriver! This will show up as log level INFO!");
    return view('welcome');
});

```
And I can read that logs through Google Web console in logs (journals)
How can I get read same logs through gcloud app logs tail ?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
