### ISSUE TITLE
Tutorial: Create simple, text-driven bot with Cloud Functions

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/community#113]
Similar to this article:

“Create a simple, free, text-driven Twitterbot with AWS Lambda & Node.js”
https://medium.com/@emckean/create-a-simple-free-text-driven-twitterbot-with-aws-lambda-node-js-b80e26209f5

Also, I don't know if we can use Twitter APIs here.

**Comment by ToddKopriva** [comment]
There seem to be a few of these:
https://www.therobinlord.com/creating-a-twitter-bot-using-google-cloud-functions/
https://www.cookieshq.co.uk/posts/how-to-build-a-serverless-twitter-bot-with-python-and-google-cloud
https://dev.to/googlecloud/beep-boop-scheduling-a-twitter-bot-with-cloud-functions-and-cloud-kms-encrypted-secrets-2f1b
https://medium.com/@irvollo/build-a-serverless-twitter-bot-with-javascript-and-google-cloud-functions-9f86109e3248
