### ISSUE TITLE
Broken Link on Tutorial: Serve Machine Learning Model on App Engine Flexible Environment

### ISSUE THREAD

**Issue by dcstang** [GoogleCloudPlatform/community#1130]
https://cloud.google.com/community/tutorials/appengine-serve-machine-learning-model

I am referring to the above tutorial by @dizcology.
The first line asks to refer to a sample app called "Model Serve". but the link is broken.

Further down on the tutorial the main.py link is broken as well. 

Am trying to follow the tutorial but it is proving a bit frustrating!

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll have a look.

**Comment by ToddKopriva** [comment]
fixed by this PR:
https://github.com/GoogleCloudPlatform/community/pull/1235
