### ISSUE TITLE
Integrate Forseti security with Google cloud security command centre.

### ISSUE THREAD

**Issue by HarshalRane23** [GoogleCloudPlatform/community#1140]
We followed this article to integrate the forseti with cloud security command centre. In below document its mentioned in Enable Cloud SCC with Forseti plugin this section how to integrate
https://cloud.google.com/community/tutorials/private-forseti-with-scc-integration
After doing this we still can’t see the forseti findings in the cloud SCC dashboard.

**Comment by ToddKopriva** [comment]
@fawix : Fatima, could you take a look at this issue reported about a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
@HarshalRane23 : Thanks for the report.

**Comment by fawix** [comment]
@HarshalRane23 did you re-run terraform apply ?

**Comment by HarshalRane23** [comment]
Yes we ran the terraform apply two time's. But we have selected the right
service account for the Forseti connector that connects to the Cloud
security center.

**Comment by HarshalRane23** [comment]
@fawix @ToddKopriva  any solution for this issu, we are going live in production in few days any help here is much appreciated.

**Comment by fawix** [comment]
@HarshalRane23 - you need to rerun terraform apply after you modify the files to add 
`cscc_violations_enabled` and `cscc_source_id`  you can validate if the configuration was applied successfully with the following command

```
gsutil cat gs://forseti-server-[id]/configs/forseti_conf_server.yaml | grep cscc -A6
```

Please check step 4 on section `Configuring the CSCC integration in Forseti` to make sure you have modified the files accordingly; 

If you still having trouble please post the result of the above and check if you are seeing violations being created in the forseti bucket; also what are the results when you run scanner directly on the forseti VM? Do you see violations being triggered?

**Comment by ToddKopriva** [comment]
@HarshalRane23 , it seems that @fawix has given you the information that you need, so I am going to close this issue.

If you still think that there is a problem with the tutorial, feel free to re-open the issue, being sure to respond to the suggesitons in the previous comment.

Also, if you are having problems beyond this tutorial, I recommend bringing questions to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
