### ISSUE TITLE
Issue with tutorials/python-vision-quickstart.md

### ISSUE THREAD

**Issue by ninhenzo64** [GoogleCloudPlatform/community#1147]
Tutorial doesn't seem to match the latest version of the api

$ python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 54, in <module>
    run_quickstart()
  File "quickstart.py", line 25, in run_quickstart
    from google.cloud import vision
ImportError: cannot import name vision

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll have a look.

**Comment by ToddKopriva** [comment]
This is fixed in the sample code that the tutorial points to.
