### ISSUE TITLE
Wordcount tutorial hangs on Dataflow runner on 2.18.0

### ISSUE THREAD

**Issue by duttley** [GoogleCloudPlatform/community#1148]
When running the WordCount examples from the Gitter8 Scio and MVN Java project, the job hangs when the worker has been created. 

"org.apache.beam" % "beam-runners-google-cloud-dataflow-java" % 2.18.0. 

If I drop the version down to 2.17.0 then the job works.

This is running on the Dataflow runner.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into this.

**Comment by CarreauClement** [comment]
Same thing with version 2.19. The scio wordcount just hangs after the worker has been created. Works when dropping to 2.17.

**Comment by ToddKopriva** [comment]
Thanks for the confirmation, @CarreauClement .

**Comment by anantdamle** [comment]
@duttley @CarreauClement are you referring to [Count words with Dataflow and Python](https://cloud.google.com/community/tutorials/python-dataflow-quickstart) tutorial located [here](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/python-dataflow-quickstart.md)?

**Comment by anantdamle** [comment]
@duttley @CarreauClement can you point me to the related tutorial for me to take a look?

**Comment by ToddKopriva** [comment]
closing because the wordcount tutorial with Dataflow and Java has been removed
