### ISSUE TITLE
Can't select a numeric PROJECT_ID 

### ISSUE THREAD

**Issue by hmiguel** [GoogleCloudPlatform/community#1154]
Hi,

I have a project running on gcloud where the `project_id` is a numeric number and I can't set project via `gcloud init` neither `gcloud config set project`.

`> gcloud projects list`
`PROJECT_ID                NAME              PROJECT_NUMBER`
`823572                    823572            62375466762`

`> gcloud config set project 823572`
`ERROR: (gcloud.config.set) The project property must be set to a valid project ID, not the project number [823572]`

`Google Cloud SDK 280.0.0`

Any ideas?

Thanks in advance

**Comment by hmiguel** [comment]
Opened @ https://issuetracker.google.com/issues/149632187

**Comment by ToddKopriva** [comment]
Thanks for following up with the issue report.
