### ISSUE TITLE
LattePanda Delta for object recognition

### ISSUE THREAD

**Issue by ramononiko** [GoogleCloudPlatform/community#1159]
if anyone can help me on my study of doing a device for object recognition.
tensorflow will be my framework.
how to implement it. a stand alone program that will be put to LattePanda Delta

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
