### ISSUE TITLE
Issue with tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md

### ISSUE THREAD

**Issue by lawrghita** [GoogleCloudPlatform/community#1160]
Issue Description:
Maybe put a warning about the cost, I use just free tier instances but forgot about Flex Costs:
- App Engine Flex Instance RAM: 21 hours = billed $0.15
- App Engine Flex Instance Core Hours: 21 Hours = billed $1.14

**Comment by ToddKopriva** [comment]
That's a good request. Thanks.

**Comment by ToddKopriva** [comment]
fixed with PR #1714
