### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by sanvila** [GoogleCloudPlatform/community#1167]
Syntax for credentials seems to be old. Now it says:

`credentials = "${file("CREDENTIALS_FILE.json")}"`

But Terraform v0.12.21 issues a warning like this:

Warning: Interpolation-only expressions are deprecated

The following line removes the warning:

`credentials = file("CREDENTIALS_FILE.json")`

Thanks.

**Comment by ToddKopriva** [comment]
Thanks for the report, @sanvila .

**Comment by ToddKopriva** [comment]
@chrisst  , could you have a look at this request for an update to a tutorial that you created?

**Comment by chrisst** [comment]
Good catch thanks! I'll update shortly.

**Comment by ToddKopriva** [comment]
Thanks for the fix, @chrisst .
