### ISSUE TITLE
Broken: Basic FIM does not update failed-file checksums

### ISSUE THREAD

**Issue by jjinno** [GoogleCloudPlatform/community#1170]
https://github.com/GoogleCloudPlatform/community/blob/712bd5d0a6850990f59648bde0d453910bb626f7/tutorials/gcp-cos-basic-fim/scan.sh#L117

Sorry no PR.  Line should be:
```    for FAILEDFILE in `cat $FAILEDFILES | cut -d ":" -f 1`; do```

(aka: `cat` instead of `echo`... otherwise looping over 1 filename)

**Comment by ianmaddox** [comment]
Thank you for the bug report and pull request!
