### ISSUE TITLE
Adding sound in ML Tensorflow: <Sound per bounding box labels>

### ISSUE THREAD

**Issue by ramononiko** [GoogleCloudPlatform/community#1185]
ML Tensorflow adding sound

Technical Level
beginner 

Please help me.

Thanks!

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
