### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by waynean** [GoogleCloudPlatform/community#1188]
In the section of...
Configure Ingress Resource to use NGINX Ingress Controller

We should mention...
Deploying multiple Ingress controllers, of different types (e.g., ingress-nginx & gce), and not specifying a class annotation will result in both or all controllers fighting to satisfy the Ingress, and all of them racing to update Ingress status field in confusing ways.

source:
https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/

**Comment by ToddKopriva** [comment]
Thanks for the report.

@ameer00 , could you have a look at this issue report about a tutorial that you worked on?
