### ISSUE TITLE
Tutorial Request: Running web site/service on kubernetes with HTTPs cert using LetsEncrypt

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/community#119]
Interesting projects to make use of
- [Kube-Lego](https://github.com/jetstack/kube-lego)
- [Hugo](https://gohugo.io/)
- [git-sync](https://github.com/kubernetes/git-sync/)

**Comment by face1m** [comment]
Could you include step by steps for Debain 9 (Stretch) on installing SSL certificates on port 443 thanks

**Comment by VikramTiwari** [comment]
I found this few days back. Pretty good tutorial. https://github.com/ahmetb/gke-letsencrypt/ by @ahmetb

**Comment by ToddKopriva** [comment]
See this qwiklab:
https://www.qwiklabs.com/focuses/2771?parent=catalog
"Deploy a Web App on GKE with HTTPS Redirect using Lets Encrypt"
