### ISSUE TITLE
"2 Spring WebApplicationInitializers detected on classpath" when following tutorials/deploy-grails-to-google-cloud/index.md

### ISSUE THREAD

**Issue by douglasom** [GoogleCloudPlatform/community#1192]
When deploying my grails 4.0.1 app to google cloud I get the following error:

`2 Spring WebApplicationInitializers detected on classpath`

Although the error is disturbing, the app seems to work fine. I would very much appreciate if a fix for the tutorial or at least considerations were made. Thank you.

**Comment by ToddKopriva** [comment]
Thanks for the report, @douglasom . I'll look into it.

**Comment by ToddKopriva** [comment]
@sdelamo , do you have any insight into the issue reported here about a document that you contributed?
