### ISSUE TITLE
Issue with tutorials/setting-up-ruby-discourse.md

### ISSUE THREAD

**Issue by cl0udmaker** [GoogleCloudPlatform/community#1194]
Issue Description:
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This deployment has too many files. New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to 10000
      files for this app.
    field: version.deployment.files[...]

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into it.

**Comment by cl0udmaker** [comment]
It's a user readability error. Moving app.yaml to app directory (instead of root) solved the issue.

**Comment by cl0udmaker** [comment]
Although now getting gem error, so app.yaml must be in the root directory of the project then:
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error! Code: APP_CONTAINER_CRASHED
Could not locate Gemfile or .bundle/ directory

**Comment by cl0udmaker** [comment]
Thanks!

**Comment by ToddKopriva** [comment]
@hxiong388 , can you take a look at this issue regarding a document that you contributed?
