### ISSUE TITLE
Issue with tutorials/setting-up-lamp/index.md

### ISSUE THREAD

**Issue by githubsrinath** [GoogleCloudPlatform/community#1201]
Issue Description
option  the OS images tab, choose a Debian 7.x, Ubuntu 14.04, CentOS 6.x, or CentOS 7.x version.

doest show shows only debian 9 which debian is choosen.  hence i am not able to install lamp full stack.

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll see what updates need to be made.

**Comment by ToddKopriva** [comment]
fixed by this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1513
