### ISSUE TITLE
Issue with tutorials/appengine-serve-machine-learning-model/index.md

### ISSUE THREAD

**Issue by mandeville135** [GoogleCloudPlatform/community#1204]
It looks like the links to the files 404 now when they are followed. I think the directory structure in the github has changed

**Comment by ToddKopriva** [comment]
Thanks for the report, @mandeville135 .

**Comment by ToddKopriva** [comment]
fixed by this PR:
https://github.com/GoogleCloudPlatform/community/pull/1235
