### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by tomnunn** [GoogleCloudPlatform/community#1205]
Hi there!

I've recently been looking at setting `http_headers` (https://cloud.google.com/appengine/docs/standard/php7/config/appref). I'm assuming for a WordPress instance it's recommended to set such headers within the applications code, especially when using GAE as from what I can see existing WordPress plugins set http_headers in a .htaccess file.

Would you suggest setting such http headers within the `gae-app.php` file?

Thank you.

**Comment by ToddKopriva** [comment]
@bshaffer , can you help with this question?
