### ISSUE TITLE
Issue with tutorials/deploy-mean-app-mongodb-replication.md

### ISSUE THREAD

**Issue by johnfernow** [GoogleCloudPlatform/community#1210]
The following command does not work.
> Navigate to the default application folder:
> `cd /opt/bitnami/apps/`

![directory-doesnt-exist](https://user-images.githubusercontent.com/31441141/78518624-ffddaa80-778e-11ea-9b69-19208c3729b9.png)

I see the directory `/opt/bitnami/` does indeed exist, so not sure if we should `cd` into that and run `mkdir apps`, or if something has changed and `apps/` has been moved or renamed.

Not knowing which it was, I created an `apps/` directory in `/opt/bitnami/` and continued with the tutorial, following it as closely as possible. When it got to the part where we register a new user account, I received the following error
![MongoError-authentication-failed](https://user-images.githubusercontent.com/31441141/78518976-e5580100-778f-11ea-8b94-a7afb5736116.png)

Not sure if that's a related error or not, but either way, it appears something has changed and needs updated.

Thanks.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll have a look.

**Comment by ToddKopriva** [comment]
closing because the outdated tutorial has been archived
