### ISSUE TITLE
have this error''Installation failed: Could not create directory''

### ISSUE THREAD

**Issue by ousamajafar** [GoogleCloudPlatform/community#1211]
After installing wordpress on standard ApppEngine I tried to install Plugins but I rcieved this error: ''Installation failed: Could not create directory''

**Comment by ToddKopriva** [comment]
Is this a question about one of the documents hosted in this repository?

The Issues section of this GitHub repository is not the best place to get troubleshooting help.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
