### ISSUE TITLE
Issue with tutorials/cloud-iot-gateways-rpi/index.md

### ISSUE THREAD

**Issue by reembayoumi** [GoogleCloudPlatform/community#1220]
Issue Description
Seems I have problem running source gateway command.
source run-gateway

Creating JWT using RS256 from private key file rsa_private.pem
on_publish, userdata None, mid 1
Unable to find key 1
connect status False
on_disconnect 1: Out of memory.
connect status False

**Comment by demessmaker** [comment]
Seeing same issue as well

**Comment by ToddKopriva** [comment]
@hongalex , can you take a look at this report that a couple of folks are having trouble with this tutorial that you contributed?
https://cloud.google.com/community/tutorials/cloud-iot-gateways-rpi

**Comment by hongalex** [comment]
You probably need to edit the `project_id` in the `run-gateway` file. I'll update the tutorial to fix this.
