### ISSUE TITLE
Issue with tutorials/storage-quickstart.md

### ISSUE THREAD

**Issue by ataiya** [GoogleCloudPlatform/community#1221]
Broken links to "Navigation Menu" and "Create bucket" in this page
https://cloud.google.com/community/tutorials/storage-quickstart?hl=en

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll get those fixed.

**Comment by ToddKopriva** [comment]
Those links are misleading in the web tutorial, but they are functional in the in-console version of the tutorial.

So, this is working as intended, even though I agree that the design for the web version of the tutorial should be reconsidered.
