### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-strongswan/index.md

### ISSUE THREAD

**Issue by matut0** [GoogleCloudPlatform/community#1222]
Hi,

The configuration on the strongswan for esp & ike must be changed to:

esp=aes128-sha1-modp2048!
ike=aes128-sha1-modp2048!

from:

ike=aes256gcm16-sha512-modp4096
esp=aes256gcm16-sha512-modp8192

Otherwise the following error appears:

DH group MODP_2048 inacceptable, requesting MODP_4096

After doing the change, the vpn tunnel works as expected.

I'm using a NAT StrongSwan host on my network and a classic cloud vpn gateway.

Regards,

Germán Pabón

**Comment by ToddKopriva** [comment]
Thanks for the note. We'll check it out.

**Comment by ToddKopriva** [comment]
@Civil , can you have a look at this report regarding a document that you contributed?

**Comment by ToddKopriva** [comment]
moved unmaintained tutorial to archive

https://github.com/GoogleCloudPlatform/community/pull/2425
