### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by bfarayev** [GoogleCloudPlatform/community#1227]
Issue Description:

I think we need to update the documentation to work with helm 3 as it's not using tiller anymore. Happy to contribute to it

**Comment by ToddKopriva** [comment]
Thanks for the report. If you want to submit a pull request to make the fix, we can review it and get it merged. If not, then we can put this in the queue for us to update.

**Comment by ameer00** [comment]
#1551 fixes this.
