### ISSUE TITLE
Run an Elixir Phoenix app in containers using Google Kubernetes Engine issue

### ISSUE THREAD

**Issue by maksimf** [GoogleCloudPlatform/community#1232]
Running

```
kubectl expose deployment hello-web \
    --type=LoadBalancer --port 80 --target-port 8080
```

Returns

```
Error from server (NotFound): deployments.extensions "hello-web" not found
```

Probably there is a missed step [in the article](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/elixir-phoenix-on-kubernetes-google-container-engine/index.md#deploy-to-the-cluster).

**Comment by ToddKopriva** [comment]
@dazuma , could you have a look at this report of an issue with a document that you worked on?

**Comment by maksimf** [comment]
Should it say
```
kubectl expose pod hello-web \
    --type=LoadBalancer --port 80 --target-port 8080
```

**Comment by maksimf** [comment]
https://github.com/GoogleCloudPlatform/community/pull/1233
