### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by amrit3327** [GoogleCloudPlatform/community#1234]
Provider.tf mentioned in the documentation is not working as credential file call may not be correct
Existing one
// Configure the Google Cloud provider
provider "google" {
 credentials = file("CREDENTIALS_FILE.json")
 project     = "flask-app-211918"
 region      = "us-west1"
}

New one
// Configure the Google Cloud provider
provider "google" {
 credentials = "${file("CREDENTIALS_FILE.json")}"
 project     = "flask-app-211918"
 region      = "us-west1"
}

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll check it out.

**Comment by chrisst** [comment]
@amrit3327 what version of Terraform are you using? The syntax you are proposing in the "new one" appears to be 0.11 style syntax which is deprecated in the latest version of Terraform.

**Comment by ToddKopriva** [comment]
So, @chrisst , it seems that there isn't an issue to be fixed here, unless it's the need to have an explicit mention of the Terraform version. Is that correct?

**Comment by chrisst** [comment]
@ToddKopriva I think that will be enough to address this bug. I added https://github.com/GoogleCloudPlatform/community/pull/1333 if you want to take a look.

**Comment by ToddKopriva** [comment]
Thanks for that. I just merged the pull request that adds the explicit statement about the version number for Terraform.

**Comment by amrit3327** [comment]
Cool. I may be using 0.11 which i am not sure right now. But thanks for looking into it will help others.
    On Monday, July 6, 2020, 02:49:33 PM EDT, Todd Kopriva <notifications@github.com> wrote:  
 
 


Thanks for that. I just merged the pull request that adds the explicit statement about the version number for Terraform.
