### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-strongswan/index.md

### ISSUE THREAD

**Issue by coolsaigit** [GoogleCloudPlatform/community#1238]
Issue Description

We are trying to get IPSec vpn tunnel over the partner interconnect using Strongswan. We are able to create the tunnel however BGP is not working so the routing is failing. Not sue if we need to configure anything on the GCP side.

**Comment by ToddKopriva** [comment]
Thanks for the report.

We can look into whether there is an issue with the tutorial, but that might not be very helpful to you in immediately solving your current problem.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
