### ISSUE TITLE
Issue with tutorials/compute-quickstart.md

### ISSUE THREAD

**Issue by Joe-at-LA** [GoogleCloudPlatform/community#1253]
The tutorial currently fails at the end when bringing up the frontend in a browser as it is unable to connect. The first evidence of an issue is in the steps near the end where the command `install npm` generates an error. The issue appears to be with contextify@0.1.15 install: `node-gyp rebuild`. It seems that something in Contexify is broken.

**Comment by ToddKopriva** [comment]
Thanks for the report, @Joe-at-LA .

**Comment by ToddKopriva** [comment]
closed because we recently completely redid this tutorial
