### ISSUE TITLE
Issue with tutorials/setting-up-lamp/index.md

### ISSUE THREAD

**Issue by APratham** [GoogleCloudPlatform/community#1255]
There is an issue with this tutorial for setting up LAMP on Google Cloud Compute Engine. When telling how to install MySQL on Ubuntu it tells 
`sudo apt-get install mysql-server php5-mysql php-pear`
The problem here is on Ubuntu 9 we installed `php` and `libapache2-mod-php` so it should be 
`sudo apt-get install mysql-server php-mysql php-pear`

I was getting an error `E: Package 'php5-mysql' has no installation candidate` that's when I realised that

**Comment by ToddKopriva** [comment]
Thanks for the report, @APratham .
