### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-cisco-asr/index.md

### ISSUE THREAD

**Issue by jschneider11** [GoogleCloudPlatform/community#1256]
This tutorial is using an example IP range of 204.237.220.0/27, which is used by Google internally.
Please update this documentation to use IPs that the IETF specifies for documentation as described in RFC5737:https://tools.ietf.org/html/rfc5737.

Please cc: harrisjoe@google.com on this issue.

Thanks.

**Comment by ToddKopriva** [comment]
@ashishverm , I'm copying you on this as a co-assignee because this is a document that you submitted:
https://cloud.google.com/community/tutorials/using-cloud-vpn-with-cisco-asr

If you aren't able to submit a fix, then I'll work with Julie on doing so.

**Comment by jschneider11** [comment]
Hi, Todd,
Ashish doesn't own the VPN Interop guides any more. The new owner is Patrick Foster (pfos@google.com). However, for an important fix like this, I can work with you to make the changes. Patrick should be cc:d on this pull request as well as Joe Harris.

Thanks.

**Comment by ToddKopriva** [comment]
Thanks, Julie.

**Comment by jarzynskila** [comment]
PR for the text: https://github.com/GoogleCloudPlatform/community/pull/1288

A second PR for the diagrams coming soon...

**Comment by ToddKopriva** [comment]
fixed by PR #1288
