### ISSUE TITLE
Examples : Compute Engine Pricing Expressions.

### ISSUE THREAD

**Issue by nepolean2** [GoogleCloudPlatform/community#1258]
Best practices to use GCP cloud billing APIs(to getting all SKUs) and how to write a generic pricing expression to satisfy most of the cases.

**Comment by nepolean2** [comment]
Can we get the update on this ticket

**Comment by nepolean2** [comment]
@ToddKopriva Could you please update the status on the issue... Thanks for your time.

**Comment by ToddKopriva** [comment]
You submitted a tutorial request. There is no guaranteed timing on when or whether someone will choose to pick up this request and write a document about this subject.

If you have a time-sensitive need for information, then I recommend that you bring your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by nepolean2** [comment]
@ToddKopriva Thanks for your reply
