### ISSUE TITLE
FATA[0000] gateway-backend setup failed: gateway/gcp_pub_sub: downlink topic 'eu868-gateway-commands' does not exis t

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/community#1261]
xxxxgooplay@xxxx:~$ sudo chirpstack-network-server
INFO[0000] starting ChirpStack Network Server            band=EU_863_870 docs="https://www.chirpstack.io/" net_id=0
00000 version=3.9.0
INFO[0000] storage: setting up storage module           
INFO[0000] storage: setting up Redis client             
INFO[0000] storage: connecting to PostgreSQL            
INFO[0000] storage: applying PostgreSQL data migrations 
INFO[0000] storage: PostgreSQL data migrations applied   count=0
INFO[0000] gateway/gcp_pub_sub: setting up client       
INFO[0000] gateway/gcp_pub_sub: setup downlink topic     topic=eu868-gateway-commands
FATA[0000] gateway-backend setup failed: gateway/gcp_pub_sub: downlink topic 'eu868-gateway-commands' does not exis
t 

Can you help me see my question？

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by radianceltd** [comment]
Thank u for help
