### ISSUE TITLE
Tutorial Request - Serve videos with GCP / Nginix?

### ISSUE THREAD

**Issue by kumzme** [GoogleCloudPlatform/community#1263]
HI I navigated from `

> https://cloud.google.com/community/tutorials/https-load-balancing-nginx 

`
using this link 
[ Submit tutorial ](https://github.com/GoogleCloudPlatform/community/issues?q=is%3Aopen+is%3Aissue+label%3A%22tutorial+request%22) 

to here. 

I am new to serviing videos . How do we do that . Can someone help me stream videos tousers using GCP and do we need NGINIX to serve them ? so we can load balance ? This way I can stream paid content

**Comment by ToddKopriva** [comment]
That's a good tutorial request. 

It takes a while for folks to turn such requests into tutorials. If you want help sooner, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by kumzme** [comment]
ok lemme do that now .. if there is any good info , I will submit that as tutorials

**Comment by APratham** [comment]
@ToddKopriva Can I work on this? I have been looking for a livestreaming solution on Google Cloud and I have some information on how to build it. Once I have built my own solution, I can publish the tutorial

**Comment by ToddKopriva** [comment]
> @ToddKopriva Can I work on this? I have been looking for a livestreaming solution on Google Cloud and I have some information on how to build it. Once I have built my own solution, I can publish the tutorial

Please do. Thanks for looking into this.
