### ISSUE TITLE
Device Communication via pub/sub message.

### ISSUE THREAD

**Issue by hsnhrn** [GoogleCloudPlatform/community#1264]
Is there any way of sending the acknowledgment message to the device back? e.g. if device has published something to the cloud functions via pub/sub then it could receive an acknowledgment message back from cloud function to the device via another pub/sub message? 

i am right now doing it via command topics but sometime the messages are lost in between...

**Comment by hsnhrn** [comment]
Hi @ToddKopriva  i thought it could also be a good tutorial. 
e.g. Publishing data to Pub/Sub subfolder using Http bridge.. Thats why posted here

**Comment by ToddKopriva** [comment]
OK. I'll mark this as a tutorial request. Thanks.
