### ISSUE TITLE
Issue with tutorials/building-android-apk-with-cloud-build-gradle-docker-image.md

### ISSUE THREAD

**Issue by syslogic** [GoogleCloudPlatform/community#1265]
The account which hosts `fullstackgcp/gradle` seems to be out of credit:
```
Already have image (with digest): gcr.io/cloud-builders/docker
Unable to find image 'gcr.io/fullstackgcp/gradle:latest' locally
latest: Pulling from fullstackgcp/gradle
e79bb959ec00: Pulling fs layer
d4b7902036fe: Pulling fs layer
1b2a72d4e030: Pulling fs layer
d54db43011fd: Pulling fs layer
1a97c78dad71: Pulling fs layer
6dcb79eeeda4: Pulling fs layer
bd56246cf4fd: Pulling fs layer
88cea60f56c5: Pulling fs layer
1b4368c500a3: Pulling fs layer
8485dee1c89f: Pulling fs layer
d54db43011fd: Waiting
1a97c78dad71: Waiting
6dcb79eeeda4: Waiting
bd56246cf4fd: Waiting
88cea60f56c5: Waiting
1b4368c500a3: Waiting
8485dee1c89f: Waiting
/usr/bin/docker: error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectAccountProblem</Code><Message>User project billing account not in good standing.</Message><Details>The billing account for the owning project is disabled in state delinquent</Details></Error>".
See '/usr/bin/docker run --help'.
```

**Comment by syslogic** [comment]
Meanwhile I've wrote [`cloudbuild-android-builder`](https://github.com/syslogic/cloudbuild-android-builder), which provides a similar docker container. Since Android projects merely use the Gradle wrapper, it is based upon `openjdk:8` and not `gradle`. Still would need to split the docker container build from the dummy Android app; alike it is suffices as an example, but it's still a work in progress.

**Comment by ToddKopriva** [comment]
@Timtech4u , this report suggests that a resource that your tutorial depends on is no longer available.. Could you take a look?

**Comment by Timtech4u** [comment]
HI @ToddKopriva , I'd love to take a look. @syslogic would you like to reach out so I'll update this with your tutorial. Email is on my profile. Thanks

**Comment by syslogic** [comment]
@Timtech4u I'd guess the mere problem was, that you've hosted the built container for everybody.
My version does not provide any image, but only the project which builds it (no traffic = no costs).
Since GitHub nicely integrates with Cloud Build, anybody can use that as source repository...

**Comment by ToddKopriva** [comment]
@Timtech4u , is this still an open issue? Is there still a problem that needs to be fixed?

**Comment by fstanis** [comment]
I just came across this article too - it seems the image no longer exists, so it's hard to piece together how to make the buid APK flow. Is it possible to add a new image? If not, perhaps a warning at the top of the article would help.

**Comment by ToddKopriva** [comment]
Thanks, @fstanis . If @Timtech4u doesn't respond in the next day or so, I'll go ahead and archive this.

**Comment by syslogic** [comment]
The image which my project builds does so with latest versions; just recently updated. For me this is just a prime example, for how well it goes when declaring Africans as experts, while discriminating against intelligence. Since this one GDE incident fueled by pure racism I've lost all respect for Google.

**Comment by ToddKopriva** [comment]
@Timtech4u , since you aren't able to bring the resource back that this tutorial depends on, I'm going to archive it now.
