### ISSUE TITLE
Issue on "managing-gcp-projects-with-terraform"

### ISSUE THREAD

**Issue by Jojoooo1** [GoogleCloudPlatform/community#1266]
Hi,

In your tutorial [Tutorial](https://cloud.google.com/community/tutorials/managing-gcp-projects-with-terraform) you do not set at any moment iam-policy on your terraform account for creating compute resources ?

All the best.

Jonathan.

(Relying on default service account is not recommended & since roles are set during project would be better to follow the least)

**Comment by ToddKopriva** [comment]
@chrisst , the original author is not available to look at this, and you worked on a related tutorial about using Terraform with Google Cloud. Could you have a look at this request?

**Comment by chrisst** [comment]
The article describes how to create a new service account and does give it a limited set of IAM permissions using gcloud only for the purpose of creating gcp projects. For the scope of the document I think this is sufficient.
If you are looking for more general guidance on GCP IAM I recommend https://cloud.google.com/iam/docs/quickstart or https://cloud.google.com/iam/docs/using-iam-securely.

**Comment by ToddKopriva** [comment]
Thanks, @chrisst .
