### ISSUE TITLE
Issue with tutorials/using-ha-vpn-with-aws/index.md

### ISSUE THREAD

**Issue by chbussler** [GoogleCloudPlatform/community#1267]
Issue Description

The formatting of this does not work at all:

gcloud compute external-vpn-gateways create [PEER_GW_NAME] \
--interfaces 0=[AWS_GW_IP_0],  \
             1=[AWS_GW_IP_1],  \
             2=[AWS_GW_IP_2],  \
             3=[AWS_GW_IP_3]

This works as there are no blanks:

gcloud compute external-vpn-gateways create peer-gw --interfaces \   
0=52.52.128.71,1=184.169.223.3,2=13.52.115.71,3=52.9.164.225

**Comment by ToddKopriva** [comment]
Thanks for the report, @chbussler .
