### ISSUE TITLE
Google Cloud Function Authenticating Access to Google Drive to read CSV file

### ISSUE THREAD

**Issue by maryLisbon** [GoogleCloudPlatform/community#1271]
Hi,
I have written a Python code that works on my local machine, now I want to use Google cloud function + google scheduler to 
1: Read a CSV file from my google drive from within GC function and then do some stuff on it.
2:  Use Google scheduler to run this code twice a day. 
I am stuck at where I have to authenticate google cloud function to access google drive. The original code is like below, but this needs client_secrets.json. Is there any other way to allow GC function to access the CSV file on the google drive? 

gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':"1P3dhfjdhfjkshfjshfjkshfks"})   
 downloaded.GetContentFile('alert.csv')
 data = pd.read_csv('alert.csv') 
 return data

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
