### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md - Nginx Ingress requires an hostname now

### ISSUE THREAD

**Issue by romainr** [GoogleCloudPlatform/community#1274]
It seems that we must specify an hostname now in the ingress https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/nginx-ingress-gke/ingress-resource.yaml (which make the tutorial impossible to do?)

 > n/n was rejected: Ingress rule contains empty host

PS: not the same, but `nginx.ingress.kubernetes.io/rewrite-target: /$1` also seems to break now

**Comment by ToddKopriva** [comment]
Thanks for the report, @romainr .

@ameer00 , can you have a look at this report about a tutorial that you worked on?

**Comment by romainr** [comment]
Actually, it might be because I used the non Kubernetes community implementation of the ingress https://github.com/nginxinc/kubernetes-ingress/issues/962 (maybe we could have the 'helm repo add ...' command.

Tutorial page:
https://cloud.google.com/community/tutorials/nginx-ingress-gke

**Comment by ameer00** [comment]
@romainr I am using the stable `nginx-ingress` from the helm charts
```helm install --name nginx-ingress stable/nginx-ingress```
The tutorial is intended to be used with this chart. 
Can you try with this and let me know if you run into any issues?
thx

**Comment by romainr** [comment]
Sorry for the confusion, it indeed works if you use the second one

```
helm repo add nginx-stable https://helm.nginx.com/stable
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
```

**Comment by ToddKopriva** [comment]
Thanks for updating us with what worked. I'm glad that it's working for you now.
