### ISSUE TITLE
I would like to request an update - Google Click To Deploy

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/community#1279]
https://console.cloud.google.com/marketplace/details/click-to-deploy-images/wordpress?id=00a8bad7-693b-4911-9f10-7bef620bdd13 

Is it possible to request an update, for example every time I install, it says PHP version is outdated and when I try it on my end nothing works. 

Which is the right place to contact?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is for reporting issues with the community tutorials in this repository.

I recommend giving your feedback by clicking **Send Feedback** in the **Help** menu in the Cloud Console, as described here:
https://cloud.google.com/support/docs/community#report_bugs_and_request_features
