### ISSUE TITLE
ERROR : connecting cloud SQL with workbench 

### ISSUE THREAD

**Issue by llmiell** [GoogleCloudPlatform/community#128]
We found error at Mysql Workbench  : **Lost connection to MySQL server at 'reading initial communication packet', system error: 0 (2013)**

**Comment by jmdobry** [comment]
Can you specify which tutorial?

**Comment by ToddKopriva** [comment]
Without more detail, we can't fix this issue. 

I'm closing this issue now, but feel free to re-open it if you can give more detail about exactly where this problem occurs, including a reference to the specific tutorial and the step in that tutorial.
