### ISSUE TITLE
Issue with tutorials/cloud-functions-twilio-voice-record/index.md

### ISSUE THREAD

**Issue by miguelc95** [GoogleCloudPlatform/community#1281]
Issue Description: 
I did the full tutorial and I am getting this error: 
INVALID_ARGUMENT: Invalid audio file: length is shorter than required header length.

At the analyzeCall cloud function, how can I get this to work?

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll have a look.

**Comment by thanh90** [comment]
what is the status of this bug ? i got the same problem when uploading a recorded wav file from ios
