### ISSUE TITLE
Updating PHP version for Wordpress deployment on Compute Engine

### ISSUE THREAD

**Issue by MunchDev** [GoogleCloudPlatform/community#1282]
After struggling for days trying to figure out how to change the PHP version used by Wordpress, I give up and go here for help.
I cannot find any tutorial associated with this problem. Some very old articles mention about migrating to another instance, which I am kind of unfamiliar.
Both by running ```php -v``` and ```php7.3 -v``` gives PHP 7.3, however, it seems like Wordpress does not see it. I also try adding it to ```PATH```, but it does not work.
Please post a tutorial for this, thanks!

**Comment by ToddKopriva** [comment]
We'll look into creating a new tutorial about this. 

In the meantime, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by MunchDev** [comment]
Thanks for replying @ToddKopriva,
I managed to do it by running the followings:
```
sudo a2dismod php7.0
sudo a2enmod php7.3
sudo service apache2 restart
```

**Comment by ToddKopriva** [comment]
Thanks for reporting back with what worked for you.
