### ISSUE TITLE
Terraform for GCP resources

### ISSUE THREAD

**Issue by ousama-alnemer** [GoogleCloudPlatform/community#1284]
Hi experts,

What I need exactly to be able to create all google cloud resources via **terraform**. I have already google cloud account and many resources but I need to deploy every resources through terraform for all projects. and is there possibility to use terraform as a shared deployment tool for cloud team that responsible to deploy google cloud resources

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
