### ISSUE TITLE
GCP start free trial is not working with 404 error

### ISSUE THREAD

**Issue by jeesim2** [GoogleCloudPlatform/community#1287]
GCP start free trial is not working with 404 error.

https://console.cloud.google.com/freetrial/signup/tos?_ga=2.235294468.406822456.1591343101-1678820368.1591343101&_gac=1.249104245.1591359526.CjwKCAjw2uf2BRBpEiwA31VZj4r0zntbxObJ-50LKnLDpM0detlW7CDmpJw5XsxNfY2aLvwzRFqBYBoC2sEQAvD_BwE

![5A06C8A6-E79F-4AF9-814C-A3DAA01A72B4](https://user-images.githubusercontent.com/1100831/83930915-ed0a4500-a7d4-11ea-8412-13d1b9e94ab1.png)
![6BB051A9-DBAC-48AB-9CC2-F7E4057B73A7](https://user-images.githubusercontent.com/1100831/83930926-f3002600-a7d4-11ea-8c1b-0d46809a40fe.png)

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
