### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-strongswan/index.md

### ISSUE THREAD

**Issue by jnewman-altair** [GoogleCloudPlatform/community#1293]
The page states, "Your on-premises firewall allows UDP port 500, UDP port 4500, and ESP packets." but this does not specify incoming or outgoing packets. Please clarify so that people know whether this tutorial can be used with NAT, etc.

**Comment by ToddKopriva** [comment]
Thanks for the suggestion.

**Comment by ToddKopriva** [comment]
@Civil , could you have a look at this question about a document that you contributed?
