### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by efmtummy** [GoogleCloudPlatform/community#1307]
Issue Description
The initial install of helm and tiller is insecure, when following these instructions, because you run
  helm init
instead of 
  helm init --tiller-tls-verify
It is critical to do the --tiller-tls-verify on the first time running helm init, because otherwise the key files are not correctly copied into the environment.
See: https://github.com/Praqma/helmsman/issues/139

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll have a look.

**Comment by ameer00** [comment]
Updated for Helm v3 which fixes this issue (after #1551 is merged)
