### ISSUE TITLE
Issue with tutorials/building-flask-api-with-cloud-firestore-and-deploying-to-cloud-run.md

### ISSUE THREAD

**Issue by anisaraf** [GoogleCloudPlatform/community#1318]
Issue Description: Link to github code no longer exists:

https://github.com/Timtech4u/flask-firestore

**Comment by ToddKopriva** [comment]
@anisaraf , thanks for the report. I have removed the bad link. The tutorial still seems to be valuable without a link to the source repository. Let me know if you disagree.
