### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by gianluca-sabena** [GoogleCloudPlatform/community#1323]
This page suggest to create a service account to use terraform, but doesn't state anything about the role which must be assigned to the sa. I suggest to add a specific documentation on the role.

**Comment by ToddKopriva** [comment]
@chrisst , could you have a look at this request?

**Comment by chrisst** [comment]
@gianluca-sabena thanks for the feedback. I've added an explicit callout for service account roles in https://github.com/GoogleCloudPlatform/community/pull/1461

**Comment by ToddKopriva** [comment]
Thanks for the fix, @chrisst .
