### ISSUE TITLE
[Documentation] Issues with the Slack link

### ISSUE THREAD

**Issue by Rishit-dagli** [GoogleCloudPlatform/community#1325]
The GCP slack badge in the documentation, [![Slack][slack_badge]][slack_link] is a link to https://gcp-slack.appspot.com/ . However, this seems to be an invalid URL. I have also added a screenshot of the same.

> 404. That’s an error.
> The requested URL was not found on this server. That’s all we know.

![gcp_slack_error](https://user-images.githubusercontent.com/39672672/86524993-de2fb480-be9e-11ea-9af4-020d35a65dba.JPG)

[slack_badge]: https://img.shields.io/badge/slack-gcp-E01563.svg?style=flat
[slack_link]: https://gcp-slack.appspot.com/

**Comment by ToddKopriva** [comment]
@Rishit-dagli , where exactly did you find this link?

Was it the link at the bottom of this page?
https://cloud.google.com/community/tutorials/appengine-yarn

**Comment by Rishit-dagli** [comment]
@ToddKopriva The link was in this repo's README file in the heading section, I have added a screenshot for better clarity.

![slack_gcp_position](https://user-images.githubusercontent.com/39672672/86525791-41bedf80-bea9-11ea-829a-3f761479813c.JPG)

**Comment by ToddKopriva** [comment]
Got it. Thanks again.

**Comment by ToddKopriva** [comment]
I removed the badge from that page and added a link to various discussion resources:
https://github.com/GoogleCloudPlatform/community/pull/1327

That new link goes to a bunch of resources, including a link to the Slack channel that is automatically kept up to date.
