### ISSUE TITLE
connect to mongo with proper whitelist.

### ISSUE THREAD

**Issue by Solobearus** [GoogleCloudPlatform/community#1326]
I just finished your tutorial about connecting the GCP app engine to Mongo atlas. 
The problem is that for the sake of simplicity you chose to whitelist all addresses. but what if I don't want to allow everyone to try and connect to my database. how can I connect the two without whitelisting all addresses?

**Comment by ToddKopriva** [comment]
I'm closing this issue because we're tracking this matter here:
https://github.com/GoogleCloudPlatform/community/issues/1352

**Comment by ideafest** [comment]
A solution to this is by routing traffic of our Appengine through a VPC connector, Atlas supports the peering of GCP VPC with theirs, therefore only allowing traffic from within your VPC to access the database.

I am giving more details on below:

- VPC Peering Overview
   https://cloud.google.com/vpc/docs/vpc-peering
- How to use app engine on shared VPC:
   https://cloud.google.com/appengine/docs/flexible/python/using-shared-vpc
- How to setup peering connection between Atlas and GCP?
   https://docs.atlas.mongodb.com/security-vpc-peering/

Please let me if you further questions.

Happy coding!
