### ISSUE TITLE
Unable to connect to server:  timeout expired

### ISSUE THREAD

**Issue by Sarthak77tiwari** [GoogleCloudPlatform/community#1328]
I am getting an error when I use to connect my pgAdmin with the google cloud VM instance 

> I use my public IP address in the hostname of pgAdmin in the windows 10

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
