### ISSUE TITLE
 Tutorial Request : Simple Php Connectivity with Sql Cloud databse on Google App Engine

### ISSUE THREAD

**Issue by arpitdeveloper** [GoogleCloudPlatform/community#134]
I want mysql connection with Google app engine project. but i didn't do it. i have an error in my code 
mysqli::__construct(): (HY000/2002): No such file or directory in /app/index.php on line 9
No such file or directory

So Please provide a tutorial with show data in php file using sql cloud database and php without using any php framework.
Thanks

**Comment by jmdobry** [comment]
Have you taken a look at [Using Cloud SQL with PHP](https://cloud.google.com/php/getting-started/using-cloud-sql)?

**Comment by arpitdeveloper** [comment]
Yes, i look at this link but not remove my error.

**Comment by jmdobry** [comment]
cc @bshaffer

**Comment by bshaffer** [comment]
There is also [this example](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/standard/cloudsql) for App Engine Standard, and [this example](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/flexible/cloudsql-mysql) for App Engine Flexible.
