### ISSUE TITLE
Download data from Google cloud "IOT Core" Pub sub

### ISSUE THREAD

**Issue by keirti** [GoogleCloudPlatform/community#1342]
Hi,

I am beginer to use google cloud platform.I have created a 'topic' and subscribed to topic,creatd registry,published data (using C langauge) to the 'Topic'. In cloud shell I can only view the the data by entering a command 

gcloud pubsub subscriptions pull  100 --auto-ack subscription name of topic

to be able to download the data,I understand it needs to be stored somewehere,Can anybody share some tutorial on how to store the data on IOT Core and download it.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
