### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by barabenka** [GoogleCloudPlatform/community#1346]
The step where I expose hello-app does not work:
username@cloudshell:~ (lateral-boulder-282521)$ kubectl run hello-app --image=gcr.io/google-samples/hello-app:1.0 --port=8080
pod/hello-app created
username@cloudshell:~ (lateral-boulder-282521)$ kubectl expose deployment hello-app

**Comment by ameer00** [comment]
Updated tutorial for Helm v3. Tested end to end. This should work now (once #1551 is merged).
