### ISSUE TITLE
Load testing IoT with Locust tutorial uses the default OrderedReady pod management

### ISSUE THREAD

**Issue by egoshard** [GoogleCloudPlatform/community#1347]
The "_Load-testing an IoT application using GCP and Locust_" tutorial uses a Kubernetes cluster to provide compute for Locust workers that run simulated users. It uses a StatefulSet to provide each worker with an ordinal number to identify itself to the Locust master. The default pod management for StatefulSet is _OrderedReady_ which deploys pods sequentially from 0 up through N-1 with each pod requiring its predecessors to be in the ready state prior to being deployed. At small scale this  management strategy is efficient enough but as scale increases the amount of time required to ready each pod before deploying the next become untenable. On average pods deploy and achieve the ready state in approximately 30 seconds with each pod capable of simulating 300 users. This means that a load test with 100,000 users requires 400 pods and a roughly 3.33 hour startup time.

Switching to _Parallel_ pod management allows the StatefulSet controller to deploy all Pods in parallel, and to not wait for pods to become ready before deploying more.

[Load-testing an IoT application using GCP and Locust](https://cloud.google.com/community/tutorials/load-testing-iot-using-gcp-and-locust)
[Kubernetes StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset)

**Comment by ToddKopriva** [comment]
@egoshard , thanks for the suggestion. That makes sense. 

@csgcp , could you have a look at this suggestion regarding a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
@egoshard , if you want to submit a pull request to implement this change, feel free to do so, and I'll review it.

**Comment by ToddKopriva** [comment]
fixed by #1348
