### ISSUE TITLE
Connecting google cloud MySQL using PHP (Local)

### ISSUE THREAD

**Issue by azrulsalki** [GoogleCloudPlatform/community#1349]
Hi,
How do i connect a PHP program to send data to the google cloud MySQL. I was able to ping my database using command prompt but when I tried to send data using my PHP, there are no error in the syntax, unfortunately the data was not inserted into my database. Here I attached some picture:

Here is the image of me pinging to the database.
![Untitled](https://user-images.githubusercontent.com/61158707/87405697-6118e380-c5f2-11ea-9290-501f72eed6ed.png)

This is my PHP code connecting to the database.

![Untitled1](https://user-images.githubusercontent.com/61158707/87405705-637b3d80-c5f2-11ea-9a64-8b2e8c85ab10.png)

Unfortunately, my database did not receive any input from my PHP.

Do i need to do firewall setting to allow my pc ip?

**Comment by azrulsalki** [comment]
I have checked for all possibility of syntax error, but i managed to send data to a localhost DB but cannot send it to the cloud.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
