### ISSUE TITLE
Process to rewrite tutorials

### ISSUE THREAD

**Issue by Annie29** [GoogleCloudPlatform/community#1354]
Is there a process for rewriting an existing community tutorial?  In particular, the tutorial at https://cloud.google.com/community/tutorials/data-science-preprocessing is written to use the command line interface to BQ.  

Would it be acceptable to rewrite this for the console interface?  (Obviously this is far more than a patch, because both versions of the tutorial should continue to exist.)

**Comment by ToddKopriva** [comment]
Depending on how much of the material would change, I think that it could make sense to have one document that has both options. If the introduction, definition of the pipeline, and cleanup steps are all the same, but running the pipeline is different, then you could just have separate sections for the CLI versus the console for that part.

Thoughts?

**Comment by Annie29** [comment]
Let me look in more detail.  I'm thinking they're probably too different: for example, the CLI version has setting up the Cloud SDK as a prerequisite, which isn't necessary for the Console.  (Now, a patch to the CLI version to have it run on the Cloud Shell might make sense.)

I'm looking at some options for a meeting tomorrow and will look into this further after that.

**Comment by ToddKopriva** [comment]
@Annie29 , is this issue still active?

**Comment by ToddKopriva** [comment]
I'm closing this issue. Feel free to reopen it or contact me through internal channels if you still have questions.
