### ISSUE TITLE
Issue with tutorials/get-started-bitnami-django.md

### ISSUE THREAD

**Issue by onavsaber** [GoogleCloudPlatform/community#1360]
I have launched a "Django Certified by Bitnami" instance and was following the mentioned tutorial. But Step 3 on this tutorial fails with:
-bash: cd: /opt/bitnami/apps/django/django_projects: No such file or directory

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll take a look.

**Comment by ToddKopriva** [comment]
@vikram-bitnami , could you take a look at this issue regarding a tutorial that you contributed?
https://cloud.google.com/community/tutorials/get-started-bitnami-django

**Comment by vikram-bitnami** [comment]
I'll have a look in the next few days

**Comment by ToddKopriva** [comment]
Thanks, @vikram-bitnami .
