### ISSUE TITLE
Issue with tutorials/sigfox-gw/index.md

### ISSUE THREAD

**Issue by rbreuss** [GoogleCloudPlatform/community#1361]
I followed step by step you sigfox-gw tutorial till point : Creating Sigfox backend callbacks
I have individualy created callback in my Sigfox backend for this device. 
- When I run python3 sigfox-api.py --callbacks list, it shows me correctly 1 existing callback. 
- When I run python3 sigfox-api.py --callbacks delete-all, it correctly delete that my individual callback
It seems to me, that authentication works fine. 
- But when I run python3 sigfox-api.py --callbacks create, it finishes with following error:

```
Traceback (most recent call last):
  File "sigfox-api.py", line 251, in <module>
    main(sys.argv)
  File "sigfox-api.py", line 243, in main
    cf_service, cf_auth, callbacks_config_file)
  File "sigfox-api.py", line 162, in create_callbacks
    callbacks.append(dict_to_callback(d, cf_data, cf_service, name, cf_auth))
  File "sigfox-api.py", line 216, in dict_to_callback
    content_type=d['contentType']
  File "/root/community/tutorials/sigfox-gw/swagger_client/models/create_url_callback.py", line 75, in __init__
    CreateCallback.__init__(self, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'send_duplicate'
```

I have no idea, where could be problem. Could you help me to solve this issue:

Radovan

**Comment by ToddKopriva** [comment]
@lepistom , would you take a look at this report about a tutorial that you submitted?

https://cloud.google.com/community/tutorials/sigfox-gw

**Comment by dmasb** [comment]
I am having the same issue.

**Comment by dmasb** [comment]
I am having the same issue as @rbreuss

**Comment by summer2020-cmd** [comment]
I am having the same issue as @rbreuss

**Comment by ferrarimarco** [comment]
Hi all! We're looking into this to automate some checks. Stay tuned!
