### ISSUE TITLE
The peer gateway notifies: Proposal mismatch in IKE SA (phase 1) , Please look at peer logs

### ISSUE THREAD

**Issue by ausias-armesto** [GoogleCloudPlatform/community#1367]
I have followed the instruction defined at https://cloud.google.com/community/tutorials/using-cloud-vpn-with-strongswan, but I think that may be there is something misssing because when I try to connect to Google Cloud VPN using Strongswan from a fresh new Debian 9.13 machine I get the following error in Google Cloud:
The peer gateway notifies: Proposal mismatch in IKE SA (phase 1) , Please look at peer logs

Looking at the Google Log I watch the following:
```
parsed IKE_SA_INIT response 0 [ N(NO_PROP) ]
received NO_PROPOSAL_CHOSEN notify error
The peer gateway notifies: Proposal mismatch in IKE SA (phase 1) , Please look at peer logs. "
````

An the logs at the Peer are those:
```
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[NET] received packet: from 34.105.183.25[500] to 10.10.10.225[500] (892 bytes)
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) ]
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[CFG] looking for an ike config for 10.10.10.225...34.105.183.25
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[IKE] no IKE config found for 10.10.10.225...34.105.183.25, sending NO_PROPOSAL_CHOSEN
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[ENC] generating IKE_SA_INIT response 0 [ N(NO_PROP) ]
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[NET] sending packet: from 10.10.10.225[500] to 34.105.183.25[500] (36 bytes)
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 15[IKE] IKE_SA (unnamed)[136] state change: CREATED => DESTROYING
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 04[NET] sending packet: from 10.10.10.225[500] to 34.105.183.25[500]
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 03[NET] received packet: from 34.105.183.25[500] to 10.10.10.225[500]
Jul 23 12:33:47 ip-10-10-10-225 ipsec[1233]: 03[NET] waiting for data on sockets
````

Any ideas?

**Comment by ToddKopriva** [comment]
@Civil , can you have a look at this question about a document that you contributed?

**Comment by Civil** [comment]
Well, unless there were changes on Cloud VPN side in GCP, if you follow the doc as written - it should just work.

However to troubleshoot such issues you need to have access to logs on both Cloud VPN side and on a strongswan side. Usually there is a clue there. Sometimes it might help to enable debug logs on strongswan side (but be careful, on some levels it will also log PSK you are using).

Btw, what ciphers you've configured on Strongswan side?

**Comment by ausias-armesto** [comment]
Thanks @Civil , I've seen both logs and I cann't see any clue, even increasing the log level to some modules like enc, ike,net . 
On Strongswan I have set the ciphers specified on this page, but I have also tried the ones proposed here: https://hub.docker.com/r/deltaprojects/strongswan/ but with no luck.
I will create a support ticket to see if they can help me more.

 I'll write back here if I find the solution.

**Comment by cgageat** [comment]
Hello,

I also had the same error today. 

When I updated the /var/lib/strongswan/ipsec.conf.inc file, I copied the example line and let the # at the beginning like that:
#include /etc/ipsec.d/gcp.conf

The conf was not loaded. That's why I got those error. When removed the # strongswan was able to create the tunnel

**Comment by ToddKopriva** [comment]
Thanks, @cgageat .

**Comment by ToddKopriva** [comment]
It seems that the answer from @cgageat has resolved this issue.
