### ISSUE TITLE
Tags don't work how I'd expect them to

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/community#137]
On the tutorials pages, such as [this one](https://cloud.google.com/community/tutorials/ghost-on-app-engine-part-1-deploying), there are tag links at the bottom. Actually that's not correct. There are multiple tags listed but there is a single link to https://cloud.google.com/community/tutorials?q=App%20Engine,%20Ghost,%20Node.js

I would expect there to be multiple links, one for each tag.

Also if they are going to be combined, it seems they should be ANDed not ORed together. I don't think all the dozens of tutorials in that search link are for that combo of Ghost on App Engine.

**Comment by jmdobry** [comment]
This has been fixed, tags are now individual links.
