### ISSUE TITLE
Issue with tutorials/dlp-to-datacatalog-tags/

### ISSUE THREAD

**Issue by akspow** [GoogleCloudPlatform/community#1374]
Specific table scan doesn't seem to work even if I mention Bigquery tableName, I am getting the entire dataset scanned. Could you kindly have a look at this @mesmacosta ?

**Comment by mesmacosta** [comment]
Hi @akspow 

There is an issue when using together the filters `tableName` and `dbName`, the `dbName` overrides the other filter.

Will send a PR to fix this.

**Comment by ToddKopriva** [comment]
Thanks for the fix. I'll go and revie the PR with the fix now.
