### ISSUE TITLE
Issue with tutorials/managing-gcp-projects-with-terraform/index.md

### ISSUE THREAD

**Issue by priyankak1212** [GoogleCloudPlatform/community#1388]
Hi,
I need to create new GCP project using organisation id by terraform script. For that which json key need to be used??? Is that first we have to create service account for new project?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get questions answered quickly. 

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

I'll leave this issue open and see if there is some way that we could improve the tutorial that you mentioned in the area that you asked about.
