### ISSUE TITLE
corporate CLA - not sure where we're stuck

### ISSUE THREAD

**Issue by Adrian-in-Aus** [GoogleCloudPlatform/community#1390]
@ToddKopriva :: Hi Todd,  any clues on who's is waiting for what on the corporate CLA behind: https://github.com/GoogleCloudPlatform/community/pull/1383 

I completed the corp-CLA earlier in the week,   if I try and fill it all in again I get the "already exists" error.
I did have the issue where my primary GH email was not pointing to the correct work email (it was a secondary),  since rectified. 
In theory I fullfill the role-requirements listed in the instructions (although the first link 404's for me,  so not sure on that one)

All the best,  Adrian

**Comment by ToddKopriva** [comment]
I'll see what I can find out.

**Comment by Adrian-in-Aus** [comment]
@ToddKopriva - any joy identifying where the corpCLA has fallen?

**Comment by ToddKopriva** [comment]
Not yet. I'll get back to you later today.

**Comment by ToddKopriva** [comment]
I think that you should be in good shape for your next PR. I've merged your most recent PR.
