### ISSUE TITLE
Issue with tutorials/mongodb-atlas-appengineflex-nodejs-app/index.md

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/community#1392]
**Issue Description**

Since there are many new developers reading [this article](https://cloud.google.com/community/tutorials/mongodb-atlas-appengineflex-nodejs-app) - it might be misguiding and resulting to their credentials being hard-coded on the server and potentially GitHub.

The database is completely naked with only the URI string protecting it and this line in the example: 
`let uri = PASTE YOUR MONGODB ATLAS CONNECTION STRING HERE ;` 
states that they should paste their mongodb URI straight into the server without suggesting that they should use their CI's environmental variables or at least `.env`.

Of course it's not client-side code, although in order to follow the practice of never having hard-coded credentials and most importantly out of GitHub - i find it an improvement for the docs.

Let me know your thoughts :raised_hands:

**Comment by ToddKopriva** [comment]
Thanks for the feedback.

@ideafest , what do you think?
