### ISSUE TITLE
Issue with tutorials/iot-device-to-device Authentication

### ISSUE THREAD

**Issue by laiunce** [GoogleCloudPlatform/community#1399]
Hi! im following the tutorial but im getting this error in the Cloud Function

`Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information. at GoogleAuth.getApplicationDefaultAsync (/srv/node_modules/google-auth-library/build/src/auth/googleauth.js:155:19) at <anonymous> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
`
Thanks!

**Comment by ToddKopriva** [comment]
Thanks for the report. We can look into this and see if there's a problem with the tutorial. 

In the meantime, for faster help for you, I recommend bringing your issue to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
