### ISSUE TITLE
Can not access to GCP VM Instance via external IP although apache2 started

### ISSUE THREAD

**Issue by phileba** [GoogleCloudPlatform/community#1402]
I've created a test VM instance on GCP:

install apache2 and the service started success: 
![image](https://user-images.githubusercontent.com/44990652/91119461-6bcc9b00-e6bd-11ea-941a-afb24fc32452.png)

the firewall setup as default: 
![image](https://user-images.githubusercontent.com/44990652/91119581-b9490800-e6bd-11ea-977d-c6f6671db7fe.png)

the apache ports config: 
![image](https://user-images.githubusercontent.com/44990652/91119508-8c94f080-e6bd-11ea-9e69-92ff1faf2adc.png)

external IP: 
![image](https://user-images.githubusercontent.com/44990652/91119521-96b6ef00-e6bd-11ea-8635-f30d2f87e788.png)

it seems ok but I can not access via external ip as the document said https://cloud.google.com/community/tutorials/setting-up-lamp

Please give me some suggestions, thanks.

=================================

curl --head http://35.240.177.89/ curl: (7) Failed to connect to 35.240.177.89 port 80: Operation timed out

curl --head https://35.240.177.89/ curl: (7) Failed to connect to 35.240.177.89 port 443: Operation timed out

netstat -lntup: 
![image](https://user-images.githubusercontent.com/44990652/91119539-a0d8ed80-e6bd-11ea-99d8-6d559f33e505.png)

**Comment by ToddKopriva** [comment]
We can look at the tutorial that you linked to and see whether we need to make any updates there.

In the meantime, the Issues section of this GitHub repository is not the best place for troubleshooting help. 

For more timely help, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by xiangshen-dk** [comment]
Looks like the firewall setup screenshot is from the **VPC network -> Firewall** page. Please check the instance firewall configuration. For example, make sure **Allow HTTP traffic** is checked for your instance under **Firewalls** at the **VM instance details** page.
