### ISSUE TITLE
Issue with tutorials/how-to-roll-your-app-engine-managed-vms-app-back-to-a-previous-version-part-1.md

### ISSUE THREAD

**Issue by ramesh-2001-2100** [GoogleCloudPlatform/community#1403]
Hello the instructions to construct package.json are inadequate. Specifically, apart from the name property, there should be this additional line in package.json, else it throws an error. 

 ,"scripts": {
        "start": "node .",
        "test": "echo \"Error: no test specified\" && exit 1"
    }

Please update the tutorial accordingly.

**Comment by ToddKopriva** [comment]
Thanks for the report. If you know what change needs to be made, you are welcome to create a pull request to make the fix, and we'll review and merge it.

**Comment by ramesh-2001-2100** [comment]
Hi Todd, thank you for your response. I have tried it out fully, now I know
what changes are to be made to the documentation (tutorial itself) in a few
places. Is it something I can change myself or can I just provide you the
list of changes to make?

Thanks

Ramesh.

**Comment by ToddKopriva** [comment]
It would be great if you made the changes yourself in a pull request, and then I can review them.

**Comment by ramesh-2001-2100** [comment]
Hi Todd,

 I've made changes and created a pull request for your review.

Thanks

Ramesh.

**Comment by ToddKopriva** [comment]
Thanks. I'll check it out.
