### ISSUE TITLE
deploying a node.js app with mongo as nosql db

### ISSUE THREAD

**Issue by Parrinque** [GoogleCloudPlatform/community#1404]
Hi Team,

Are there any set of best practices for this? Please recommend.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
