### ISSUE TITLE
Issue with tutorials/deploy-react-nginx-cloud-run/index.md

### ISSUE THREAD

**Issue by 0xblaze** [GoogleCloudPlatform/community#1406]
Issue Description`
Step 5/13 : RUN yarn build
 ---> Running in 281ff03d2d95
yarn run v1.21.1
error Couldn't find a package.json file in "/app"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1`

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll check it out.

**Comment by ToddKopriva** [comment]
@FelipeLujan , could you take a look at this report about a tutorial that you submitted?

**Comment by ToddKopriva** [comment]
closing as fixed with PR #1865
