### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-flexible/index.md

### ISSUE THREAD

**Issue by muhfaisal90** [GoogleCloudPlatform/community#1408]
I am trying to deploy laravel 7 app and having following error when running "gcloud app deploy" 

Step #1: 
Step #1: In Connection.php line 671:
Step #1:                                                                                
Step #1:   SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
Step #1:   ation_schema.tables where table_schema = cpapis_db and table_name = setting  
Step #1:   s and table_type = 'BASE TABLE')                                             
Step #1:                                                                                
Step #1: 
Step #1: In PDOConnection.php line 31:
Step #1:                                                     
Step #1:   SQLSTATE[HY000] [2002] No such file or directory  
Step #1:                                                     
Step #1: 
Step #1: In PDOConnection.php line 27:
Step #1:                                                     
Step #1:   SQLSTATE[HY000] [2002] No such file or directory  
Step #1:                                                     
Step #1: 
Step #1: Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Step #1: error building image: error building stage: waiting for process to exit: exit status 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/kaniko-project/executor@sha256:f87c11770a4d3ed33436508d206c584812cd656e6ed08eda1cff5c1ee44f5870" failed: step exited with non-zero status: 1

**Comment by ToddKopriva** [comment]
We can look at the tutorial that you referred to and see whether we need to make any updates there.

In the meantime, the Issues section of this GitHub repository is not the best place for troubleshooting help.

For more timely help, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
