### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by Salmen33** [GoogleCloudPlatform/community#1413]
PHP message: PHP Fatal error: Uncaught Error: Class 'Google\Cloud\ErrorReporting\Bootstrap' not found in /workspace/app/Exceptions/Handler.php:42 Stack trace: #0

idk why but for some reason function report cannot get the bootstrap class

**Comment by ToddKopriva** [comment]
Thanks for the report.

**Comment by ibnujakaria** [comment]
Hi I got the same error too after following steps on the tutorial.

Here is the error message from google cloud logging:

```
PHP message: PHP Fatal error:  Uncaught Error: Class 'Google\Cloud\ErrorReporting\Bootstrap' not found in /workspace/app/Exceptions/Handler.php:42
```

**Comment by ToddKopriva** [comment]
@bshaffer , can you have a look at this issue about a tutorial that you submitted?

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
