### ISSUE TITLE
Issue with tutorials/docker-gcplogs-driver/index.md

### ISSUE THREAD

**Issue by athreyapatel** [GoogleCloudPlatform/community#1418]
Issue Description:
Please add how to change the ADC(Application Default Credentials). 
If the default account doesn't provide access i.e. if it doesn't have log.writer access. There is occurance of PermissionDenied error in rpc call.

**Comment by ToddKopriva** [comment]
@tswast , can you have a look at this request about a tutorial that you contributed?

**Comment by tswast** [comment]
Are you asking how to set up the correct scopes and IAM permissions on the service account used for the GCE instance? Or are you asking how to set up alternative authentication options?

**Comment by athreyapatel** [comment]
I am asking about the use of different service account, which is not a default account when creating the instance. 
Consider I have a service account with log.writer role, and I want it be used by gcplogs driver to send logs. 
I have exported `GOOGLE_APPLICATION_CREDENTIALS="/path/to/key.json"` and I have also tried setting the environment variables for docker daemon like this https://stackoverflow.com/questions/49983216/the-google-cloud-logging-driver-for-docker?noredirect=1&lq=1 .

But the logs are not injested to Cloud Log Viewer

**Comment by tswast** [comment]
> not a default account when creating the instance

I think this is outside of the scope of the article. It's a best practice to avoid the use of service account key files when running on GCE and to instead grant the logs writer role to the service account associated with the instance.

From https://stackoverflow.com/questions/49983216/the-google-cloud-logging-driver-for-docker?noredirect=1&lq=1 . it does appear that `GOOGLE_APPLICATION_CREDENTIALS` is supported by the gcplogs driver, but you need to make sure that environment variable is set in whatever shell / process is launching the docker daemon.
