### ISSUE TITLE
Error during tokenization: 5 NOT_FOUND:

### ISSUE THREAD

**Issue by GraHms** [GoogleCloudPlatform/community#1420]
I'm getting this error 

Error during tokenization: 5 NOT_FOUND: The DLP Service Account `service-************@dlp-api.iam.gserviceaccount.com` not found. This service account is automatically created when the DLP API is enabled for a project in the Cloud Console. Assure that the API is enabled in project `10************` and the service account was not deleted. If it was deleted, disable and then re-enable the Cloud DLP API to restore it..

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get troubleshooting help for issues like this. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
