### ISSUE TITLE
Issue with tutorials/wix-media.md

### ISSUE THREAD

**Issue by brucemcpherson** [GoogleCloudPlatform/community#1423]
Issue Description
Wix media platform seems to no longer exist as a service.

**Comment by ToddKopriva** [comment]
Thanks, Bruce. I'll look into this.

**Comment by ToddKopriva** [comment]
Thanks again, @brucemcpherson .

I checked, and Wix Media Platform is no longer available as a service. I archived the three tutorials that describe how to use it.
