### ISSUE TITLE
Issue with tutorials/drupal-on-compute-engine.md

### ISSUE THREAD

**Issue by camerongreen** [GoogleCloudPlatform/community#1432]
This is quite different to https://sendgrid.com/docs/for-developers/sending-email/drupal/ which recommends the sendgrid module.

For example in the sendgrid instructions it says to use your API key as a password.

Anyway I haven't got it working yet so not sure if one or both is right, but just interested in the discrepancy.

I also feel there should be a little more instruction of what to do on the sendgrid side.  What sort of account you need etc.

Thanks :)

**Comment by camerongreen** [comment]
Actually it seems all of them led me astray.

You need to sign up, and:

-  go into the Email API section
-  select SMTP relay
-  Name key and generate

Then after enabling the SMTP module (I also installed the mailsystem module and told it to use SMTP for sending):
- SMTP Server: smtp.sendgrid.net
- SMTP port: 2525
- Use encrypted protocol: Use TLS
- Enable TLS encryption automatically: On
- Username: apikey (this is not my username, it is the same for all users)
- Password: API token generated above
- E-mail from address: I used the email from sendgrid as I've had issues in the past when I used a different one to the email service account.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll have a look.

**Comment by ToddKopriva** [comment]
addressed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1520
