### ISSUE TITLE
Issue with tutorials/run-sailsjs-on-google-app-engine.md

### ISSUE THREAD

**Issue by kingflamez** [GoogleCloudPlatform/community#1445]
How do you connect to Google CLOUD SQL using Sails

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. 

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
