### ISSUE TITLE
max_chars doesn't work in given example

### ISSUE THREAD

**Issue by whicks1** [GoogleCloudPlatform/community#1463]
https://github.com/GoogleCloudPlatform/community/blob/fc28d27927d1e548ce200b31d3a0e59105cb7703/tutorials/speech2srt/speech2srt.py#L72-L76

in the tutorial, charcount won't in most cases, exceed the default character count, because it's looking for long individual words, not long line lengths. I think flipping the two variables and checking the length of content is the intended behavior.

```
        content += " " + w.word.strip()
        charcount += len(content)

        if ("." in w.word or "!" in w.word or "?" in w.word or
                charcount > args.max_chars or
```

**Comment by ToddKopriva** [comment]
@lepistom , can you have a look at this suggestion regarding your speech2srt tutorial code?

**Comment by ToddKopriva** [comment]
@whicks1 , thanks for the report.

**Comment by whicks1** [comment]
No problem, good tutorial overall, got me started down a good path, so hope I'm right. Also FWIW, (and I know it's a tutorial, but for posterity sake), the logic of breaking lines on periods and commas is going to have all sorts of odd outlier problems for Mr. Mrs, Dr. \d,\d{3}, etc. Needs some regex, but I'm sure that's overkill for the example.  Cheers.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
