### ISSUE TITLE
Issue with tutorials/cloud-functions-twilio-sms/index.md

### ISSUE THREAD

**Issue by cgarrovillo** [GoogleCloudPlatform/community#1465]
# Twilio has an overall new API.

## Changing Auth token insertion to use curried functions on module import
`const twilio = require('twilio');`
to
```
const twilio = require('twilio');  
const client = new twilio(accountSid, authToken);
```

## Stop using an Express specific function
```
isValid = twilio.validateExpressRequest(req, config.TWILIO_AUTH_TOKEN, {
      url: `https://${region}-${projectId}.cloudfunctions.net/reply`
    });
```
to
```
isValid = twilio.validateRequestWithBody(config.TWILIO_AUTH_TOKEN, twilioSignature, 
`https://${region}-${projectId}.cloudfunctions.net/reply`, req.body);
```

Also see https://github.com/twilio/twilio-node/issues/294

**Comment by ToddKopriva** [comment]
Thanks, @cgarrovillo .

If you know what fix needs to be made, we'd welcome you creating a pull request to make the fix, and then we can get it reviewed and merged.
