### ISSUE TITLE
Issue with tutorials/pubsub-spring-dedup-messages/index.md

### ISSUE THREAD

**Issue by dmkskd** [GoogleCloudPlatform/community#1471]
Issue Description: typo in cloning instructions for _pubsub-spring-dedup-messages.git_ repo url and after correcting it, the repo is not found

The following link
`git clone https://github.com.GoogleCloudPlatform/pubsub-spring-dedup-messages.git`

has a '**.**' instead of a '**/**' after github.com

It should be
`git clone https://github.com/GoogleCloudPlatform/pubsub-spring-dedup-messages.git`

Nevertheless, the repo seems not to exist (anymore) or to be private

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into it.

**Comment by ToddKopriva** [comment]
I'll fix the typo in the command.

Of course, that still leaves the larger problem of the repository not being available.

@anguillanneuf , can you look into what happened with the GitHub repository that this document refers to?
https://github.com/GoogleCloudPlatform/pubsub-spring-dedup-messages
