### ISSUE TITLE
Issue with tutorials/pci-tokenizer/index.md

### ISSUE THREAD

**Issue by will-hill** [GoogleCloudPlatform/community#1482]
Issue Description - There is a table in this article that says KMS is not Deterministic.  After reading about GCP KMS, it seems KMS is Deterministic and actually has multiple Deterministic options.  Am I missing something?  Thanks for your help ahead of time

**Comment by ToddKopriva** [comment]
@ianmaddox , can you answer this question?

**Comment by ToddKopriva** [comment]
@will-hill , this page answers your question:
https://cloud.google.com/kms/docs/resource-hierarchy#algorithm

"Regardless of the algorithm, Cloud KMS uses probabilistic encryption, so that the same plaintext encrypted with the same key version twice does not encrypt to the same ciphertext."
