### ISSUE TITLE
Issue with tutorial

### ISSUE THREAD

**Issue by vinodgupta-tivo** [GoogleCloudPlatform/community#1484]
Hi Google,

Tutorial Page https://cloud.google.com/community/tutorials/horizontally-scale-mysql-database-backend-with-google-cloud-sql-and-proxysql is having below given section which is having wrong comments. I am marking it in Bold Text and correct ones I am marking as Italic Text.

------
Declare rules with the following SQL queries:

        INSERT INTO mysql_rules (rule_id, active, match_digest, destination_hostgroup, apply) VALUES (1,1,'^SELECT.*FOR UPDATE',0,1), (2,1,'^SELECT',1,1);
        LOAD MYSQL RULES TO RUNTIME;
        SAVE MYSQL RULES TO DISK;

The queries add two rules:

- **Distribute all the `SELECT … FOR UPDATE` queries to database servers in
    host group `1`**
- **Distribute all the `SELECT` queries to database servers in host group `0`**

Queries that do not match any existing rules go to database servers in host
group `0` (default).

Correct statements should be like below:

- _Distribute all the `SELECT … FOR UPDATE` queries to database servers in
    host group `0`_
- _Distribute all the `SELECT` queries to database servers in host group `1`_

Thanks & regards,
Vinod

**Comment by ToddKopriva** [comment]
I fixed the error in the source document. The published page will be updated when I rebuild it later this week with a batch publishing operation.
