### ISSUE TITLE
Request for Tutorial on Hosting PERN app on Google Cloud Run

### ISSUE THREAD

**Issue by haydenlingle** [GoogleCloudPlatform/community#1485]
I'm interested in using Google Cloud Run to host a React front-end application that speaks to an express backend, then using a Google PostgreSQL database too.  I would like to containerize the react app and express API and host them on Google Cloud Run. I think GCR could become the standard for hosting React apps in an approachable, scalable way, but there's not much documentation on the subject.

Best,
Hayden

**Comment by ToddKopriva** [comment]
Thanks for the request. 

If you have an urgent need for such information, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
