### ISSUE TITLE
Issue with tutorials/compute-quickstart.md

### ISSUE THREAD

**Issue by pjThinker** [GoogleCloudPlatform/community#1507]
Issue Description
Think the todomvc mongo DB app is well deprecated, and currently am unable to make this work. 
needs a newer version of node, and seems to have quite a few broken dependencies now.

**Comment by ToddKopriva** [comment]
Thanks for the report, @pjThinker .

**Comment by ToddKopriva** [comment]
closed because we recently reworked this tutorial
