### ISSUE TITLE
Issue with tutorials/cbt-import-csv.md

### ISSUE THREAD

**Issue by pmaksymiak** [GoogleCloudPlatform/community#1509]
Hello! This is nice tutorial but I am getting errors:
[main] WARN org.apache.beam.sdk.util.RetryHttpRequestInitializer - Request failed with code 409, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes, HTTP framework says request can be retried, (caller responsible for retrying):
=projectPrivate&predefinedDefaultObjectAcl=projectPrivate&project=playground-s-11-8587668c
[main] INFO org.apache.beam.runners.dataflow.options.DataflowPipelineOptions$StagingLocationFactory - No stagingLocation provided, falling back to gcpTempLocation
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)

I tried it on my normal account and on LinuxAcademy one (I suspected that LinuxAcademy has some limitations, but no luck in case of these 2 I am still getting the same issue I mentioned before while trying to run this tutorial).

I am using CloudShell so everything should be installed but when running: mvn package exec:exec -DCsvImport -Dbigtable.projectID=xxxx-Dbigtable.instanceID=quickstart-instance -DinputFile="gs://seclog/sample.csv" -Dbigtable.table="my-table" -Dheaders="rowkey,a,b"
I am getting above errors....

**Comment by ToddKopriva** [comment]
@billyjacobson , could you take a look at this issue with a tutorial that you contributed?

**Comment by xiangshen-dk** [comment]
Looks like the sample code has already been updated. I just tried and the tutorial worked fine in Cloud Shell with the following JDK and maven versions:

```bash
$mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.11, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.104+", arch: "amd64", family: "unix"
```

I have created a PR to update the java and maven versions.

**Comment by ToddKopriva** [comment]
Thanks for the fix.
