### ISSUE TITLE
Issue with tutorials/data-science-preprocessing/index.md

### ISSUE THREAD

**Issue by iballina** [GoogleCloudPlatform/community#1516]
Issue Description:

Regarding tutorial at:
https://cloud.google.com/community/tutorials/data-science-preprocessing

There is a bug in the tutorial code. Line 138 raises:
`AttributeError: module 'apache_beam' has no attribute 'Read'`

**Comment by anantdamle** [comment]
@ToddKopriva this is thoroughly outdated. I will spend some time early 2021 to rewrite major portions of this tutorial.

**Comment by ToddKopriva** [comment]
Thanks a lot, @anantdamle .

**Comment by anantdamle** [comment]
@iballina circling back, do you expect only updating this code to work or a rewrite of the article?

**Comment by ToddKopriva** [comment]
closing issue for now, since document is being archived
