### ISSUE TITLE
Issue with tutorials/embedded-c-getting-started/index.md

### ISSUE THREAD

**Issue by PRenouf** [GoogleCloudPlatform/community#1518]
No resources for running the sample (unclear after cloning the MQTT sample)

**Comment by ToddKopriva** [comment]
@galz10 , could you take a look at this issue report about a document that you contributed?

**Comment by galz10** [comment]
Hi @PRenouf , what part of the MQTT sample are you trying to use ?

**Comment by PRenouf** [comment]
Hi @galz10, this was a long time ago now. I do not recall.

**Comment by galz10** [comment]
@ToddKopriva You can close this because no repro

**Comment by ToddKopriva** [comment]
Thanks, @galz10 .
