### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by u12206050** [GoogleCloudPlatform/community#1528]
Following these instructions on an existing Laravel project simply leads to 500 error and in the console log I only get this error: `Class view not found`

I believe it might have something to do with how Laravel is being bootstrapped, but not sure.

**Comment by ToddKopriva** [comment]
@bshaffer , could you have a look at this report of an issue with a document that you contributed?

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
