### ISSUE TITLE
Issue with tutorials/appengine-ruby-rails-activejob-sidekiq.md

### ISSUE THREAD

**Issue by MoHayat** [GoogleCloudPlatform/community#1529]
trying to use option B listed in [this article](https://cloud.google.com/community/tutorials/appengine-ruby-rails-activejob-sidekiq) to run sidekiq in a service and running into two issues:

1. deployment script states that health check line in `worker.yaml` has been deprecated.
2. service has been timing out and not deploying, this is the message I receive every time I try to deploy:
```ERROR: (gcloud.app.deploy) Error Response: [4] Timed out waiting for the flex deployment to become network provisioned.```

can't pinpoint what the issue exactly is, I've been reading that timeout issues may represent multiple reasons of failure but any help would be greatly

**Comment by ToddKopriva** [comment]
@chingor13 , could you have a look at this issue regarding a document that you contributed?

**Comment by MoHayat** [comment]
in case anyone might come across this article and issue -- I was able to figure out a solution by merging option A and B. I decided to test out option A by deploying a version where both web and worker are in a single app (using foreman) while serving none of the traffic, and I noticed that the jobs were run when endpoints were hit in a version that was serving all the traffic, but did not have the sidekiq server spun up inside of it. So the version running option A acted as a sidekiq server for the version running the pure web app.

I still needed to remove the health check line seen in `worker.yaml`, though.

would love to clarify the steps I took if needed.

**Comment by ToddKopriva** [comment]
> would love to clarify the steps I took or submit a PR fix if needed.

If you want to submit a pull request with your suggested fix, that would be great. Thanks.

**Comment by MoHayat** [comment]
of course, I'll get to work on that soon, thanks.

**Comment by ToddKopriva** [comment]
Thanks for the fix, @MoHayat .
