### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by VGerris** [GoogleCloudPlatform/community#1532]
Issue Description

The tutorial uses Helm 2 and tiller while the latest version of ingress-nginx only uses helm 3 (no tiller):
https://kubernetes.github.io/ingress-nginx/deploy/

The tutorial can be modified to include that.

**Comment by ToddKopriva** [comment]
Thanks for the report, @VGerris .

@ameer00 , could you have a look at this request for an update to a document that you contributed?

**Comment by ameer00** [comment]
#1551 fixes this
