### ISSUE TITLE
Issue with tutorials/run-symfony-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by tomsykes** [GoogleCloudPlatform/community#1545]
This guide doesn't cover building assets with webpack/encore. It seems that the build server for composer based projects doesn't have either yarn or npm installed.

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll have a look and see what improvements are needed here.

**Comment by ToddKopriva** [comment]
@bshaffer , could you give your thoughts on this request regarding a tutorial that you authored?
https://cloud.google.com/community/tutorials/run-symfony-on-appengine-standard

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
