### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by palkerecsenyi** [GoogleCloudPlatform/community#1549]
Issue Description

This tutorial is quite outdated: Helm v3 no longer supports `helm init` and no longer uses Tiller. Please update.

**Comment by ToddKopriva** [comment]
@ameer00 , could you take a look at this request regarding a tutorial that you contributed?

https://cloud.google.com/community/tutorials/nginx-ingress-gke

**Comment by ameer00** [comment]
@ToddKopriva PR submitted with fix. Please review and merge.
https://github.com/GoogleCloudPlatform/community/pull/1551

**Comment by ToddKopriva** [comment]
Thanks, @ameer00 .

**Comment by ToddKopriva** [comment]
fixed with PR #1551

**Comment by palkerecsenyi** [comment]
That was quick! Thanks so much
