### ISSUE TITLE
For community/tutorials/cloud-iot-gateways-rpi

### ISSUE THREAD

**Issue by 6010110254** [GoogleCloudPlatform/community#1557]
I tried to follow https://cloud.google.com/community/tutorials/cloud-iot-gateways-rpi
To the stage, Sending configuration updates from the IoT Core console toggles the LED device through the gateway device.
I will ask if I can write an app to configure it on android studio. Is there an example code? Thank you.

For example, I want to set ON on the app instead of on the console.

**Comment by ToddKopriva** [comment]
@hongalex , could you help with this question about a document that you contributed?

**Comment by hongalex** [comment]
Unfortunately, we don't have documentation on this specific combination. Our client libraries also currently does not support Android, so you will have to try another path.

You would likely need to set up a server that can handle requests from your android device, and have the server be authenticated to call the IoT Core API. If you need help with this, I would recommend posting on StackOverflow for help.

**Comment by ToddKopriva** [comment]
Thanks, @hongalex .

@6010110254 , as Alex suggests, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
