### ISSUE TITLE
Issue with SecretManager Python3 Tutorial

### ISSUE THREAD

**Issue by Axel-Jacobsen** [GoogleCloudPlatform/community#1561]
(tutorial is `tutorials/secrets-manager-python/index.md`)

The issue occurs when attempting to retrieve the secret key, with the code snippet from the tutorial:

```python3
secrets = secretmanager.SecretManagerServiceClient()
secrets.access_secret_version("projects/<my project id>/secrets/<key name>").payload.data.decode("utf-8")  # the path was copy-pasted from the secret details page
```

The error that I get is
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<me>/.local/share/virtualenvs/<...>/lib/python3.7/site-packages/google/cloud/secretmanager_v1/services/secret_manager_service/client.py", line 1099, in access_secret_version
    request = service.AccessSecretVersionRequest(request)
  File "/home/<me, again!>/.local/share/virtualenvs/<...>/lib/python3.7/site-packages/proto/message.py", line 448, in __init__
    % (self.__class__.__name__, mapping,)
TypeError: Invalid constructor input for AccessSecretVersionRequest: 'projects/<my project id>/secrets/<key name>'
```

It seems like AccessSecretVersionRequest is being passed my path, I am guessing in the `mapping` variable should be a `dict` instead of my path which is a `str`? I don't have time to dig into the code much. It didn't seem like an authentication issue, since it is a type error - if it actually is an authentication error, it may be wise to catch this case specifically and raise some sort of authentication error for clarity etc etc etc.

Thanks! :)

**Comment by ToddKopriva** [comment]
@TheJaySmith , could you take a look at this issue reported about a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
Thanks for the report, @Axel-Jacobsen .

**Comment by TheJaySmith** [comment]
https://github.com/GoogleCloudPlatform/community/pull/1562

**Comment by Axel-Jacobsen** [comment]
Cheers folks! :)

**Comment by simonfernandes7389** [comment]
Hi there, I am facing the same issue in Python3, even tried updating the libraries to the latest versions.
Below are the updated version of google libraries used.

```
google-api-core==1.28.0
google-api-python-client==2.7.0
google-auth==1.30.1
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-cloud-bigquery==2.18.0
google-cloud-core==1.6.0
google-cloud-datacatalog==3.2.0
google-cloud-datastore==2.1.3
google-cloud-storage==1.38.0
google-cloud-secret-manager==2.5.0
google-resumable-media==1.3.0
googleapis-common-protos==1.53.0
grpc-google-iam-v1==0.12.3
```
