### ISSUE TITLE
Issue with tutorials/dlp-hybrid-inspect/index.md

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#1586]
https://cloud.google.com/community/tutorials/dlp-hybrid-inspect

"hybrid inspection method" link is broken.

**Comment by anantdamle** [comment]
@ToddKopriva #1579 fixes this issue, you can mark this resolved once the changes go live.

**Comment by ToddKopriva** [comment]
Thanks, @anantdamle .
