### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by MontejoJorge** [GoogleCloudPlatform/community#1587]
When I run the project locally with php artisan server it works perfectly, but when I upload it to gcloud I get the error: ERR_TOO_MANY_REDIRECTS. I tried to use private browsing and delete the cookies.

https://summoner-298715.ew.r.appspot.com/

**Comment by ToddKopriva** [comment]
@bshaffer , can you have a look at this issue regarding a document that you contributed?

**Comment by edbergavera** [comment]
@MontejoJorge can you please post here your `app.yaml`  just leave out sensitive information. Also what version of Laravel you are using.

**Comment by MontejoJorge** [comment]
I tried a newly created project and could access it without any problem, I will check my code to find out what the problem was.
Thanks for your concern!

**Comment by ToddKopriva** [comment]
Thanks for letting us know, @MontejoJorge .
