### ISSUE TITLE
Tutorial Request: Custom Authentication - Verify user phone number using Twilio and Google Cloud Functions

### ISSUE THREAD

**Issue by Akharuf** [GoogleCloudPlatform/community#159]
I was wondering if you can provide a tutorial/help for custom authentication using a user's phone number? Where a code is sent via SMS to the user, and they need to enter that code in the app to complete registration and verification.

**Comment by jmdobry** [comment]
That's a great idea for a tutorial!

**Comment by VikramTiwari** [comment]
I have the final solution for this over here:
https://github.com/VikramTiwari/nodejs-examples/tree/master/sms-authentication-twilio-gcf

Will be adding supporting tutorial and codelab over the weekend.
