### ISSUE TITLE
Unclear role name on permissions

### ISSUE THREAD

**Issue by Ryuyxx** [GoogleCloudPlatform/community#1596]
#### When adding a role in the IAM & Admin [GUI screen](https://console.cloud.google.com/iam-admin/iam?), it is confusing if there is an exact same name.
In fact, I wanted to add a Cloud Run Service Agent, but the name and description are the same and I don't understand the difference.
I would like to see some kind of difference clearly stated.
<div align="center">
<img width="500" alt="CloudRun_ServiceAgent_duplicated" src="https://user-images.githubusercontent.com/69892552/105655444-650fb180-5f03-11eb-9403-b6d7933c70e5.png">
</div>

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is for reporting issues with the community tutorials in this repository.

I recommend using the **Send feedback** command in the Cloud Console to give feedback about the Cloud Console itself:
https://cloud.google.com/support/docs/issue-trackers
