### ISSUE TITLE
Google Cloud logging driver tutorial - configuration does not persist across reboots

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/community#160]
This is a bug with https://cloud.google.com/community/tutorials/docker-gcplogs-driver

The tutorial recommend Container-Optimized OS, but per https://cloud.google.com/container-optimized-os/docs/concepts/security even though /etc is writable, it does not persist across reboots.

**Comment by ToddKopriva** [comment]
Tim, if I'm reading this correctly, the following PR addressed this issue:
https://github.com/GoogleCloudPlatform/community/pull/170

I'm closing this issue based on this understanding. If I'm mistaken, feel free to re-open this issue, of course.
