### ISSUE TITLE
post-install-cmd not working in Google App Engine Flexible Environment

### ISSUE THREAD

**Issue by finallyRaunak** [GoogleCloudPlatform/community#1603]
Hi,

I am trying to update a file permission via composer's `post-install-cmd` but seems to me it is not working correctly though in the log it says the command executed correctly but when I log in to the VM it still show the incorrect permission.

This is what I have in `/composer.json`

```json
"scripts": {
    "post-root-package-install": [
        "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ],
    "post-install-cmd": [
        "chmod -R 777 public\/external_package\/webmail\/data"
    ]
}
```

Here is the screenshot of Cloud Build

<img width="859" alt="gcp file permission issue" src="https://user-images.githubusercontent.com/22704179/106235799-7289ac00-6221-11eb-99ec-25bb5edc3e25.png">

And this is what I see in VM

```
dr-xr-x--- 1 root www-data  4096 Jan 28 19:18 data
```

**I want this dir permission to be 777 rather than 550.**

Can anyone help me on this?

Thanks.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by finallyRaunak** [comment]
Hi @ToddKopriva ,

Thanks for the response, I might have asked it as a question but it feels like there is an issue with App Engine which is not updating the correct permission after deploying.

Anyways I will ask in the support form as well.

Thanks.
