### ISSUE TITLE
Issue with tutorials/setting-up-lamp/index.md

### ISSUE THREAD

**Issue by amsyvah** [GoogleCloudPlatform/community#1604]
Initial test fails to get GCloud external IP after installing apache2 and php, 

user@cloudshell:~ (cloudlearn-30xxx)$ echo '<!doctype html><html><body><h1>Hello World!</h1></body></html>' | sudo tee /var/www/h
tml/index.html
<!doctype html><html><body><h1>Hello World!</h1></body></html>
user@cloudshell:~ (cloudlearn-30xxx)$ http://34.89.xx.xxx
-bash: http://34.89.xx.xxx: No such file or directory
user@cloudshell:~ (cloudlearn-30xxx)

What do I do please?

**Comment by amsyvah** [comment]
Resolved.  I have http working, lamp running.  If ToddKopriva wishes to understand the bug that was, the log files can be set up for access.  Thank you

**Comment by amsyvah** [comment]
and the history of ssh commands as well.

**Comment by ToddKopriva** [comment]
Thanks for reporting back that the issue is resolved.

If you have information to share that you think would bee helpful to others, please do share it.

**Comment by amsyvah** [comment]
Sharing history:   After following instructions from [https://cloud.google.com/community/tutorials/setting-up-lamp#setting-up-dns](url) lamp tutorial's hello world appears on http://external ip , phpinfo.php page is seen without any errors, but phpmyadmin does not display. The history is copied below.  Thank you

  1  ls
    2  ls/
    3  ls /
    4  sudo apt update && sudo apt -y install apache2
    5  sudo apt install apache2 php libapache2-mod-php
    6  echo '<!doctype html><html><body><h1>Hello World!</h1></body></html>' | sudo tee /var/www/html/index.html
    7  sudo sh -c 'echo "[YOUR_PHP_CODE]" > /var/www/html/phpinfo.php'
    8  sudo sh -c 'echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php'
    9  sudo apt-get update
   10  sudo apt-get install mariadb-server php php-mysql
   11  sudo systemctl status mariadb
   12  sudo systemctl start mariadb
   13  sudo mysql
   14  sudo mysql_secure_installation
   15  debian version
   16  debian-version
   17  debian -v
   18  lsb_release
   19  cat /etc/debianversion
   20  ls /etc
   21  cat /etc/issue
   22  sudo apt-get install php-bz2 php-gd php-curl
   23  sudo apt-get install -t buster-backports php-twig
   24  sudo apt-get install phpmyadmin
   25  systemctl php status
   26  systemctl phpmyadmin status
   27  sudo status phpmyadmin
   28  sudo systemctl status php
   29  sudo systemctl start  php
   30  sudo systemctl start  phpmyadmin
   31  sudo apt-get install phpmyadmin
   32  lamp
   33  systemctl status lamp
   34  ls /
   35  ls /var   
36  ls /var/www
   37  ls /var/www/html
   38  history >historylampjan3120210528.txt
   39  cat /historylampjan3120210528.txt
   40  cat /home/historylampjan3120210528.txt
   41  ls /
   42  ls /home
   43  ls /home/xxxx
   44  cat historylampjan3120210528.txt 
   45  # followed instructions from https://cloud.google.com/compute/docs/tutorials/basic-webserver-apache?hl=zh-tw &&  https://cloud.google.com/community/tutorials/setting-up-lamp?hl=zh-tw
   46  cat historylampjan3120210528.txt 
   47  exit
   48  systemctl status lamp
   49  sudo systemctl start  phpmyadmin
   50  sudo apt-get install phpmyadmin
   51  ls /
   52  cd /home/xxxxx
   53  ls
   54  cd /home
   55  ls
   56  locate www
   57  find /www
   58  cd /var
   59  ls
   60  cd /var/www
   61  ls
   62  touch hello.php
   63  sudo touch hello.php
   64  nano hello.php
   65  sudo nano hello.php
   66  sudo sh -c 'echo "[YOUR_PHP_CODE]" > /var/www/html/phpinfo.php'
   67  sudo sh -c 'echo "[hello.php]" > /var/www/html/phpinfo.php'
   68  sudo sh -c 'echo "<?hello.php(); ?>" > /var/www/html/phpinfo.php'
   69  sudo systemctl start mariadb
   70  sudo apt-get install phpmyadmin
   71  history | grep apache
   72  history | grep php
   73  history
 74  sudo sh -c 'echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php'
   75  sudo apt-get update
   76  sudo apt-get install mariadb-server php php-mysql
   77  sudo systemctl status mariadb
   78  sudo systemctl start mariadb
   79  sudo mysql
   80  sudo mysql_secure_installation
   81  sudo apt-get install php-bz2 php-gd php-curl
   82  # this command is only needed for Debian 10
   83  sudo apt-get install -t buster-backports php-twig
   84  sudo apt-get install phpmyadmin
   85  sudo apt-get install --reinstall  phpmyadmin
   86  history
