### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by sripathivenky** [GoogleCloudPlatform/community#1610]
The nginix ingress rule given as:
Create a simple Ingress Resource YAML file that uses the NGINX Ingress Controller and has one path rule defined:

cat <<EOF > ingress-resource.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ${NGINX_INGRESS_IP}.xip.io
    http:
      paths:
      - backend:
          serviceName: hello-app
          servicePort: 8080
        path: /hello
EOF
The kind: Ingress line dictates that this is an Ingress Resource object. This Ingress Resource defines an inbound L7 rule for path /hello to service hello-app on port 8080.

When I run this the subsequent request should be available on the 
http://NGINX_INGESS_IP/hello
and also on
http://NGINX_INGESS_IP.xip.io/hello

But the request only works on http://NGINX_INGESS_IP**.xip.io/hello**

kubectl describe ingresses.extensions ingress-resource
command resulted in:

Default backend:  default-http-backend:80 (x.x.x.x:8080)
Rules:
  Host                   Path  Backends
  ----                   ----  --------
  NGINX_INGESS_IP.xip.io
                         /hello   hello-app:8080 (x.x.x.x:8080)
Annotations:             kubernetes.io/ingress.class: nginx
                         nginx.ingress.kubernetes.io/ssl-redirect: false

So the document should be updated or the config should be updated. I am new so not sure what the right config is.

**Comment by ToddKopriva** [comment]
@ameer00 , can you take a look at this issue about a document that you contributed?

**Comment by ameer00** [comment]
Submitted fix in PR https://github.com/GoogleCloudPlatform/community/pull/1740
