### ISSUE TITLE
Issue with tutorials/singularity-containers-with-cloud-build/index.md

### ISSUE THREAD

**Issue by multikengineer** [GoogleCloudPlatform/community#1627]
gcloud compute instances create ken-singularity-test --machine-type=n1-standard-1 --scopes=https://www.googleapis.com/auth/cloud-platform --metadata-from-file startup-script=startup.sh
 
 ERROR: (gcloud.compute.instances.create) Unable to read file [startup.sh]: [Errno 2] No such file or directory: 'startup.sh'

**Comment by ToddKopriva** [comment]
@wkharold and @vsoch, could you take a look at this issue report about a document that you contributed?

**Comment by vsoch** [comment]
Does the file startup.sh exist in the present working directory where you are running the command @multikengineer ?

**Comment by multikengineer** [comment]
No. The point is the documentation viewed https://cloud.google.com/community/tutorials/singularity-containers-with-cloud-build. makes no mention of cloning (this) git repo.

**Comment by vsoch** [comment]
That's a good point! I'll see if I can do a quick PR to add this (very important) step. You're right - it's totally absent :laughing:

**Comment by multikengineer** [comment]
No problem. We should all have such easy bugs to fix.
(Of course I was able to build a VM that tested the build / execution of singularity containers - just would have been easier if the tutorial included that tidbit.

**Comment by ToddKopriva** [comment]
Thanks, @vsoch . I'll review and merge the pull request with the fix.

**Comment by multikengineer** [comment]
Looks good. Thanks @ToddKopriva @vsoch.

**Comment by vsoch** [comment]
Sounds good! Thanks for the speedy review @ToddKopriva !

**Comment by ToddKopriva** [comment]
This will get published tomorrow with a batch of fixes.
