### ISSUE TITLE
How do I create a Valheim server on GoogleCloud?

### ISSUE THREAD

**Issue by Dibdab001** [GoogleCloudPlatform/community#1629]
I was following a guide to create an Arma 3 server and had got my server to log into steam when the guide tells me the install code for Arma, but I need the valheim one. Can anyone help?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. 

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
