### ISSUE TITLE
Issue with tutorials/tensorflow-automl-classification-python/index.md

### ISSUE THREAD

**Issue by asharashrestha** [GoogleCloudPlatform/community#1632]
## Issue Description:
Under the section **"Formatting the results obtained with TensorFlow"**, **"To know which one is which, go to the Dataset page in the Cloud Console and from there go to the Images tab."** I followed this documentation and found out that my model performance was bad. Later I realized that instead of following the order as shown in the image if I followed the order in the confusion matrix, my results were correct. The order of the labels is just alphabetically sorted by default as shown in the image below:
<img width="443" alt="Screen Shot 2021-02-22 at 10 38 22 AM" src="https://user-images.githubusercontent.com/15857445/108739678-7e078480-74fa-11eb-9d91-33f77a80cbbc.png">

The correct order is shown in confusion matrix:
<img width="432" alt="Screen Shot 2021-02-22 at 10 42 02 AM" src="https://user-images.githubusercontent.com/15857445/108739823-a1323400-74fa-11eb-8065-a98daeaa23e2.png">

I request to change this part of the documentation to avoid this confusion. 

The following statement might be correct as Overexposed comes first than underexposed when ordered alphabetically. But this is not accurate.

**"Overexposed is the first entry, followed by the underexposed entry; in your output array, the first entry is the probability that the given image is overexposed, and the second entry is the probability that the given image is underexposed."**

**Comment by ToddKopriva** [comment]
Thanks for the detailed feedback. We'll have a look.

**Comment by ToddKopriva** [comment]
@harshithdwivedi , could you have a look at this issue report about a document that you contributed?
