### ISSUE TITLE
Missing scan in gcp-cos-clamav

### ISSUE THREAD

**Issue by frenetic-be** [GoogleCloudPlatform/community#1654]
This is related to https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/gcp-cos-clamav. I haven't looked too deeply but it seems to me like `start.py` is missing the cron scheduling of `scan.sh`.

**Comment by ToddKopriva** [comment]
@ianmaddox , can you have a look at this?

**Comment by ianmaddox** [comment]
Cron has recently been removed from this code. Instead, it relies on the `clamd` daemon and its internal scheduling, which you can configure in [clamd.conf](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/gcp-cos-clamav/conf/clamd.conf)

The documentation changes removing references to cron are in the works.

**Comment by ToddKopriva** [comment]
from @ianmaddox :

"Cron has recently been removed from this code. Instead, it relies on the clamd daemon and its internal scheduling, which you can configure in clamd.conf

The documentation changes removing references to cron are in the works."

**Comment by ybudweiser** [comment]
Do you have any documentation on the "internal scheduling" of clamd. Every document i found requires clamdscan to submit a scan request to the daemon still. The daemon just keeps the virus definition in memory for clamdscans, where as running clamscan by itself requires the clamscan to load the virus definition each time. 
Seems like both clamdscan and clamscan require a cronjob

**Comment by ubald** [comment]
This repository is still mentioned in the [GCP documentation on how to run an AV](https://cloud.google.com/architecture/installing-antivirus-and-file-integrity-monitoring-on-container-optimized-os) but as it stands now there is no scheduling happening. `clamdscan` documentation never mentions scheduling anywhere. It is confusing why this was removed.

**Comment by ToddKopriva** [comment]
We've removed this document.
