### ISSUE TITLE
Issue with tutorials/data-science-extraction/index.md

### ISSUE THREAD

**Issue by tugceozgur** [GoogleCloudPlatform/community#1676]
Whatever mp3 I tried, this code cannot read mp3.
community/tutorials/data-science-extraction/convert_audio.py

Converting fables_01_02_aesop_64kb.mp3
EXCEPTION 'utf-8' codec can't decode byte 0xff in position 129: invalid start byte

**Comment by tugceozgur** [comment]
It may not be permanent solution but ignoring errors solved it. 
with open(dest, 'r', errors='ignore') as f:

**Comment by ToddKopriva** [comment]
closing issue because document is being archived
