### ISSUE TITLE
Issue with tutorials/setting-up-postgres.md

### ISSUE THREAD

**Issue by mario-rozario** [GoogleCloudPlatform/community#1695]
This does not work !! 

Connecting from pgAdmin4 to the postgress instance does not work !!

Did all the firewall settings and whatever was mentioned. Cannot see to connect at all from the Postgress Client 
![DT-Postgress](https://user-images.githubusercontent.com/15810557/111033160-dbc22900-8435-11eb-8339-b71e588a0596.JPG)

**Comment by ToddKopriva** [comment]
@xiangshen-dk , you recently updated this document. Could you have a look at this issue report and see if you can provide any insight?

**Comment by xiangshen-dk** [comment]
I have verified on my side and I didn't have the issue. I would like to suggest double-checking the following:

1. The Postgres service is running on the Linux server.
2. The config files /etc/postgresql/12/main/pg_hba.conf and /etc/postgresql/12/main/postgresql.conf both have the correct setup.
2. The correct source IP is used in the config files and also in the firewall setup.
3. The /32 suffix is used in the firewall setup.
4. There are no other firewalls, such as a local firewall or corp firewall, that block the connection.

**Comment by ToddKopriva** [comment]
I'm going to close this issue, since the document seems to be working for others. 

@mario-rozario , feel free to re-open this issue and answer all of the questions from @xiangshen-dk if you're still having trouble.

**Comment by mario-rozario** [comment]
Hello this worked finally. Thanks for the help.
It was an issue with the Postgres account itself that wasn't setting the password correctly.
Thanks for the help.

**Comment by ToddKopriva** [comment]
Glad to hear it. Thanks for letting us know what the issue was.
