### ISSUE TITLE
Issue with tutorials/secrets-manager-python/index.md

### ISSUE THREAD

**Issue by marcogaruthix** [GoogleCloudPlatform/community#1703]
### Wrong documentation.

Change from:
```ALPHA_VANTAGE_KEY = secrets.access_secret_version("projects/"+PROJECT_ID+"/secrets/alpha-vantage-key/versions/1").payload.data.decode("utf-8")```

Change to:
```
ALPHA_VANTAGE_KEY = secrets.access_secret_version({
    "name": "projects/"+PROJECT_ID+"/secrets/alpha-vantage-key/versions/1"
}).payload.data.decode("utf-8")
```

Full documentation link:
_https://cloud.google.com/community/tutorials/secrets-manager-python_

**Comment by ToddKopriva** [comment]
This was recently fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1694

The document will be republished with the fix soon (probably tomorrow).
