### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible

### ISSUE THREAD

**Issue by Humni** [GoogleCloudPlatform/community#171]
After adding `"chmod -R 755 bootstrap\/cache"` to the app.yaml file, I get this error after following the 

```
> chmod -R 755 bootstrap/cache
chmod: cannot access 'bootstrap/cache': No such file or directory
Script chmod -R 755 bootstrap/cache handling the post-deploy-cmd event returned with error code 1
+ echo 'Failed to execute post-deploy-cmd'
+ exit 1
Failed to execute post-deploy-cmd
```
 
After removing this line, Laravel deployed correctly.

**Comment by bshaffer** [comment]
Hey @Humni 
This directory should definitely exist, see [here](https://github.com/laravel/laravel/tree/master/bootstrap/cache). Is it possible you removed it? Or it's possible your `app.yaml` does not contain `skip_files: false`

**Comment by Humni** [comment]
I didn't specifically remove it, but I will run through the tutorial again check that it does work.  
As noted in the initial post, removing it in my situation did fix the issue, I will try to find out why.

**Comment by Humni** [comment]
As it turns out it was something to do with my specific deployment. There is no issue with the tutorial when using a non-modified Laravel deployment
