### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by the-provost** [GoogleCloudPlatform/community#1710]
Cannot deploy Laravel 8 apps to app engine with PHP74 because of absence of ext-sodium (libsodium)

Please support libsodium for PHP74 app Engine Standard

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
