### ISSUE TITLE
Issue with tutorials/sigfox-gw/index.md

### ISSUE THREAD

**Issue by arun-jolly** [GoogleCloudPlatform/community#1715]
Callback functions not working due to a missing entry in the environment variable file.

Hi,
 I am working on integrating Sigfox backend and Google Cloud for my project. While trying to send data from the Sigfox device to the Cloud , I was getting an error " Error reading environment variables". When I looked into the main.py file in the cloned GitHub repository folder community/tutorials/sigfox-gw/cf/, I found a code segment 

topic = os.environ.get('PUBSUB_TOPIC_DATA')
project_id = os.environ.get('GCP_PROJECT')
if not topic or not project_id:
          print('Error reading Function environment variables')
          return abort(500)

However, in the ".env.yaml" file there is no entry for 'GCP_PROJECT'. Also in the community tutorial on integrating Sigfox and Cloud - https://cloud.google.com/community/tutorials/sigfox-gw-  nothing is said about adding the project id for 'GCP_PROJECT'.

I edited the .env.yaml file adding the line 
'GCP_PROJECT'= *** myprojectid***

And it worked!!!!!!!. The callback was successfully called and the message was send to PUB/SUB topic.

**Comment by ToddKopriva** [comment]
@arun-jolly , thanks for letting us know about the issue and what worked for you. We'll take a look.

If you would like to submit a pull request to make the necessary change, I will review and merge that.

**Comment by arun-jolly** [comment]
@ToddKopriva I'm sorry. I'm new to github and coding. I'm not sure how to do a pull request. 
1. Edit the .env.yaml file in the community tutorial folder - community/tutorials/sigfox-gw/cf 
In compliance with the main.py file in the same folder.
2. Mention to add the project Id as an environment variable in the tutorial as well.

These are my two requests.

**Comment by ToddKopriva** [comment]
Thanks, @arun-jolly . We'll take it from here.

**Comment by ToddKopriva** [comment]
@lepistom , could you look into this issue regarding a document that you contributed?

https://cloud.google.com/community/tutorials/sigfox-gw

**Comment by ToddKopriva** [comment]
This document has been removed.
https://github.com/GoogleCloudPlatform/community/pull/2333
