### ISSUE TITLE
Issue with tutorials/sigfox-sensit/index.md

### ISSUE THREAD

**Issue by arun-jolly** [GoogleCloudPlatform/community#1716]
Environment variable missing
Hi, 
I've raised this issue for a similar tutorial. The .env.yaml file in the tutorial folder
Community/tutorials/sigfox-sensit/cf
does not have an environment variable named 
'GCP_PROJECT' which is coded in the main.py file in the same folder. It is also not mentioned in the tutorial under the section "deploy the pub_sub bigquery cloud function"- step 2. 
This variable whose value is the Google project Id is required for the cloud function to work properly. 
It returns an error otherwise.
Please look into this issue.

**Comment by ToddKopriva** [comment]
For others looking at this, the other issue that @arun-jolly referenced is this:
https://github.com/GoogleCloudPlatform/community/issues/1715

**Comment by ToddKopriva** [comment]
@lepistom , could you take a look at this issue reported about a document that you contributed?

https://cloud.google.com/community/tutorials/sigfox-sensit

**Comment by ToddKopriva** [comment]
This document has been removed.
https://github.com/GoogleCloudPlatform/community/pull/2333
