### ISSUE TITLE
Can not install Cloud Monitoring agent on CentOS 7.9.2009

### ISSUE THREAD

**Issue by supershowwei** [GoogleCloudPlatform/community#1717]
I followed the document - Install Cloud Monitoring agent on a single VM (https://cloud.google.com/monitoring/agent/installation) to install Cloud Monitoring agent on CentOS 7.9.2009 and it failed.

I got a error meesage '
https://packages.cloud.google.com/yum/repos/google-cloud-monitoring-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-monitoring'.

Any other way to install Cloud Monitoring agent on CentOS 7.9.2009? thx.

**Comment by xiangshen-dk** [comment]
I just tried on a new VM with the image from GCP [CentOS Linux release 7.9.2009 (Core)] and it worked fine. 

You can double check this yum config file: `/etc/yum.repos.d/google-cloud-monitoring.repo`. Make sure it has the following:

```
[google-cloud-monitoring]
name=Google Cloud Monitoring Agent Repository
baseurl=https://packages.cloud.google.com/yum/repos/google-cloud-monitoring-el7-$basearch-all
autorefresh=0
enabled=1
type=rpm-md
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

You can delete the file and try the install script again. You can also workaround it by disabling repo check: `repo_gpgcheck=0`

**Comment by ToddKopriva** [comment]
Thanks for the help, @xiangshen-dk .
