### ISSUE TITLE
Use of GCF Test the Function Capability

### ISSUE THREAD

**Issue by sternisc** [GoogleCloudPlatform/community#172]
Could use a tutorial or expansion to other tutorials to cover the json format of how to test. Is it only the message, the url, the request, etc?

**Comment by jmdobry** [comment]
Hi @sternisc, can you be more specific? Are you wondering about the format of arguments passed to Cloud Functions?

**Comment by sternisc** [comment]
Hi Jason!
Yes. GCF states it needs to be JSON formatted for the arguments (assuming
this is all the environmental, headers, etc in addition to host, url,
query, etc.) to perform the test but there are no examples of how to
actually perform a local test or what part of the response object etc
should be used.
If I am going to work through GCF UI instead of a browser/browser developer
tools and/or a local instance, it would be helpful to know what argument
structure is expected, over trial and error, etc. I might learn some really
cool things I didn't think of too!

Dave

**Comment by jmdobry** [comment]
Let me point you to a few docs:

* [HTTP functions](https://cloud.google.com/functions/docs/writing/http) specify that the function receives `req`, and `res` arguments like with [Express.js](http://expressjs.com/)
  * You provide a body, headers, and query parameters to the function when you make the HTTP request
* [Background functions](https://cloud.google.com/functions/docs/writing/background) specify that the function receives `event` and `callback` arguments.
  * The properties of `event` are documented [here](https://cloud.google.com/functions/docs/writing/background#event_parameter) (you don't control these)
  * However, `event.data` is the payload that will be sent to the function from Cloud Storage, Cloud Pub/Sub, or you (in the case of your manual test).
  * For examples of JSON payloads you can provide to functions, see [Direct Triggers](https://cloud.google.com/functions/docs/calling/direct#calling_background_functions) and [Calling functions](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Calling-functions#calling-background-functions)
  * Note that Pub/Sub functions expect `event.data` to be a [PubSub Message object](https://cloud.google.com/pubsub/docs/reference/rest/v1/PubsubMessage), as documented [here](https://cloud.google.com/functions/docs/calling/pubsub#cloud_pubsub_events)
  * Note that Storage functions expect `event.data` to be an [Object resource](https://cloud.google.com/storage/docs/json_api/v1/objects#resource), as documented [here](https://cloud.google.com/functions/docs/calling/storage#cloud_storage_events)

**Comment by ToddKopriva** [comment]
@sternisc : I'm closing this issue, since it seems that the comment from @jmdobry answers your question.
