### ISSUE TITLE
Issue with tutorials/cloud-functions-rate-limiting/index.md

### ISSUE THREAD

**Issue by jeff-romine** [GoogleCloudPlatform/community#1720]
The clean up step here has a problem.  

`gcloud beta compute networks vpc-access connectors create functions-connector --quiet`

should be:

`gcloud beta compute networks vpc-access connectors delete functions-connector --quiet --region $REGION`

**Comment by ToddKopriva** [comment]
Thanks. I'll have a look.

Feel free to make a pull request to make fixes like this yourself, and we can review and merge them.

**Comment by ToddKopriva** [comment]
@jeff-romine fixed this issue with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1722
