### ISSUE TITLE
Issue with tutorials/embedded-c-getting-started/index.md

### ISSUE THREAD

**Issue by JakeLewisFSC** [GoogleCloudPlatform/community#1721]
One of the steps is to find `mqtt-example.c`

But this file doesn't exist in the downloaded Github file.

in this document 
https://cloud.google.com/community/tutorials/embedded-c-getting-started

However, it seems the code it wants you to look at is now at a file name `smart_outlet_example.c`

Could be frustrating for some users to be told to look for a file that doesn't exist

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll look into it.

**Comment by ToddKopriva** [comment]
@galz10 , can you take a look at this suggestion regarding a document that you contributed?

**Comment by ToddKopriva** [comment]
@gguuss or @hongalex , could you take a look at this sgguestion about an update needed for Gal's document?

**Comment by gguuss** [comment]
Gal should be coming back soon, but I can take a quick look. The sample is based on the Smart Outlet example but the provided sample sources are in [getting-started.c](https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/embedded-c-getting-started/examples/main). I'll take a look at the article sources for an update.

**Comment by galz10** [comment]
Fixed the issue [PR](https://github.com/GoogleCloudPlatform/community/pull/2015)

**Comment by ToddKopriva** [comment]
Thanks, @galz10 .
