### ISSUE TITLE
Google Repository Signature Issue

### ISSUE THREAD

**Issue by gregarios** [GoogleCloudPlatform/community#1723]
When trying to run 'yum update' I get the following error:

`Determining fastest mirrors
epel/x86_64/metalink                                                                                                                                                             |  12 kB  00:00:00     
 * base: mirror.fileplanet.com
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirror.sfo12.us.leaseweb.net
 * updates: sjc.edge.kernel.org
PLESK_17_PHP73                                                                                                                                                                   | 2.9 kB  00:00:00     
PLESK_17_PHP74                                                                                                                                                                   | 2.9 kB  00:00:00     
PLESK_17_PHP80                                                                                                                                                                   | 2.9 kB  00:00:00     
PLESK_18_0_34-extras                                                                                                                                                             | 2.9 kB  00:00:00     
base                                                                                                                                                                             | 3.6 kB  00:00:00     
epel                                                                                                                                                                             | 4.7 kB  00:00:00     
extras                                                                                                                                                                           | 2.9 kB  00:00:00     
google-cloud-compute/signature                                                                                                                                                   |  844 B  00:00:00     
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
google-cloud-compute/signature                                                                                                                                                   | 1.4 kB  00:00:00 !!! 
https://packages.cloud.google.com/yum/repos/google-cloud-compute-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-compute
Trying other mirror.

 One of the configured repositories failed (Google Cloud Compute),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=google-cloud-compute ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable google-cloud-compute
        or
            subscription-manager repos --disable=google-cloud-compute

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=google-cloud-compute.skip_if_unavailable=true

failure: repodata/repomd.xml from google-cloud-compute: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/google-cloud-compute-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for google-cloud-compute
`

**Comment by ToddKopriva** [comment]
Is this issue report about a document in this repository? If so, which one?

**Comment by gregarios** [comment]
I may have reported this in the wrong section. I'm trying to report an issue with a Google Cloud Compute yum repository failure...

**Comment by valarauca** [comment]
> Is this issue report about a document in this repository? If so, which one?

Not necessarily, it seems that the repository is serving bad data causing `yum` & `dnf` to fail. It seems to be a repository failure.

---

I am also experiencing this issue. We cannot pull the cloud sdk from `packages.cloud.google.com`. We are following the steps outlined on [this page (sdk install docs)](https://cloud.google.com/sdk/docs/install#rpm). It is scripted in ansible and was working this morning.

**Comment by ToddKopriva** [comment]
OK. Then please report the bug using the **Send feedback** button on that affected page:
https://cloud.google.com/sdk/docs/install

The issues section of this repository is for a different set of documents: just the tutorials that have their source in this repository. These documents and the software that you're having an issue with are handled by different teams.
