### ISSUE TITLE
Python cloud function with Firestore

### ISSUE THREAD

**Issue by nxquang1994** [GoogleCloudPlatform/community#1738]
Hi, I wanna a demo with Python cloud function connecting firestore. I only see the nodejs demo.
Currently, I write code python cloud function connect to Firestore same as code Python running my dedicate server, not run in FIrebase like Cloud function.

**Comment by xiangshen-dk** [comment]
You can find Python examples from the Cloud Firestore doc at: https://firebase.google.com/docs/firestore/quickstart

There is no big difference to use it in Cloud Functions. If you are interested, I have an example at:
https://github.com/GoogleCloudPlatform/serverless-log-trigger-demo/blob/master/trace-metric-demo/function_src/main.py

**Comment by ToddKopriva** [comment]
Thanks, @xiangshen-dk .

I'm going to close this request. @nxquang1994 , feel free to re-open it if you don't think that the answer above is adequate.
