### ISSUE TITLE
Issue with tutorials/vm-migration-with-stratozone/index.md

### ISSUE THREAD

**Issue by tiny-tinker** [GoogleCloudPlatform/community#1773]
Several of the links on this page lead to a broken page on the StratoZone web site. For example, the "SSH or WMI access" link in Discovery 1 redirects to this page:
https://portal.stratozone.com/Error.aspx?aspxerrorpath=/Documentation/StratoProbe_Guide.html#4

Same with the "Troubleshooting" at the bottom of the page. It points to this link:
https://portal.stratozone.com/Documentation/StratoProbe_Troubleshooting.html

But redirects to this one:
https://portal.stratozone.com/Error.aspx?aspxerrorpath=/Documentation/StratoProbe_Troubleshooting.html

**Comment by ToddKopriva** [comment]
Thanks. I'll take a look.

**Comment by ToddKopriva** [comment]
@laidig , could you update this document that you created with current links?
