### ISSUE TITLE
Issue with tutorials/deploy-react-nginx-cloud-run/index.md

### ISSUE THREAD

**Issue by iusamakhan** [GoogleCloudPlatform/community#1778]
Issue Description

Hi, I have implemented this and everything is working fine but the environment variables defined in the cloud run service are undefined. I am not able to understand that because with the NODE project environment variables are defined but when it comes to REACT these its undefined. looking forward to the solution.
thank you!

**Comment by ToddKopriva** [comment]
Did this refresh of the tutorial fix the issue?
https://github.com/GoogleCloudPlatform/community/pull/1865

I'm going to close this issue now, because it seems that the tutorial is working now. But don't hesitate to re-open this issue if there's still a problem.
