### ISSUE TITLE
Issue with tutorials/migrate-oracle-postgres-using-ora2pg/index.md

### ISSUE THREAD

**Issue by pgoldtho** [GoogleCloudPlatform/community#1789]
Broken links:

    Setting up Cloud SQL for PostgreSQL for production use
    Migrating Oracle users to Cloud SQL for PostgreSQL: Terminology and functionality
    Migrating Oracle users to Cloud SQL for PostgreSQL: Data types, users, and tables
    Migrating Oracle users to Cloud SQL for PostgreSQL: Queries, stored procedures, functions, and triggers
    Migrating Oracle users to Cloud SQL for PostgreSQL: Security, operations, monitoring, and logging

I'm getting 404 error on each. E.g. https://cloud.google.com/architecture/setting-up-cloud-sql-for-postgresql-for-production

**Comment by ToddKopriva** [comment]
Thanks for the report. Fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1790

The links should point to /solutions, not /architecture .

The document will be updated on cloud.google.com soon.
