### ISSUE TITLE
Error in preflight while creating cluster on Bare metal

### ISSUE THREAD

**Issue by kaushalabhishek** [GoogleCloudPlatform/community#1801]
I am trying to create on-prem cluster on Bare metal with following infra detail  -
_Master node 10.10.100.181
worker node- 10.10.100.180_
VIP detail -
        _10.10.100.180	10.10.100.181
2	10.10.100.41	10.10.100.46
3	10.10.100.42	10.10.100.47
4	10.10.100.43	10.10.100.48
5	10.10.100.44	10.10.100.49
6	10.10.100.45	10.10.100.50_

I am getting error on when trying to create cluster using command  - **./bmctl create cluster -c cluster1**

_TASK [vip_test : fail] *********************************************************
fatal: [10.10.100.181]: FAILED! => {"changed": false, "msg": "vip 10.10.100.41 is already used (should not be pingable)"}
fatal: [10.10.100.180]: FAILED! => {"changed": false, "msg": "vip 10.10.100.41 is already used (should not be pingable)"}
fatal: [localhost]: FAILED! => {"changed": false, "msg": "vip 10.10.100.41 is already used (should not be pingable)"}

NO MORE HOSTS LEFT *************************************************************
	
PLAY RECAP *********************************************************************
10.10.100.180              : ok=21   changed=7    unreachable=0    failed=1    skipped=8    rescued=0    ignored=0   
10.10.100.181              : ok=25   changed=9    unreachable=0    failed=1    skipped=7    rescued=0    ignored=0   
localhost                  : ok=15   changed=6    unreachable=0    failed=1    skipped=13   rescued=0    ignored=0   

F0504 17:02:50.723876       1 main.go:48] exit status 2_

My Cluster YMAL is 

gcrKeyPath: /home/<<USER>>/baremetal/bmctl-workspace/.sa-keys/anthos-sandbox-anthos-baremetal-gcr.json
sshPrivateKeyPath: /home/<<USER>>/.ssh/id_rsa
gkeConnectAgentServiceAccountKeyPath: /home/<<USER>>/baremetal/bmctl-workspace/.sa-keys/anthos-sandbox-anthos-baremetal-connect.json
gkeConnectRegisterServiceAccountKeyPath: /home/<<USER>>/baremetal/bmctl-workspace/.sa-keys/panthos-sandbox-anthos-baremetal-register.json
cloudOperationsServiceAccountKeyPath: /home/<<USER>>/baremetal/bmctl-workspace/.sa-keys/anthos-sandbox-anthos-baremetal-cloud-ops.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: cluster-cluster1
---
apiVersion: baremetal.cluster.gke.io/v1
kind: Cluster
metadata:
  name: cluster1
  namespace: cluster-cluster1
spec:
  type: hybrid
   anthosBareMetalVersion: 1.6.2
   gkeConnect:
    projectID: anthos-sandbox
   controlPlane:
    nodePoolSpec:
      nodes:
      - address: 10.10.100.181
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  loadBalancer:
    mode: bundled
    ports:
      controlPlaneLBPort: 443
    vips:
      controlPlaneVIP: 10.10.100.41
      ingressVIP: 10.10.100.42
    addressPools:
    - name: pool1
      addresses:
      - 10.10.100.42-10.10.100.50
    projectID: pk-anthos-sandbox
    location: us-central1
  storage:
    lvpNodeMounts:
      path: /mnt/localpv-disk
      storageClassName: local-disks
    lvpShare:
      path: /mnt/localpv-share
      storageClassName: local-shared
      numPVUnderSharedPath: 5
---
apiVersion: baremetal.cluster.gke.io/v1
kind: NodePool
metadata:
  name: node-pool-1
  namespace: cluster-cluster1
spec:
  clusterName: cluster1
  nodes:
  - address: 10.10.100.180

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
