### ISSUE TITLE
issue with gcp-cos-clamav

### ISSUE THREAD

**Issue by Tom284** [GoogleCloudPlatform/community#1812]
I pulled the repository but then when I tried to launch the Docker image (which I made from the pulled Dockerfile) it wouldn't work. I would get this message:

`/bin/sh: /start.py: not found`

So I had to change the Dockerfile into:

```
# Dockerfile for clamav service
FROM alpine:3.8
RUN apk add --no-cache \
  python3 py3-pip \
  && pip3 install --upgrade pip
RUN apk add --no-cache clamav rsyslog wget clamav-libunrar
RUN mkdir -p /logs /data

COPY conf /etc/clamav-custom
COPY start.py /start.py
COPY health.sh /health.sh
COPY scan.sh /scan.sh
RUN chmod +x /health.sh /scan.sh

CMD ["python3", "/start.py"]
```
[(this site](https://jsonformatter.org/yaml-formatter) said that the yaml file from the repo was invalid as well.)

After that is done I keep getting: 
`ERROR: Incorrect argument format for option LogSyslog `
`ERROR: Incorrect argument format for option Foreground`
`ERROR: Incorrect argument format for option LogFileMaxSize`
with the argument being pretty much random each time. 

I also get these errors when I make the clamd and freshclam configs pretty much empty:

```
ERROR: Update failed for database: daily

ERROR: Database update process failed: Connection failed

ERROR: Update failed.

ERROR: Incorrect argument format for option TCPSocket

ERROR: Can't open/parse the config file /etc/clamav/clamd.conf
```

I am following [this tutorial](https://cloud.google.com/architecture/installing-antivirus-and-file-integrity-monitoring-on-container-optimized-os#deploying_av_and_fim_to_a_gke_cluster). I pulled the repo, and the dockerfile builds 

I really want to be able to scan specifics pods and I don't know what I am doing wrong.

**Comment by ToddKopriva** [comment]
@ianmaddox , can you take a look at this issue regarding a document that you contributed?

**Comment by Tom284** [comment]
I ended up testing it on another machine as well and I had the same issue(s).

**Comment by ToddKopriva** [comment]
We've removed this document.
