### ISSUE TITLE
DokuWiki App Engine Tutorial

### ISSUE THREAD

**Issue by cgalo5758** [GoogleCloudPlatform/community#1813]
[DokuWiki](https://www.dokuwiki.org/dokuwiki) is a popular lightweight wiki engine. I think a tutorial on setting this up on app engine might be really useful to illustrate how to connect an application which stores data in files to the app's Cloud Storage bucket.

I am currently attempting to set up a DokuWiki instance on app engine, but I am experiencing difficulties connecting to my app's cloud storage bucket. I have looked at the samples for how to connect using the stream wrapper for the 'gs' protocol (gs://) but I am not entirely certain I comprehend the concept of a stream wrapper to implement it. I have attempted to make changes to make the set up work out, but I am genuinely stuck and don't know what to do.

Additionally, I was wondering if it might be possible to mount a bucket as an app engine folder (Maybe this doesn't make sense? A bucket with a bucket pointer?)

**Comment by ToddKopriva** [comment]
Thanks for the tutorial request.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by cgalo5758** [comment]
Why was this closed?

**Comment by ToddKopriva** [comment]
It was closed because we directed you to a better place for your question.

**Comment by Rohit484** [comment]
right
