### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by manojonurnet** [GoogleCloudPlatform/community#1816]
WordPress is an open source web framework for PHP developers that encourages the use of the model-view-controller (MVC) pattern.
This is incorrect. WordPress is a CMS.

**Comment by ToddKopriva** [comment]
@bshaffer , can you help @manojonurnet with his implicit question about what is meant by the first sentence here?
https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard

**Comment by bshaffer** [comment]
@manojonurnet is right, this must have been copied accidentally over from the laravel tutorial

**Comment by ToddKopriva** [comment]
Thanks for pointing this out, @manojonurnet . Thanks for the quick fix, @bshaffer .
