### ISSUE TITLE
Issue with tutorials/deploy-react-nginx-cloud-run

### ISSUE THREAD

**Issue by oliverbevan** [GoogleCloudPlatform/community#1818]
error chalk@4.1.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
error Found incompatible module.

I got the above error by running the command:
gcloud builds submit --tag gcr.io/ordinal-nucleus-307711/cra-cloud-run

I was able to fix the error by changing the Dockerfile to:
FROM node:10-alpine as react-build

I have made a pull request for the same:
https://github.com/GoogleCloudPlatform/community/pull/1825

**Comment by ToddKopriva** [comment]
Thanks for the report and the fix. I commented on your pull request about one remaining step.
