### ISSUE TITLE
[Question]  How can I scan a specific pod with gcp-cos-clamav?

### ISSUE THREAD

**Issue by Tom284** [GoogleCloudPlatform/community#1824]
[The tutorial](https://cloud.google.com/architecture/installing-antivirus-and-file-integrity-monitoring-on-container-optimized-os#deploying_av_and_fim_to_a_gke_cluster) leaves off with scanning the entire system by running: 
`clamdscan --multiscan /host-fs`
How would I now scan a specific pod?
I can find pod files by running: 
`kubectl exec -it {pod name} ls` but how would I now scan these files/this pod? DO I need to give clamav specific rights or do I need to use a command?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

That said, I'm tagging @ianmaddox in case he can help with your question here.

**Comment by Tom284** [comment]
Thank you! I will ask my question there as well.

**Comment by ToddKopriva** [comment]
I'll close this instance of the question.
