### ISSUE TITLE
Issue with tutorials/speech2srt/index.md

### ISSUE THREAD

**Issue by rezab777** [GoogleCloudPlatform/community#1832]
Issue Description
When running speech2srt.py, RecognitionConfig is not found.

`python3 speech2srt.py --storage_uri gs://$BUCKET_IN/example.wav --sample_rate_hertz 24000
`
```
Transcribing gs://audio_in/example.wav ...
Traceback (most recent call last):
  File "speech2srt.py", line 159, in <module>
    main()
  File "speech2srt.py", line 153, in main
    subs = long_running_recognize(args)
  File "speech2srt.py", line 35, in long_running_recognize
    encoding = speech.RecognitionConfig.AudioEncoding.LINEAR16
**AttributeError: module 'google.cloud.speech_v1' has no attribute 'RecognitionConfig'**
```

**Comment by rezab777** [comment]
solved by replacing python3 with python.

**Comment by ToddKopriva** [comment]
Is there something that we could do to prevent other folks from having this issue? Feel free to submit a pull request to make the document more clear.
