### ISSUE TITLE
Issue with tutorials/slack-bot-cloud-functions-scheduler.md

### ISSUE THREAD

**Issue by adanba** [GoogleCloudPlatform/community#1835]
Hey,

Can you please share the index.js file ?

Regards

**Comment by adanba** [comment]
I found it.
https://gist.github.com/Timtech4u/2f59976a183eefe57bb65be247de49b5
Thank you

**Comment by ToddKopriva** [comment]
Thanks. Did you find that link in the "Get the sample code" section?

I'd be curious to know how we could make that more clear.

**Comment by adanba** [comment]
it's clear, it was my fault.

Even we can improve this by adding code index.js as snippet in the article.

Thank you
