### ISSUE TITLE
Issue with tutorials/kubernetes-engine-customize-fluentbit/index.md

### ISSUE THREAD

**Issue by bpaduch** [GoogleCloudPlatform/community#1844]
Advise users of this tutorial that this doesn't work with Windows Server nodes.  Add the following:

"Note: This tutorial applies to Linux nodes. Windows Server nodes are not customizable at this time."

**Comment by ToddKopriva** [comment]
Thanks for the report.

**Comment by ToddKopriva** [comment]
@xiangshen-dk , I just want to check with you before I make this note in a document that you contributed.

**Comment by xiangshen-dk** [comment]
@ToddKopriva Thanks for checking!
It works for me. Please make the change.
