### ISSUE TITLE
workflow-cloudfucntions

### ISSUE THREAD

**Issue by pavithranagaraj26** [GoogleCloudPlatform/community#1852]
Hi,

Can we create a pipeline to integrate many cloud functions as a sequence in workflow?

**Comment by ayapsone** [comment]
@pavithranagaraj26  - Can you please explain more what you need ? is it 
both cloudfunction & workflow yaml in git and using cloudbuild deploy to gcp ?

**Comment by pavithranagaraj26** [comment]
Yes, kind of the same services to deploy to GCP.  @ayapsone If there are some deep-dive in workflows it will be helpful.

**Comment by varundhussa** [comment]
@pavithranagaraj26 The tutorial on [serverless orchestration](https://cloud.google.com/architecture/serverless-orchestration-loading-data-from-cloud-storage-to-biquery-using-workflows) should help. The sample workflow is available [here](https://github.com/GoogleCloudPlatform/bigquery-workflows-load/blob/main/workflow.yaml).

**Comment by ToddKopriva** [comment]
Thanks, for that tutorial link, @varundhussa .

@pavithranagaraj26 , please let us know if that document is what you were looking for.

**Comment by pavithranagaraj26** [comment]
@ToddKopriva  This is based on bigquery. But as a DevOps and Infrastructure engineer, I was expecting some use case which is used for infra automation purpose. Like custom patching or cloud functions to run scripts. This is not what I was expecting. if you can help me better, would be grateful.

**Comment by ayapsone** [comment]
@pavithranagaraj26 - Are you OK, if I provide a sample for this Infra Automation use case https://cloud.google.com/workflows#section-7
Basic idea
1. When VM is created, Tag the resource - IDLE_TIME=<starthour>-<endhour>
2. scheduler 1 runs
3. Looks for running , stop the vm as per tag

From this you should be able to build out your use case, starting point of your workflow might change like HTTP/cloud build etc.
