### ISSUE TITLE
Issue with tutorials/embedded-c-getting-started/index.md

### ISSUE THREAD

**Issue by Tomaszito** [GoogleCloudPlatform/community#1853]
Issue Description
The attached codes dont work on google cloud services.

**Comment by ToddKopriva** [comment]
@Tomaszito , can you give us more detail about the problems that you encountered?

**Comment by ToddKopriva** [comment]
@galz10 , I want to make sure that you see this report about a document that you contributed.

**Comment by galz10** [comment]
@ToddKopriva thanks i'll keep an eye out for Tomaszito response

**Comment by ToddKopriva** [comment]
closing because we didn't get a response with details
