### ISSUE TITLE
Issue with tutorials/using-ha-vpn-with-fortigate/index.md

### ISSUE THREAD

**Issue by Roofahg** [GoogleCloudPlatform/community#1857]
Issue Description:

1. Customer has 'One peer VPN device with one IP address', a supported model
https://cloud.google.com/network-connectivity/docs/vpn/concepts/topologies

2. Documentation explains how to setup for one peer and 2 addresses. Can we please amend the documentation to explain the changes needed for one peer and one address. In this case you need to set [ON_PREM_GW_IP_0] and [ON_PREM_GW_IP_1] to the same IP address.

**Comment by ToddKopriva** [comment]
This unmaintained document has been moved to the archive.

https://github.com/GoogleCloudPlatform/community/pull/2426
