### ISSUE TITLE
I am having trouble with gcloud on my terminal

### ISSUE THREAD

**Issue by JamesVanWaza** [GoogleCloudPlatform/community#1875]
I didn't find the correct place to submit this issue, but this is the problem I am facing

<img width="1888" alt="Screen Shot 2021-07-05 at 5 32 14 PM" src="https://user-images.githubusercontent.com/4000076/124519327-f5a5c400-ddb6-11eb-93a5-41960113359c.png">

Let me know other details you would require.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
