### ISSUE TITLE
Issue with tutorials/setting-up-lamp/index.md

### ISSUE THREAD

**Issue by CapobiancoLuca** [GoogleCloudPlatform/community#1888]
after installing php my admin, where ce test php my admin you forgot this command sudo ln -s / usr / share / phpmyadmin / / var / www / html /, otherwise PHP my admin doesn't work

**Comment by ToddKopriva** [comment]
@xiangshen-dk , you recently updated this tutorial. Could you have a look at this issue report?

**Comment by xiangshen-dk** [comment]
If all the steps are completed successfully, we don't need to manually create a link under `/var/www/html`. The reason is the installation will create the config file `/etc/apache2/conf-enabled/phpmyadmin.conf`, which has an alias `/phpmyadmin` pointing to `/usr/share/phpmyadmin`.
