### ISSUE TITLE
Issue with tutorials/docker-compose-on-container-optimized-os.md

### ISSUE THREAD

**Issue by danielgak** [GoogleCloudPlatform/community#1894]
Can you provide an example of how to authenticate into **GCR** when runing _docker compose_ on _cos_ so one can use private imges with this docker compose command? [docs](https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os)
Normally the _cos_ instance will be authenticated or one can configure the authentication with service accounts and then run `docker-credential-gcr configure-docker`, and this does work for the GCR instance as its explained [here](https://cloud.google.com/container-registry/docs/advanced-authentication) but it turns out that if you authenticate the  docker's *cos* instance, the command:

```
docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -v "$HOME/.docker:$HOME/.docker"
    -w="$PWD" \
    docker/compose:1.24.0 pull
```
will fail:
```
ERROR: for ***** unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by tswast** [comment]
That's a good question. I wonder if some kind of networking pass-through is needed to access the metadata server? `gcloud` and `bq` commands were working OK when I tested this, so probably not that.

**Comment by tswast** [comment]
Does the service account you are using to run the instance have access to the bucket where the images are stored?

**Comment by danielgak** [comment]
After searching a bit, I read this [medium post](https://medium.com/@sachin.d.shinde/docker-compose-in-container-optimized-os-159b12e3d117) and he mentions this:

> using ‘docker-credential-gcr’ seems to be easy approach and it is, however authentication that way does not work with docker compose. docker compose is not available in COS by default, you have to use and run it’s docker image, hence authentication issue still popup when you run that container and try to pull docker image’s mention in your docker-compose.yml file,from Private Google Container Registry.

And I end up solving the issue for my usecase... however I would like to know if there is a better aproach for this.



```bash 
# First I extract the service account token:

token=$(curl --silent --header "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token)
access_token=$(echo ${token} | grep --extended-regexp --only-matching "(ya29.[0-9a-zA-Z._-]*)")

# Manually log in into docker

/usr/bin/docker login -u oauth2accesstoken -p "${access_token}" https://eu.gcr.io

# I enshure that the configuration is available in the *docker compose image* when runing docker compose

docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -v "$HOME/.docker:/root/.docker" \
    -w="$PWD" \
    docker/compose:1.24.0 pull
```

**Comment by tswast** [comment]
I'm not aware of an alternative, but also haven't worked much with Docker the past few years. Pull requests are welcome.
