### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by vorugantivishwanath** [GoogleCloudPlatform/community#1896]
Web page has got below information:
Author(s): @chrisst ,   Published: 2018-08-17

We are in 2021 now, so my request is to update the webpage or provide latest information.

**Comment by ToddKopriva** [comment]
Is there something specific that you are seeing that is out of date?

Please give as much detail as you can about the parts of the document that you think need to be updated.

**Comment by vorugantivishwanath** [comment]
Hi,

Nothing specific but as a learner I felt like I am following outdated
description.

Hope you got my point

**Comment by ToddKopriva** [comment]
Thanks for the response. Feel free to re-open this issue if you see anything that is outdated that needs to be updated.

**Comment by vorugantivishwanath** [comment]
Hi,

May I know resolution for this issue?

**Comment by ToddKopriva** [comment]
> May I know resolution for this issue?

If we are given any specific information about parts of this document that need to be updated, then we will update it.
