### ISSUE TITLE
Issue with tutorials/cloud-iot-enviro-board-workshop/index.md

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#1900]
I'm copying this report over from a different bug-reporting system so that it's visible to all contributors to this repository.

https://cloud.google.com/community/tutorials/cloud-iot-enviro-board-workshop

"Step "Get the public key of the secure element of the sensor board" end with an error:

pi@raspberrypi:/usr/lib/python3/dist-packages/coral/cloudiot $ python3 ecc608_pubkey.py
No crypto detected, using SW.
pi@raspberrypi:/usr/lib/python3/dist-packages/coral/cloudiot $

I got my ESB last week & started this tutorial. I am able to print data from the temperature, humidity, ambient light, and pressure sensors onto the board's OLED display but cannot get the tutorial for cloud iot working."

**Comment by hongalex** [comment]
Unfortunately, Cloud IoT Core is being discontinued on August 16, 2023. For those interested, ClearBlade (a GCP partner) is going to be offering a [1-click migration path](https://www.clearblade.com/wp-content/uploads/2022/08/ClearBlade-Google-IoT-Core-Migration_Website.pdf).

**Comment by ToddKopriva** [comment]
Thanks for the update, Alex.
