### ISSUE TITLE
Issue with tutorials/kotlin-ktor-app-engine-java8/index.md

### ISSUE THREAD

**Issue by crazo7924** [GoogleCloudPlatform/community#1907]
JCenter has become read-only. MavenCentral could be used instead.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
