### ISSUE TITLE
Issue with tutorials/gke-filestore-dynamic-provisioning/index.md

### ISSUE THREAD

**Issue by bgrant0607** [GoogleCloudPlatform/community#1908]
Please update all tutorials with old installation instructions for Helm.

https://cloud.google.com/s/results?q=%22storage.googleapis.com%2Fkubernetes-helm%22

The official way to install helm changed 2 years ago:
https://helm.sh/blog/get-helm-sh/

No new releases have been pushed to the old location for ages, and that bucket is going away in favor of the official CNCF/project hosting location.

Installation instructions:
https://helm.sh/docs/intro/install/

**Comment by bgrant0607** [comment]
cc @viglesiasce

**Comment by bgrant0607** [comment]
Deprecating this tutorial if it's no longer relevant would also be fine.

**Comment by ToddKopriva** [comment]
@wkh , could you take a look at this issue regarding a tutorial that you contributed:
https://cloud.google.com/community/tutorials/gke-filestore-dynamic-provisioning

**Comment by ToddKopriva** [comment]
fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1909
