### ISSUE TITLE
Issue with tutorials/appengine-ruby-rails-activejob-sidekiq.md

### ISSUE THREAD

**Issue by tracyperangusta** [GoogleCloudPlatform/community#1913]
Hello,

Foreman is no longer usable in production environment 👎🏽 
https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman

I guess we need to update the article

**Comment by ToddKopriva** [comment]
Thanks for that, @tracyperangusta .

Feel free to submit a pull request to make the fix yourself. If you'd rather not, then I can look into doing so.

**Comment by ToddKopriva** [comment]
The easy update would be to just remove option A. I'll take that approach unless someone has a better idea.
