### ISSUE TITLE
fluentbit tutorial referencing non-existing image

### ISSUE THREAD

**Issue by toadjaune** [GoogleCloudPlatform/community#1917]
Following https://github.com/GoogleCloudPlatform/community/pull/1911, the fluentbit example manifests refers to `gcr.io/cloud-solutions-images/fluent-bit:1.8`, which does not exist.

Only a `1.6` tag exists in this repository : https://console.cloud.google.com/gcr/images/cloud-solutions-images/GLOBAL/fluent-bit

Reverting back to `1.6` does not work either, you get 400s answers from stackdriver in fluentbit logs.

I assume the correct fix would be to build and push the correct image into the registry ?

**Comment by ToddKopriva** [comment]
Thanks for the report. We'll look into it.

**Comment by toadjaune** [comment]
Using `gcr.io/gke-on-prem-release/fluent-bit:v1.7.7-gke.4` seems to be a working workaround.

Not sure if we can consider it a proper fix, I'd expect not.

**Comment by ToddKopriva** [comment]
This is fixed by pull request #1947 .
