### ISSUE TITLE
Issue with setting-up-lamp

### ISSUE THREAD

**Issue by tenebreux** [GoogleCloudPlatform/community#192]
Package php is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libapache2-mod-php is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php' has no installation candidate
E: Package 'libapache2-mod-php' has no installation candidate

**Comment by bshaffer** [comment]
Thank you for reporting this issue. Are you using Debian, Ubuntu, or CentOS as your Compute Engine OS?

**Comment by tenebreux** [comment]
Hi Brent,

I’m using Debian 8

**Comment by remedcu** [comment]
Same problem still exists

**Comment by bshaffer** [comment]
Hey guys, for Debian 8 and Ubuntu 14 use the following commands instead:

```
sudo apt-get update
sudo apt-get install apache2 php5 libapache2-mod-php5
```
