### ISSUE TITLE
Issue with tutorials/drupal-on-compute-engine.md

### ISSUE THREAD

**Issue by imclean557** [GoogleCloudPlatform/community#1920]
The Drupal modules "PHPMailer SMTP" and "SMTP Authentication Support" do the same thing, it is not necessary to install both. For a while there the SMTP Auth module didn't support installing the PHPMailer library via composer which is probably why the guide was written this way. 

Installing either module via composer will now also install the PHPMailer library.

See the module pages and issue queues for the differences between the modules.

**Comment by ToddKopriva** [comment]
We're archiving this tutorial, so I'm closing this issue.
