### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md File Limit of 10,000 files

### ISSUE THREAD

**Issue by ChamaruAmasara** [GoogleCloudPlatform/community#1921]
Issue Description

Although we can start a Wordpress site in App Engine, we can't expand it because there is a file limit of 10,000 for deployments by default. Is there a workaround to get rid of this file limit?

**Comment by ChamaruAmasara** [comment]
Usually, WordPress sites easily scale more than 10,000 files.
The WordPress 5.8 core has 2,622 Files.

**Comment by ToddKopriva** [comment]
@ChamaruAmasara , I think that you'll get more people to see your question and help you out if you bring your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.

**Comment by ChamaruAmasara** [comment]
Sure thing.
It was already answered in the forums. But I just thought it may be worth pointing it out in the tutorial because many people may be stuck in this file limit.
By the way, your tutorial was super useful. Thank you very much. 😊
