### ISSUE TITLE
Setting Up LAMP on Compute Engine Tutorial

### ISSUE THREAD

**Issue by hkiame** [GoogleCloudPlatform/community#1925]
On this section, Optional: Use phpMyAdmin for database administration. The following steps should be added

- on /etc/php/apache2/php.ini turn on extension=mysqli.so
- on /etc/apache2/apache2.conf add  
    ```
    Include /etc/phpmyadmin/apache.conf
    ```
- Restart apache
    ```
    sudo /etc/init.d/apache2 restart
    ```

**Comment by ToddKopriva** [comment]
@hkiame , it seems that you have a clear idea of what you think should be added. Please, feel free to create a pull request to make the changes yourself. We welcome such contributions.

**Comment by hkiame** [comment]
> @hkiame , it seems that you have a clear idea of what you think should be added. Please, feel free to create a pull request to make the changes yourself. We welcome such contributions.
> 
> Of course, if you'd rather not make the change yourself, just say so and we can look into it.

Awesome. I will work on it. Thanks!

**Comment by ToddKopriva** [comment]
fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1937
