### ISSUE TITLE
ingress host issue is coming

### ISSUE THREAD

**Issue by ashutoshkr73** [GoogleCloudPlatform/community#1926]
- [
 ashutoshkumar@Ashutoshs-MacBook-Pro helm-lt % kubectl apply -f ingress.yaml -n locust
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
The Ingress "ingress-resource" is invalid: spec.rules[0].host: Invalid value: "${NGINX_INGRESS_IP}.nip.io": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]

**Comment by ToddKopriva** [comment]
@ashutoshkr73 , is this intended to be a report of an issue with a document in this repository? If so, which one?

**Comment by ToddKopriva** [comment]
@ashutoshkr73 , I'm closing this issue now because I don't think that we have enough information to move forward. Feel free to re-open this when you can provide more details, including what document you're reporting about.
