### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform: default project for gsutil

### ISSUE THREAD

**Issue by miketruty** [GoogleCloudPlatform/community#193]
I ran into the problem with TF_BACKEND_BUCKET.  Seems you have fixed this but not merged it.

I also ran into a problem with gsutil mb failing.  I was running the commands in my cloud shell.

Seems --set-as-default sets core.project but not project (which is picked up by gsutil).  So 2 fixes seem to work fine:
a) gsutil mb -p ${TF_ADMIN} gs://${TF_ADMIN}
b) gcloud config set project ${TF_ADMIN}

I chose a).

**Comment by jmdobry** [comment]
Fixed by #191 and #194
