### ISSUE TITLE
Issue with tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by AthulMuralidhar** [GoogleCloudPlatform/community#1942]
the manifest and the related resources are not up to date. I am a beginner in this so i don't have the required knowledge to edit / update the page. Hopefully someone comes along and does it so that noobs like me can learn.

thanks!

**Comment by ameer00** [comment]
@AthulMuralidhar . Thanks for the feedback. You can simply fork this repo, make the updates in your fork and create a PR. And send in your updates that way. Myself and a few others can them review and approve it. Please let me know if that works for you.
