### ISSUE TITLE
Fluent Bit for GKE logs not working when workload identity activated

### ISSUE THREAD

**Issue by jrdi** [GoogleCloudPlatform/community#1949]
I've been following the "Customizing Fluent Bit for Google Kubernetes Engine logs" tutorial to customize a FluentBit parser on my GKE production cluster.

Everything works as expected when executing the code from the example. Playing with the dummy cluster, and customizing the logs works nicely.

The problem comes when I try to apply the exact same configuration to an already existing cluster that has the Workload Identity option activated.

![image (1)](https://user-images.githubusercontent.com/67608/134960575-cb5f1f31-389d-49da-bde5-fedc11381caa.png)

By changing FluentBit output to stdout looks like everything is working but submitting to stackdriver is stuck. I tried to debug a bit but the only think I was able to see is that is getting 403 responses but I wasn't able to get more information about the error.

Since 403 sounds like permission error I tried to solve it following the next steps with no success:

1. I created a service account in GCP and bound it to the GKE, as I usually do

```bash
gcloud iam service-accounts add-iam-policy-binding \
  --project=$PROJECT_ID \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT_ID.svc.id.goog[logging/fluent-bit]" \
  fluent-bit@$PROJECT_ID.iam.gserviceaccount.com
```

2. and gave permissions to the GCP service account

<img width="358" alt="image" src="https://user-images.githubusercontent.com/67608/134960943-31d328b5-4957-4e60-95ea-51d6eee3d4d4.png">

I should be missing something but I cannot figure out what it is. Does anybody has experienced the same issue?

PS: Worth mentioning that if I disable the Workload Identity everything starts working as expected.

**Comment by ToddKopriva** [comment]
@xiangshen-dk , can you take a look at this issue about a document that you worked on?

**Comment by jrdi** [comment]
I managed to make it work by activating `hostNetwork: true` to bypass Workload Identity. I get the idea from here: https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/issues/17#issuecomment-825872626

I won't consider this a fix since it's been just try and error until I managed to have everything working 🤷‍♂️

**Comment by jrdi** [comment]
I managed to make it work by activating `hostNetwork: true` to bypass Workload Identity. I get the idea from here: https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/issues/17#issuecomment-825872626

I won't consider this a fix since it's been just "try and error" until I managed to have everything working 🤷‍♂️

**Comment by xiangshen-dk** [comment]
@jrdi:
You can use `hostNetwork: true` as a workaround. If you do that, you probably also want to set `dnsPolicy: ClusterFirstWithHostNet`. As you mentioned, it bypasses workload identity.

It should also work to use workload identity. I have tried it and verified in my testing cluster without problems. Please make sure you follow the steps in the [doc](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to), and configurations such as the IAM binding, annotation in the corresponding namespace are created successfully.

**Comment by jrdi** [comment]
Thank you @xiangshen-dk!

It will be great if you can share the steps you followed. It should be a matter of assigning the right roles and I'm pretty sure that I was missing some important one 🙁

**Comment by xiangshen-dk** [comment]
@jrdi, you can find the commands I used at:
https://gist.github.com/xiangshen-dk/55a4004876b30e44a7050fea166d6c15

**Comment by jrdi** [comment]
@xiangshen-dk now it's working, thanks!

**Comment by ToddKopriva** [comment]
Thanks for confirming, @jrdi .

**Comment by ToddKopriva** [comment]
@xiangshen-dk , should this issue report stay open? Is there a need for a change?

**Comment by xiangshen-dk** [comment]
@ToddKopriva There is no change needed. It can be closed. Thanks!
