### ISSUE TITLE
Tutorial Request: FTP to Google Cloud Storage

### ISSUE THREAD

**Issue by jankrynauw** [GoogleCloudPlatform/community#195]
How could one use cloud functions to copy a file from a particular ftps site to Google Cloud Storage.

We currently have an App Engine (Flex python environment) setup to do this, but it would be ideal to have this functionality setup using Cloud Functions

**Comment by ToddKopriva** [comment]
It looks like there's a tutorial here to do this:
https://medium.com/@Tim_Ebbers/import-a-file-to-gcp-cloud-storage-using-cloud-functions-9cf81db353dc
