### ISSUE TITLE
Deploy OWASP Dependency-Track to Google Cloud - integration with Google Identity Platform 

### ISSUE THREAD

**Issue by plech-sec** [GoogleCloudPlatform/community#1952]
Hi, 
I would like to implement Dependency-Track in GCP, according to this tutorial - https://cloud.google.com/community/tutorials/deploy-dependency-track 
Can Dependency-Track in GCP be integrated with the Google Identity platform as identity provisioner ?
Are the integration rules similar to, for example, KeyCloak?  

Thank you.

**Comment by ToddKopriva** [comment]
@dedickinson , can you help with these questions about a document that you contributed?

**Comment by dedickinson** [comment]
Hiya - I don't think this will work with [Cloud Identity Platform (CIP)](https://cloud.google.com/identity-platform). Whilst CIP can connect to an OIDC provider I don't believe CIP also presents itself as a provider. @plech-sec I see that that KeyCloak config example is provided in the [OpenID Connect Configuration](https://docs.dependencytrack.org/getting-started/openidconnect-configuration/) for Dependency Track but I can't locate similar attributes for CIP in the Google Cloud documentation. Sorry, I'd love to have given a more positive answer (and am always happy to be corrected).

**Comment by ToddKopriva** [comment]
It seems that this conversation has finished, so I'll close this.
