### ISSUE TITLE
Tutorial on Docker networking

### ISSUE THREAD

**Issue by jenildesai25** [GoogleCloudPlatform/community#1958]
I have been trying to find a tutorial on how the docker network works internally. I could not find a resource with an example. Can someone please provide me with some guidance?

**Comment by aghahasaan** [comment]
It depends on your environment/operating system/distribution and other factors but for the most part Docker does not necessarily interfere with your host network's environment and instead creates a Virtual Bridge (or LAN Network) inside the instance/container/physical host or what have you and then assigns each container you start a Virtual Ethernet Port (and address) as you go along.  So basically whether you run Docker on your local host or any Cloud environment including GCP it is the same thing from Network point of view. You can define subnets and IP addresses within Docker and you should refer to their official documentation along with basic Networking (Bridge functionality and Virtual Ethernet features of Linux Systems). Good luck! and this is my personal view I am not an expert or represent GCP!

**Comment by ToddKopriva** [comment]
If you still have questions, I recommend bringing them to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
