### ISSUE TITLE
Tutorial Request: Kong API with Cassandra DB Cluster on Google Container Platform

### ISSUE THREAD

**Issue by rasekar2000** [GoogleCloudPlatform/community#197]
Cassandra DB with Cluster on Alpine OS - Docker , preferably on multi data center deployment
Kong API Gateway Cluster on Alpine OS - Docker, connecting to the earlier shared Cassandra DB Cluster.
Both can run on the same Kubernetes Cluster

**Comment by ToddKopriva** [comment]
closing outdated tutorial requests
