### ISSUE TITLE
Issue with tutorials/cicd-cloud-run-github-actions/index.md

### ISSUE THREAD

**Issue by RafaelZasas** [GoogleCloudPlatform/community#1970]
Is this still valid documentation? 
The [Google GitHub Actions](https://github.com/google-github-actions/deploy-cloudrun) Page for Cloud Run says to migrate to `deploy-cloudrun` however it also mentions that this workflow will not allow to set configurations like allow unauthenticated requests.

**Comment by ToddKopriva** [comment]
@leozz37 , can you answer this question about a document that you contributed?
