### ISSUE TITLE
Issue with tutorials/managing-gcp-projects-with-terraform/index.md

### ISSUE THREAD

**Issue by ivoilic** [GoogleCloudPlatform/community#1971]
This tutorial is missing a step which would allow the reader to see the created project in their dashboard:

```terraform
variable "owner" {}

resource "google_project_iam_member" "project" {
  project = google_project.project.project_id
  role    = "roles/owner"
  member  = "user:${var.owner}"
}
```

This would also make it harder for the reader to accidentally create "ghost" projects they don't know exist if they don't complete the tutorial and delete all Terraform resources. I did this myself and wasn't sure until I found the project listed under my billing account but nowhere else.

**Comment by ToddKopriva** [comment]
Thanks. Feel free to submit a pull request to fix this.

**Comment by ToddKopriva** [comment]
The document has been archived.

I recommend using the documentation on the HashiCorp site for current instructions:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project
