### ISSUE TITLE
Invalid parameter autoscalingAlgorithm  in tutorials/schedule-dataflow-jobs-with-cloud-scheduler/index.md

### ISSUE THREAD

**Issue by octopop** [GoogleCloudPlatform/community#1972]
Issue Description

The tutorial has sample code for Terraform with the following block that defines the body of the API call to start a dataflow job:

`# need to encode the string
body = base64encode(<<-EOT
{
      "jobName": "test-cloud-scheduler",
      "parameters": {
        "region": "${var.region}",
        "autoscalingAlgorithm": "THROUGHPUT_BASED",
      },
      "environment": {
        "maxWorkers": "10",
        "tempLocation": "gs://${var.bucket}/temp",
        "zone": "${var.region}-a"
      }
    }
EOT`

This does not work and leads to `INVALID_ARGUMENT` with HTTP 400. I found that the culprit is the `autoscalingAlgorithm` parameter. I was unable to find this parameter at the official REST API spec as listed here: https://cloud.google.com/dataflow/docs/reference/rest/v1b3/RuntimeEnvironment

**Comment by ToddKopriva** [comment]
Thanks for the report, @octopop .

@zhongchen , can you take a look at this report of an issue with a document that you contributed?

**Comment by ToddKopriva** [comment]
unpublishing document, so closing this issue
