### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by mackgorski** [GoogleCloudPlatform/community#1978]
When I use wp-cli to update plugins I get an error on deployment after updating plugins where it says that my project has too many files and the limit is 10K :( before the update, it was deployed successfully not sure why I cannot deploy after updating plugins. The tutorial should cover this and some best practices for how many plugins can be used with WP on App Engine or how to serve plugins directory from e.g., GCS bucket so that this can be resolved.

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
