### ISSUE TITLE
Issue with tutorials/setting-up-postgres.md and tutorials/setting-up-lamp.md

### ISSUE THREAD

**Issue by itsgarimagoogle** [GoogleCloudPlatform/community#1981]
The "Create new VM" Cloud console page has been updated recently. Related steps in the following documents need to be updated:

https://cloud.google.com/community/tutorials/setting-up-lamp
https://cloud.google.com/community/tutorials/setting-up-postgres

**Comment by ToddKopriva** [comment]
@davide-zanon fixed this issue with pull requests #1984 and #1985 .
