### ISSUE TITLE
Lack of permissions to verify if a step if still valid per the new UI 

### ISSUE THREAD

**Issue by davide-zanon** [GoogleCloudPlatform/community#1987]
I'm unable to verify if this step is still valid for the new UI (see [Issue#1981](https://github.com/GoogleCloudPlatform/community/issues/1981)). 

https://cloud.google.com/community/tutorials/setting-up-lamp

**Comment by ToddKopriva** [comment]
@davide-zanon , please give more detail about exactly what you tried and exactly what is failing. What permission are you lacking?

@xiangshen-dk , you've done a lot of work on this document recently, so I'm hoping that you can help Davide to understand whatever he needs to understand to move forward with his testing of this document:
https://cloud.google.com/community/tutorials/setting-up-lamp

**Comment by davide-zanon** [comment]
@xiangshen-dk I need permission to verify the following step: https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/setting-up-lamp/index.md?plain=1#L293

Alternatively, could you instead tell me if that steps is still valid or has changed?

**Comment by xiangshen-dk** [comment]
@davide-zanon That step assumes you are the owner of the project, or you just create the project for the tutorial. Otherwise, you will not have permission to delete it. In most of our tutorials, we suggest that anyone who tries the tutorial create a new project and shut it down when it's done.

**Comment by davide-zanon** [comment]
@xiangshen-dk Thank you for your reply! The step is unchanged from the previous version. Thus, we can close this issue.
