### ISSUE TITLE
Issue with tutorials/run-wordpress-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by jpswade** [GoogleCloudPlatform/community#2008]
This tutorial suggests that you can simply deploy an existing wordpress application, however, you'll likely get this error:

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This deployment has too many files. New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to 10000
      files for this app.
    field: version.deployment.files[...]
```

If your application has over 10k of files, then it simply will not deploy. It would be useful to know this at the beginning of the tutorial, rather than at the end.

**Comment by ToddKopriva** [comment]
Thanks for the feedback, @jpswade .

@bshaffer , can you look into adding some information about this limitation  early in the document?

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
