### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by deprosun** [GoogleCloudPlatform/community#2009]
The step with ssh does not work

---- ISSUE 1
```bash
ssh `terraform output ip`
ssh: Could not resolve hostname "35.203.191.59": nodename nor servname provided, or not known
```

I had to do 
```
gcloud compute ssh --project=projectId --zone=us-west1-a instanceNAME
```

---- ISSUE 2

the firewall tf code doesn't work.
```
resource "google_compute_firewall" "default" {
 name    = "mera-project-bhai-firewall"
 network = "default"

 allow {
   protocol = "tcp"
   ports    = ["5000"]
 }
}
```
 Following is the error

```
* one of source_tags, source_ranges, or source_service_accounts must be defined
```

![image](https://user-images.githubusercontent.com/5571798/146214273-2426f582-5e71-4753-9ab2-cb76840e1385.png)

**Comment by ToddKopriva** [comment]
Thanks, @deprosun . I'll look into this.

**Comment by ToddKopriva** [comment]
@chrisst , could you take a look at this issue regarding a tutorial that you submitted?

**Comment by ToddKopriva** [comment]
We've updated this document and moved it here:
https://cloud.google.com/docs/terraform/get-started-with-terraform
