### ISSUE TITLE
Feature request regarding tutorials/nginx-ingress-gke/index.md

### ISSUE THREAD

**Issue by kostadin-kar** [GoogleCloudPlatform/community#2013]
I like how well written this document is. 
One suggestion would be for an expert with GKE to extend this tutorial by including the steps necessary for a private GKE cluster, if it is possible.
Thanks!

**Comment by ToddKopriva** [comment]
Thanks for the feedback, @kostadin-kar .

@ameer00 , I want to make sure that you see this feedback.

**Comment by ToddKopriva** [comment]
I'll publish the updated document soon. Thanks for the update, @ameer00 . Thanks for the request, @kostadin-kar .
