### ISSUE TITLE
Issue with tutorials/cicd-cloud-run-github-actions/index.md

### ISSUE THREAD

**Issue by tiagostutz** [GoogleCloudPlatform/community#2018]
Hi folks! 👋🏻 

The provided YAML example has `GoogleCloudPlatform/github-actions/setup-gcloud@master` in the Login step, which yields to 
```
Repository not found : googlecloudplatform/github-actions
```
Doing some research I found that the current working action is `google-github-actions/setup-gcloud@master`

Maybe could update the tutorial? I could send a PR for that's the case

**Comment by ToddKopriva** [comment]
Thanks for the report, @tiagostutz . Please, feel free to submit a pull request with the fix.

**Comment by tiagostutz** [comment]
Nice, on my way. Thanks!
