### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by ryanmark1867** [GoogleCloudPlatform/community#2024]
Issue Description - the tutorial is great, but the step "Open port 5000 on the instance"

resource "google_compute_firewall" "default" {
 name    = "flask-app-firewall"
 network = "default"

 allow {
   protocol = "tcp"
   ports    = ["5000"]
 }
}

generates the following error with terraform plan: 

│ Error: 1 error occurred:
│       * one of source_tags, source_ranges, or source_service_accounts must be defined
│
│
│
│   with google_compute_firewall.default,
│   on main.tf line 48, in resource "google_compute_firewall" "default":
│   48: resource "google_compute_firewall" "default"

To get around this, need to add source_tags = ["mynetwork"] to the resource definition:

resource "google_compute_firewall" "default" {
 name    = "flask-app-firewall"
 network = "default"

 allow {
   protocol = "tcp"
   ports    = ["5000"]
 }
 source_tags = ["mynetwork"]
}

With this change the terraform plan issue goes away.

**Comment by ToddKopriva** [comment]
@ryanmark1867 , thanks for the report.

Feel free to submit a pull request to fix the issue. If you do, then I'll review and merge it.

**Comment by ToddKopriva** [comment]
fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2026
