### ISSUE TITLE
Issue with tutorials/run-symfony-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by Doctorrr** [GoogleCloudPlatform/community#2030]
app.yaml link is broken for now

actual URL: https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/symfony-framework/app.yaml

**Comment by ToddKopriva** [comment]
Thanks for the report, @Doctorrr . 

Feel free to submit a pull request to fix this. If you do, then I'll review and merge it. If you don't, then I'll have a look at fixing it myself.

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
