### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md - Laravel Migrations

### ISSUE THREAD

**Issue by Stoyvo** [GoogleCloudPlatform/community#2038]
This tutorial is great, however it misses a critical part of a Laravel application development lifecycle. You will always use `php artisan migrate` to perform database changes in your deployment pipeline.

Will make a PR if I figure it out.

**Comment by ToddKopriva** [comment]
Thanks, @Stoyvo . I assigned this to you because you indicated that you might make a pull request to address this. Let me know if you choose to not do this.

**Comment by ToddKopriva** [comment]
@bshaffer , I added you because you are the original author.

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
