### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by evilsysadmin** [GoogleCloudPlatform/community#2040]
hey, just a comment

on the firewall rule, you say to add

 source_tags = ["mynetwork"]

but that wont work ,as gcp in no way knows what "mynetwork" is.  

Hence the way its now, you cannot access the flask app externally.

Considering this tutorial is for testing purposes, i think its easier to setup that like this 

 source_ranges = ["0.0.0.0/0"] or  source_ranges = ["your external public ip, cidr format"]

**Comment by ToddKopriva** [comment]
We've updated this document and moved it here:
https://cloud.google.com/docs/terraform/get-started-with-terraform
