### ISSUE TITLE
Tutorial Request: Typescript

### ISSUE THREAD

**Issue by yonathan06** [GoogleCloudPlatform/community#205]
Hi all,

For now all I see are tutorials and samples of using Typescript for the front-end assets
I think it will be really good to have the ability to use Typescript to write the server (helps a lot on big projects)
I did a little research, and all I managed is to process the .ts file into .js files before deploying (with grunt)
The only problem it with having the grunt watcher when running the server on localhost (without opening two terminals)

Is there a working boilerplate/tutorial for that?

Thank you all

**Comment by ToddKopriva** [comment]
I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
