### ISSUE TITLE
npm instead mof Yarn

### ISSUE THREAD

**Issue by Gyekye** [GoogleCloudPlatform/community#2085]
My project uses npm instead of yarn, should I still use RUN Yarn in the Dockerfile ?

**Comment by ToddKopriva** [comment]
Are you asking about a specific document or example, @Gyekye ?

**Comment by Gyekye** [comment]
In your deploy react to cloud run , the Dockerfile configuration used Yarn, but my project uses npm for package management,  should I just change the Yarn to Npm in the Dockerfile

**Comment by ToddKopriva** [comment]
@FelipeLujan , can you help to answer this question about a tutorial that you contributed?

https://cloud.google.com/community/tutorials/deploy-react-nginx-cloud-run
