### ISSUE TITLE
Issue with tutorials/serverless-vpc-access-private-mongodb-atlas/index.md

### ISSUE THREAD

**Issue by rbarrett-scope** [GoogleCloudPlatform/community#2087]
Issue Description

This tutorial is about setting up VPC connection from GCP to Atlas, but the example connection string format is incorrect for a VPC connection. To use a VPC connection string, as per: https://docs.atlas.mongodb.com/reference/faq/connection-changes/#std-label-connstring-private the connection string must have the `-pri` suffix in the hostname portion of the URL, otherwise it will resolve to a public IP. If it resolves to a public IP it will either not work at all, or work but bypass the VPC connection, depending on other routing and firewall rules.

This:
`mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER_NAME].[SUBDOMAIN].mongodb.net/`

should be:

`mongodb+srv://[USERNAME]:[PASSWORD]@[CLUSTER_NAME]-pri.[SUBDOMAIN].mongodb.net/`

And it should probably reference the Atlas documentation I linked above.

**Comment by ToddKopriva** [comment]
@russStarr , could you take a look ar this suggestion regarding a document that you contributed?

**Comment by russStarr** [comment]
Thank you @rbarrett-scope for calling this out! I've submitted a fix and we'll see the tutorial page get updated soon.

**Comment by rbarrett-scope** [comment]
Thanks for the prompt response.
