### ISSUE TITLE
Cloud function for receiving push notification from google calendar 

### ISSUE THREAD

**Issue by kingman** [GoogleCloudPlatform/community#210]
Hi, I'm trying to use cloud function as receiver of google calendar push notifications, and then do something else on each received notification. What I'm stuck right now is to find a proper way to get my deployed cloud function domain verified as that I own the domain. Because it's the first step for Register the domain of your receiving URL, on google calendar api side. If you could provide me guidance/ tutorial on best practice on how to get my cloud function verified as domain for receiving the calendar push notifications I would be really grateful.
Thanks in advance!

**Comment by jmdobry** [comment]
@jasonpolites Any hint on using the cloudfunctions.net domain as a verifieid domain?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
