### ISSUE TITLE
Issue with tutorials/run-laravel-on-appengine-standard/index.md

### ISSUE THREAD

**Issue by afcsagir** [GoogleCloudPlatform/community#2100]
Step #2 - "build": In PackageManifest.php line 177:
Step #2 - "build":                                                                           
Step #2 - "build":   The /workspace/bootstrap/cache directory must be present and writable.  
Step #2 - "build":

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
