### ISSUE TITLE
Issue with tutorials/exposing-aspnet-webapi-using-dotnetcore-with-cloud-endpoints/index.md, is outdated

### ISSUE THREAD

**Issue by MartinCastellon** [GoogleCloudPlatform/community#2109]
This article is only useful for .NET Core 2.0. When I try to use .NET 6, it won't work. In order to reproduce the error, just create .NET 6 Web AP and try to follow the same steps. It will break on step 5. 

There should be more recent articles targeting.NET 6

**Comment by ToddKopriva** [comment]
@simonz130 , could you take a look at this request about a document that you contributed?

**Comment by simonz130** [comment]
@amanda-tarafa

**Comment by MartinCastellon** [comment]
Thanks, @simonz130 . Will we get a tutorial for NET6.0?  That would be amazing 💯. I ended up using a container with Cloud Run to deploy my project. But would be great to get to try Cloud Endpoints.

**Comment by ToddKopriva** [comment]
> I think we should deprecate this tutorial - I don't think it's still supported on .NET 6.0 with the endpoints. Adding Amanda who might look into it more.

Thanks, @simonz130 .

I'll take care of archiving the existing tutorial.

**Comment by ToddKopriva** [comment]
I switched this to a "tutorial request" rather than "update needed" on the assumption that the new document will involve more than a simple bug fix.

**Comment by meteatamel** [comment]
.NET 6 Web API supports Open API 3.1 by default. Unfortunately, Cloud Endpoints only supports Open API 2.0 right now. I don't think we can create a tutorial with .NET 6 until Cloud Endpoints supports Open API 3.X

**Comment by ToddKopriva** [comment]
Thanks, @meteatamel . I'm closing this for now, then.
