### ISSUE TITLE
Unable to open D-track UI

### ISSUE THREAD

**Issue by mrrobothack1** [GoogleCloudPlatform/community#2124]
I have installed everything in Google cloud and have ingress also. But in the documentation its not visible how to open up the UI.

➜  frontend git:(master) ✗ kubectl get ing
NAME                            CLASS    HOSTS   ADDRESS          PORTS   AGE
dependency-track-frontend-ing   <none>   *       131.212.30.241   80      11m

https://cloud.google.com/community/tutorials/deploy-dependency-track

Is there any issue reported regarding this one?

**Comment by ToddKopriva** [comment]
@dedickinson , can you help to answer this question about a document that you contributed?

**Comment by dedickinson** [comment]
You should be able to see the user interface by browsing to the subdomain you configured in the "Configure your domains" section. My placeholder domain was dt.example.com so https://dt.example.com would work in that example. This is also covered in the "Enable services and set up the environment" section.

**Comment by mrrobothack1** [comment]
okay, thanks for that but I am getting an error that says failed to determine the availability of OpenID connect.

and also 

login:1 Access to XMLHttpRequest at 'https://dependency-track-ip-api.tets.tech/api/v1/user/login' from origin 'https://dependency-track-ip-ui.test.tech' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mrrobothack1** [comment]
I have solved this issue, but adding cors in ingress

    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dependency-track-ip-ui.test.tech"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dependency-track-ip-api.test.tech"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"

If anyone faces issues like CORS can use it this way.

Thanks @dedickinson for the help
