### ISSUE TITLE
Issue with tutorials/bigquery-from-dbeaver-odbc/index.md

### ISSUE THREAD

**Issue by EmaGianna** [GoogleCloudPlatform/community#2125]
https://cloud.google.com/community/tutorials/bigquery-from-dbeaver-odbc This explanation use a alder version of dbeaver, right now dbeaver show us a bigquery option to connect.
If you have time, maybe someone could be update this tutorial.

thanks!

**Comment by ToddKopriva** [comment]
@julzsam , could you take a look at this request for an update of a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
removed outdated tutorial:
https://github.com/GoogleCloudPlatform/community/pull/2311
