### ISSUE TITLE
tutorials/gcds-use-cases-common-and-complex/index.md: Replace joonix.net example

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/community#2128]
The joonix.net domain isn't meant to be used in public documentation. Please replace it with a different domain that follows Google's guidelines: https://developers.google.com/style/examples#example-domain-names

This change requires a number of screenshots to be updated as well.

**Comment by ToddKopriva** [comment]
@akaashr , please make the change that is requested here.

**Comment by akaashr** [comment]
ack. I'll prioritize updating the doc and screenshots accordingly.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
