### ISSUE TITLE
Issue with tutorials/stackdriver-monitor-slow-query-mysql/index.md

### ISSUE THREAD

**Issue by drzewinski** [GoogleCloudPlatform/community#2129]
The result of this tutorial is different from what is indicated. It is impossible to see the entire query as presented in the tutoria, even though I've created the label as indicated...

**Comment by ToddKopriva** [comment]
@jwlee98 , could you take a look at this report about a tutorial that you worked on?

**Comment by ToddKopriva** [comment]
archived the outdated tutorial
