### ISSUE TITLE
Any interest in updating the used version of Eclipse/Californium in tutorials/cloud-iot-coap-proxy?

### ISSUE THREAD

**Issue by boaks** [GoogleCloudPlatform/community#2134]
Long time, since I put a [look](https://github.com/GoogleCloudPlatform/community/pull/690) on that.

[Eclipse/Californium](https://github.com/eclipse/californium) reached version 3.3.1.
Many bug-fixes, some vulnerability-fixes, and great functional improvements.

[Eclipse/Californium](https://github.com/eclipse/californium) comes with one of the first [RFC9146 (to be)](https://www.rfc-editor.org/rfc/authors/rfc9146.html) implementations. [mbedtls](https://github.com/ARMmbed/mbedtls/pull/5061) is currently working on supporting it, and I implemented it as well in [Eclipse/TinyDtls](https://github.com/eclipse/tinydtls/tree/feature/connection_id) as experimental feature (it supports only the client side, but still ideal as device counterpart for Californium).

Setting up a [(cloud) VM](https://github.com/eclipse/californium/tree/master/demo-apps/cf-unix-setup) becomes in the meantime easy. Using it with [k8s](https://github.com/eclipse/californium/wiki/Californium-as-k8s-service) works also without too much pain.

Features as [DTLS - graceful restart](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server#benchmarks---dtls-graceful-restart) or [UDP - DTLS CID LoadBalancer](https://github.com/eclipse/californium/tree/master/demo-apps/cf-extplugtest-server#built-in-support-for-dtls-connection-id-cluster-using-basic-udp-load-balancers) makes CoAP/DTLS CID unique and powerful. With that, efficient, reliable, scalable, real e2e secure device communication becomes true. You can really get "20 for 2" (means, 20 IP messages with https request will be 2 IP messages with CoAP/DTLS CID).

So, if there is any interest by others, let me know. I'm still not able/allowed, to contribute it by my own, but I'm able to help others to do so.

**Comment by ToddKopriva** [comment]
@ptone , could you take a look at this question about a possible update to a document that you contributed?

**Comment by hongalex** [comment]
Unfortunately, Cloud IoT Core is being discontinued on August 16, 2023. For those interested, ClearBlade (a GCP partner) is going to be offering a [1-click migration path](https://www.clearblade.com/wp-content/uploads/2022/08/ClearBlade-Google-IoT-Core-Migration_Website.pdf).

**Comment by ToddKopriva** [comment]
Thanks for the update, Alex.

**Comment by boaks** [comment]
Thanks! We will see, if ClearBlade has any interest in supporting CoAP.

For [Eclipse/Californium](https://github.com/eclipse/californium) I consider, that using it directly on a vm or k8s provides the most benefit. I currently started to develop a [simple service](https://github.com/boaks/californium/tree/add_cloud_demo_server/demo-apps/cf-cloud-demo-server) and a [modem client](https://github.com/boaks/zephyr-coaps-client). Using both enables to build battery powered mobile modem clients, which runs pretty long.

```
coap-client coap://californium.eclipseprojects.io/echo/cali.352656100985434
2043081 s, Thingy:91 v0.3, 0*564, 1*2, 2*0, 3*0, failures 1
3891 mV 59% battery
RSSI q,p: 255,255
Network: NB-IoT
Released: 53 ms
```
 
Three weeks, 1 message per hour, 59% battery left. A real device, not just paper.
