### ISSUE TITLE
Using Terraform with GCP to Automate Project creation

### ISSUE THREAD

**Issue by sokpara01** [GoogleCloudPlatform/community#2137]
Hello Guys, 

I need help in understanding how I can automate the creation of project and IAM users on GCP. I have tried many of the user guides and I get stuck every time.

A step-by-step guide with someone who has done it before will be much appreciated.

Regards,

Samson

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
