### ISSUE TITLE
Issue with tutorials/using-scheduler-invoke-private-functions-oidc/index.md

### ISSUE THREAD

**Issue by mvladoi** [GoogleCloudPlatform/community#2146]
There is no need to deploy the cloud function with the identity of the service account. The service account has to be linked only to the cloud scheduler job

**Comment by ToddKopriva** [comment]
@dinagraves , could you have a look at this issue about a document that you worked on?

**Comment by dinagraves** [comment]
@glasnt Tagging Katie since I'm on rotation working in a different area.

**Comment by glasnt** [comment]
Hi @mvladoi. In the current configuration, using the created service account means that the Cloud Function isn't using the default service account, which has too many permissions for this use case. 

While the Cloud Function doesn't need the invoker permission, using this custom account means that the function doesn't accidentally get (at time of writing) 4,800+ additional permissions it doesn't require (as the default service account for Cloud Functions has the Editor role).

**Comment by ToddKopriva** [comment]
Thanks for the explanation, @glasnt .
