### ISSUE TITLE
community/tutorials/https-load-balancing-nginx/ suggestion

### ISSUE THREAD

**Issue by JimTravis** [GoogleCloudPlatform/community#215]
Thanks for this very useful tutorial :- )  4-5 stars, but nevertheless I set 3 stars just so I would be able to write this:
  Why didn't you include instructions about creating an instance group that always keeps the Nginx server alive? Like you did for the HAProxy load balancing tutorial? If there's any reason you didn't mention [an-instance-group-with-only-the-nginx-server-as-a-member] other than keeping-the-tutorial-short, it'd be good to know I think.  And if the reason is to keep-things-short-and-simple — then I suggest that you tell people to have a look at the HAProxy tutorial too, so they'll notice that they can indeed onfigure Google Cloud to ensure the Nginx server & process stay alive forever

You could just add a link in the "Check out other possible load balancing solutions" section in the screenshot?

**Comment by jmdobry** [comment]
@JimTravis Is this your feedback, or feedback from a Google Cloud user?

**Comment by JimTravis** [comment]
From a user.

**Comment by tswast** [comment]
(not my tutorial) The author tag says it's @tzero's

**Comment by ToddKopriva** [comment]
@tzero , can you have a look at this issue?
