### ISSUE TITLE
Issue with tutorials/nodejs-mongodb-on-appengine.md

### ISSUE THREAD

**Issue by rodneyallanprice** [GoogleCloudPlatform/community#2151]
The sample code in this example appears to have some copy and paste errors.   Several blocks of code are duplicated and the code crashes when run. 

I was able to get it working by cutting out much of the code.   See the code below:

'use strict';

const mongodb = require('mongodb');
const http = require('http');
const nconf = require('nconf');

// Read in keys and secrets. Using nconf use can set secrets via
// environment variables, command-line arguments, or a keys.json file.
nconf.argv().env().file('keys.json');

// Connect to a MongoDB server provisioned over at
// MongoLab.  See the README for more info.

const user = nconf.get('mongoUser');
const pass = nconf.get('mongoPass');
const host = nconf.get('mongoHost');
const port = nconf.get('mongoPort');

let uri = `mongodb+srv://${user}:${pass}@${host}`;
if (nconf.get('mongoDatabase')) {
    uri = `${uri}/${nconf.get('mongoDatabase')}`;
}
console.log(uri);

// Create a simple little server.
http.createServer((req, res) => {
    if (req.url === '/_ah/health') {
        res.writeHead(200, {
            'Content-Type': 'text/plain'
        });
        res.write('OK');
        res.end();
        return;
    }

    mongodb.MongoClient.connect(uri, { useNewUrlParser: true }, (err, client) => {
        if (err) {
            throw err;
        }

        const db = client.db(nconf.get("mongoDatabase"))
        const collection = db.collection('IPs');

        const ip = {
            address: req.connection.remoteAddress
        };

        collection.insertOne(ip, (err) => {
            if (err) {
                throw err;
            }

            // push out a range
            let iplist = '';
            collection.find().toArray((err, data) => {
                if (err) {
                    throw err;
                }
                data.forEach((ip) => {
                    iplist += `${ip.address}; `;
                });

                res.writeHead(200, {
                    'Content-Type': 'text/plain'
                });
                res.write('IPs:\n');
                res.end(iplist);
            });
        });
    });
}).listen(process.env.PORT || 8080, () => {
    console.log('started web process');
});

**Comment by ToddKopriva** [comment]
Thanks, @rodneyallanprice . You are certainly correct that there are some problems here.

We are in the process of archiving this document because it is out of date, so I'm going to close this issue.
