### ISSUE TITLE
Issue with tutorials/metrics-export-with-mql/index.md

### ISSUE THREAD

**Issue by eda-yuji-10472** [GoogleCloudPlatform/community#2156]
Issue Description

Build didn't work well when python's version was 38. It worked fine when I set it to 37. Attach the log.

---

eda_yuji_10472@eda-test-2:~/work21/community/tutorials/metrics-export-with-mql$ gcloud functions deploy mql_export_metrics \
> --trigger-topic $PUBSUB_TOPIC \
> --runtime python38 \
> --entry-point export_metric_data \
> --service-account=$EXPORT_METRIC_SERVICE_ACCOUNT
Deploying function (may take a while - up to 2 minutes)...⠹                                                                                                                                               
For Cloud Build Logs, visit: https://console.cloud.google.com/cloud-build/builds;region=us-central1/bdfe2f47-ac78-4dd8-8c15-2c9eba5d648d?project=811602934537
Deploying function (may take a while - up to 2 minutes)...failed.                                                                                                                                         
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: ... while.
INFO: pip is looking at multiple versions of pyasn1-modules to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyasn1 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of protobuf to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of googleapis-common-protos to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-resumable-media to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-crc32c to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-cloud-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-cloud-bigquery to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-auth to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of google-api-core to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cffi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cachetools to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 18) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts; Error ID: 0ea8a540
eda_yuji_10472@eda-test-2:~/work21/community/tutorials/metrics-export-with-mql$ gcloud functions deploy mql_export_metrics --trigger-topic $PUBSUB_TOPIC --runtime python37 --entry-point export_metric_data --service-account=$EXPORT_METRIC_SERVICE_ACCOUNT
Deploying function (may take a while - up to 2 minutes)...⠹                                                                                                                                               
For Cloud Build Logs, visit: https://console.cloud.google.com/cloud-build/builds;region=us-central1/e9b7be48-b6b6-4421-8240-84d11b6a5100?project=811602934537
Deploying function (may take a while - up to 2 minutes)...done.                                                                                                                                           
availableMemoryMb: 256
buildId: e9b7be48-b6b6-4421-8240-84d11b6a5100
buildName: projects/811602934537/locations/us-central1/builds/e9b7be48-b6b6-4421-8240-84d11b6a5100
dockerRegistry: CONTAINER_REGISTRY
entryPoint: export_metric_data
eventTrigger:
  eventType: google.pubsub.topic.publish
  failurePolicy: {}
  resource: projects/striped-proxy-187410/topics/mql_metric_export
  service: pubsub.googleapis.com
ingressSettings: ALLOW_ALL
labels:
  deployment-tool: cli-gcloud
name: projects/striped-proxy-187410/locations/us-central1/functions/mql_export_metrics
runtime: python37
serviceAccountEmail: mql-export-metrics@striped-proxy-187410.iam.gserviceaccount.com
sourceUploadUrl: https://storage.googleapis.com/uploads-463359727826.us-central1.cloudfunctions.appspot.com/96d8cb13-7fa9-4edc-9d00-732c162b535b.zip
status: ACTIVE
timeout: 60s
updateTime: '2022-04-19T10:34:37.433Z'
versionId: '2'

---

**Comment by ToddKopriva** [comment]
@xiangshen-dk , could you take a look at this issue regarding one of your contributions?

**Comment by xiangshen-dk** [comment]
Submitted https://github.com/GoogleCloudPlatform/community/pull/2166

**Comment by ToddKopriva** [comment]
Thanks for the fix, @xiangshen-dk .
