### ISSUE TITLE
Issue with tutorials/managing-gcp-projects-with-terraform/index.md

### ISSUE THREAD

**Issue by bigbitbus** [GoogleCloudPlatform/community#2164]
This document is misleading.

When you use a service account of the admin project (like in this document) to create the service project, you end up with a service project which cannot be controlled by the user or the admin project service account - because service accounts are scoped by project. The "project creator" role does not make a service account the "owner" of the created service project.

So this tutorial will create a project that cannot be used.

**Comment by ToddKopriva** [comment]
The document has been archived.

I recommend using the documentation on the HashiCorp site for current instructions:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project
