### ISSUE TITLE
Why the number of nodes parameter is not returned as part of the response while using java client library to list the nodepools in a cluster

### ISSUE THREAD

**Issue by ragul-03** [GoogleCloudPlatform/community#2213]
Hi all,
I'm trying to use the java client library (Container.Projects.Locations.Clusters.NodePools.List request) to list down the nodepools present in the cluster. [https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters.nodePools/list](url)
But, the response does not have the total number of nodes present in that nodepool. Is there any specific reason why it is not returned and is there any other way to get the total number of nodes present in that nodepool.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
