### ISSUE TITLE
Issue with tutorials/dlp-to-datacatalog-tags

### ISSUE THREAD

**Issue by harshdM99** [GoogleCloudPlatform/community#2215]
Thanks for the repo.
Getting this error : "Create Tag Error Message: Cannot find template dlp_email_address@us in storage." while running the steps in GCP virtual machine.

Detailed message : 

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Start: Thu Jun 30 15:16:58 UTC 2022]
Inspect SQL via JDBC V0.1
jdbc:bigquery:****HIDING THIS PART*****
-----------------------------------------
 Start Run ID: 6b2bdb8d-70ca-4207-8ad8-b4e5e0d4ecd3
-----------------------------------------

|
> DLP infoType Profile: [test_bq_dlp][org_facilitate_viral_mindshare_3f54]|
> DLP infoType Profile: [test_bq_dlp][org_productize_mission_critical_systems_d8de]|
> DLP infoType Profile: [test_bq_dlp][org_transform_virtual_action_items_6aa9].................Create Tag Error Message: Cannot find template dlp_email_address@us in storage.
Create Tag Error Message: Cannot find template dlp_mac_address@us in storage.
Create Tag Error Message: Cannot find template dlp_ip_address@us in storage.
Create Tag Error Message: Cannot find template dlp_first_name@us in storage.
.......Create Tag Error Message: Cannot find template dlp_first_name@us in storage.
Create Tag Error Message: Cannot find template dlp_credit_card_number@us in storage.
Create Tag Error Message: Cannot find template dlp_email_address@us in storage.
Create Tag Error Message: Cannot find template dlp_ip_address@us in storage.

-----------------------------------------
 3 tables inspected
 End Run ID: 6b2bdb8d-70ca-4207-8ad8-b4e5e0d4ecd3
-----------------------------------------
[End: Thu Jun 30 15:17:11 UTC 2022]
[Duration:   0 days,   0 hours,   0 minutes,   12 seconds.]

**Comment by harshdM99** [comment]
My teammate did not add admin permissions to the associated service account.
This error is resolved. 
Thank you

**Comment by ToddKopriva** [comment]
@harshdM99 , thank you very much for reporting back with the details.
