### ISSUE TITLE
HTTP requests are sent to GCP before vms fully initialized

### ISSUE THREAD

**Issue by OriAlpha** [GoogleCloudPlatform/community#2218]
I am using GCP vms for my applications. These VMs are connected to instance groups and load balancer, so when there is new request sent from my application. VMs will trigger and start, but the problem is my requests are sent to vm before they are fully initialized. Which makes my requests to fail. So i had gone through web pages and set some parameters like 

- Auto healing - inital delay 
- Cool-down period

But this issue is not 100% cleared, so if any have some more ideas?? 

i was not sure where to post this question because, its confusing with lot of repo. But not native GCP command line repo.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
