### ISSUE TITLE
Update needed for using-slurm-to-host-jupyter-notebooks-review to support v5 slurm-gcp

### ISSUE THREAD

**Issue by jrossthomson** [GoogleCloudPlatform/community#2220]
Update of slurm-gcp from SchedMD make this out of date.

https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/using-slurm-to-host-jupyter-notebooks-review

**Comment by jrossthomson** [comment]
@wkharold

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
