### ISSUE TITLE
connect to big query via vb script using excel macros

### ISSUE THREAD

**Issue by SS1605** [GoogleCloudPlatform/community#2221]

**Comment by ToddKopriva** [comment]
Are you asking a question about how to accomplish the task in the title of this issue?

The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
