### ISSUE TITLE
Issue with tutorials/stackdriver-monitor-slow-query-mysql/index.md

### ISSUE THREAD

**Issue by ns-png** [GoogleCloudPlatform/community#2231]
Issue Description:
The article is outdated, there are no "slow_query_log" "long_query_time" int patch, and you can't find slow log in log part.
Also the no "log view" that panel also changed.

**Comment by ToddKopriva** [comment]
Thanks for the report, @ns-png .

**Comment by XDevice-code** [comment]
a"a"><img src=<marquee>x onerror=alert(7)>
a"><img src=x onerror=alert(7)>

**Comment by XDevice-code** [comment]
Hello

**Comment by ToddKopriva** [comment]
archived outdated tutorial
https://github.com/GoogleCloudPlatform/community/pull/2308
