### ISSUE TITLE
Google Cloud Platform Slack

### ISSUE THREAD

**Issue by travnewmatic** [GoogleCloudPlatform/community#2234]
I joined previously with my work email, but I've changed jobs and went back to join and discovered that I need an @google.com email address to register.

How can I join Google Cloud Platform Slack *without* an @google.com email address?

Thanks!

-Travis

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend trying the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
