### ISSUE TITLE
Issue with tutorials/securing-gcs-static-website/index.md

### ISSUE THREAD

**Issue by petemounce** [GoogleCloudPlatform/community#2239]
## Errors during `npm run build` step.

I'm running on macOS 12 M1.

```
$ npm run build

> build
> node ./bin/build

embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/bigquery-ibis/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/cloud-functions-github-container-builder/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/cloud-iot-firestore-config/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/cloud-functions-sns-pubsub/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/cloud-iot-hybrid/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/delivering-cloud-monitoring-notifications-to-third-party-services/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/dnssec-cloud-dns-domains/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/github-auto-assign-reviewers-cloud-functions/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/gke-less-disruptive-node-upgrades/index.md
embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/pubsub-spring-dedup-messages/index.md
Error: Command failed: embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/github-auto-assign-reviewers-cloud-functions/index.md
/bin/sh: embedmd: command not found

    at ChildProcess.exithandler (node:child_process:410:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'embedmd -w /Users/pete/src/ef/prod/internal-docs-hosting/community/tutorials/github-auto-assign-reviewers-cloud-functions/index.md'
}

...
```

## Possible fix: 

Mention needing github.com/campoy/embedmd (I assume).

Alternatively, just have a static foo.html?

**Comment by petemounce** [comment]
Omitted step in `Build a static website and deploy it to Cloud Storage`

Need to run `npm install --devDependencies` before `npm run build` will work (I now have `embedmd` on my PATH from above debugging)

**Comment by xiangshen-dk** [comment]
Looks like the `npm run build` was not run under the `community/tutorials/securing-gcs-static-website/static-website` directory.

In the tutorial, the following commands are required before `npm run build`. 

### Clone the repository:

git clone https://github.com/GoogleCloudPlatform/community.git

### Go to the tutorial directory:

cd community/tutorials/securing-gcs-static-website/static-website

-----------
Please confirm if the errors still happen after switching directory.

**Comment by petemounce** [comment]
@xiangshen-dk thanks - that was it.

btw - thank you for writing https://github.com/xiangshen-dk/securing-gcs-static-assets-iap. That is what I'm actually trying to do right now (host some private static content using all managed services within GCS) - but unfortunately not yet succeeding. I am eagerly following https://issuetracker.google.com/issues/114133245?pli=1.

I also stumbled across https://github.com/GoogleCloudPlatform/cdn-auth-proxy/ - and while I _also_ found that didn't work (https://github.com/GoogleCloudPlatform/cdn-auth-proxy/issues/1), I did find it easier to follow. I think that is down to how my brain works and the declarative nature of terraform configuration - I found it easier to understand how things related together.

Likewise, https://www.karimarttila.fi/gcp/2022/05/10/gcp-cloud-run-with-iap.html.

If I succeed in combining the two approaches (IAP-to-private-GCS, but via terraform), would a contribution be welcome? Clearly, I don't work for GCP. :)

**Comment by xiangshen-dk** [comment]
@petemounce Thanks for the update! Let us know if you succeed. And any contribution is much welcomed!

**Comment by petemounce** [comment]
Sadly, I didn't succeed. Too hard, so I used private github pages which Just Worked :tm:.

I'll revisit as/when I work on a static site with mixed requirements for authn/z. Our customer facing docs ideally would require Authn for some but not all content, which Github pages does not support.

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
