### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by 7h3h4ckv157** [GoogleCloudPlatform/community#2243]
Hey Team!

Recently I found a potential security issue on the code which I would be eager to share with you. Could you add a SECURITY.md file for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help researchers in the future. 

eg: https://github.com/GoogleCloudPlatform/python-docs-samples/security/policy

Looking forward to hearing from you. 

Regards,

**Comment by ToddKopriva** [comment]
security policy added in PR #2247
