### ISSUE TITLE
"We encourage you to read through the script for the details of what it does." <sigh>

### ISSUE THREAD

**Issue by kbrown** [GoogleCloudPlatform/community#2249]
Or just explain how Cloudrun tits into all of this in the article

**Comment by ToddKopriva** [comment]
@jasonsmithio , this seems to be a somment about this document that you contributed:
https://cloud.google.com/community/tutorials/cloud-run-eventing-kafka

**Comment by jasonsmithio** [comment]
Happy to help. Can you give me more information on what you are looking for?

**Comment by kbrown** [comment]
Most of the the "article is just" see setup.sh -- which is not even linked.  Some explanation of what is going on in the text might be helpful.  more comments below.

**Comment by kbrown** [comment]
The title starts with "Serverless eventing with Cloud Run on Anthos"Serverless eventing"

**Comment by kbrown** [comment]
"AlphaVantage" is not defined.  Why do I need a key?  Clicking..   Oh it's just an artifact of this particular demo and not central to the other tech.  Words would help.

**Comment by kbrown** [comment]
Trying to be helpful, but grumpy today.

**Comment by kbrown** [comment]
What I really was looking for is how I can use Cloud Run as a Kafka consumer, and stumbled upon this article.

**Comment by jasonsmithio** [comment]
Gotcha, this article is dated and many of the examples aren't really valid anymore. I am working on a new one so please stand by while I work on it

**Comment by ToddKopriva** [comment]
closing this issue, since the document that it's about has been archived
