### ISSUE TITLE
content://com.transsion.phoenix.fileprovider/root_path/storage/emulated/0/bugreport-BISON-QP1A.190711.020-2022-06-28-13-11-21.txt

### ISSUE THREAD

**Issue by irmanfauzi33** [GoogleCloudPlatform/community#2253]
comment edited to remove potentially problematic link

**Comment by dbssilva** [comment]
Para que serve essa merda

Em Ter, 13 de set de 2022 12:28, Todd Kopriva ***@***.***>
escreveu:
