### ISSUE TITLE
Issue with tutorials/terraform-asm-mcp.md

### ISSUE THREAD

**Issue by Yuukiko85** [GoogleCloudPlatform/community#2256]
There are version constraint issues, potentially caused by GKE?:

```
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/kubernetes: no available releases match the given constraints 2.6.1, ~> 2.10
╵
```

```
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/google: no available releases match the given constraints >= 2.12.0, ~> 3.45, 3.88.0, < 4.0.0, >=
│ 4.29.0, < 5.0.0
```

It seems to be similar to this, and should be updated so the tutorial runs smoothly.  
https://stackoverflow.com/questions/72319701/provider-hashicorp-google-no-available-releases-match-the-given-constraints

**Comment by ToddKopriva** [comment]
Thanks for the report, @Yuukiko85 .

@alizaidis , could you take a look at this issue about a document that you contributed?

**Comment by ToddKopriva** [comment]
closing this issue because the document has been moved to the archive
