### ISSUE TITLE
Tutorial request: Node.js Microservices Sample

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/community#227]
demo app w/ multiple services for the Node.js flexible environment. Similar to

GoogleCloudPlatform/python-docs-samples#509

**Comment by dgonzalez** [comment]
I will work on this one. It is coming in line with my talk this Thursday on the Dublin Node.js Meetup.

**Comment by ToddKopriva** [comment]
@dgonzalez , did you ever end up working on this?

**Comment by ToddKopriva** [comment]
@dgonzalez , is this still on your radar?
