### ISSUE TITLE
Issue with tutorials/developing-services-with-k8s.md

### ISSUE THREAD

**Issue by chadmcrowell** [GoogleCloudPlatform/community#2281]
Issue Description:

This guide is outdated. The installation instructions fail and the guestbook YAML is not present in the main branch. I suggest updating this article to include the updated installation [here](https://www.telepresence.io/docs/latest/quick-start/), and to update the YAML and place in a separate repo. Thanks!

**Comment by ToddKopriva** [comment]
Thanks for the report, @chadmcrowell .

**Comment by ToddKopriva** [comment]
We've archived the outdated tutorial:
https://github.com/GoogleCloudPlatform/community/pull/2306
