### ISSUE TITLE
Want to get GKE Deployment failed using GCP Logging Query

### ISSUE THREAD

**Issue by Muthiah131998** [GoogleCloudPlatform/community#2294]
we need to get k8S Deployment Failed logs using GCP Logging Query

Tried Below GCP logging Query but not sure how to get failed Deployment logs using this

resource.type="k8s_cluster" AND log_id("cloudaudit.googleapis.com/activity") AND protoPayload.methodName:"deployments"

but also there is a field called protoPayload.response.status.code 
is there any way to get failed deployment logs

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
