### ISSUE TITLE
Issue with tutorials/serverless-grafana-with-iap/index.md

### ISSUE THREAD

**Issue by saimanwong** [GoogleCloudPlatform/community#2316]
### Cloud Run - "The request was not authenticated."

About a week ago, 2022-01-13, I started to experience several failed requests with the following Cloud Run warning logs:

```
The request was not authenticated. 
Either allow unauthenticated invocations or set the proper Authorization header. 
Read more at https://cloud.google.com/run/docs/securing/authenticating 
Additional troubleshooting documentation can be found at: https://cloud.google.com/run/docs/troubleshooting#unauthorized-client
```

For the failed requests, the Grafana panel would indicate a red error in the top left corner saying that the request was not authenticated. I didn't think too much about it because it was still possible to load a dashboard with 10+ panels after a handfull of page refreshes.

However, this week (03), no requests seem to arrive to the Grafana container as a 403 frontend page is immediately returned. And the Cloud Run warning log, mentioned above, appears for every request. The troubleshooting documentation was helpful and tried everything except:

> If the service is meant to be invocable by anyone, [update its IAM settings](https://cloud.google.com/run/docs/securing/managing-access#making_a_service_public) to make the service public.

The purpose was to spin up an instance for internal usage only. In my mind and at that time, the words "anyone" and "public" meant that external users from the internet would be able to invoke the `run.app` instance too. Then I found this page https://cloud.google.com/iap/docs/enabling-cloud-run#configuring_to_limit_access (relatively new page?), which clarified a bit about the ingress and authentication settings. So, granting `allUsers` the Invoker role seemed to do the trick and only invocable by internal clients because the ingress is set to `Internal and Cloud Load Balancing` will deny/drop any request made directly to the Cloud Run instance from the internet.

https://github.com/GoogleCloudPlatform/community/blob/c4a3231800bbf7c23e1427f47ef7189ee6311692/tutorials/serverless-grafana-with-iap/code/main.tf#L52

---

Would it make sense to add one of the following to the `main.tf`?

```terraform
data "google_iam_policy" "noauth" {
  binding {
    role = "roles/run.invoker"
    members = [
      "allUsers",
    ]
  }
}

resource "google_cloud_run_service_iam_policy" "noauth" {
  location    = google_cloud_run_service.default.location
  project     = google_cloud_run_service.default.project
  service     = google_cloud_run_service.default.name

  policy_data = data.google_iam_policy.noauth.policy_data
}
```

or 

```terraform
resource "google_cloud_run_service_iam_member" "allUsers" {
  service  = google_cloud_run_service.default.name
  location = google_cloud_run_service.default.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}
```

The first one may be preferable as it's consistent with this Terraform provider example https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#example-usage---cloud-run-service-noauth

---

Thank you for an awesome tutorial!

**Comment by cgrotz** [comment]
Hi @saimanwong, thanks for this. Yes there was a  change in the way that IAP with Cloud Run works (still in preview right now), and your proposal ist the right way to fix it. I'll raise a PR for it.

**Comment by ToddKopriva** [comment]
closing as fixed with the PR from @cgrotz
