### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-strongswan/index.md

### ISSUE THREAD

**Issue by jeffdroibnson** [GoogleCloudPlatform/community#2317]
Issue Description: leftid and rightid must be public, all traffic tunnels except https.  ping, ssh, http work just fine.

i had to change the left and right IDs to match my public IPs.  an issue i have not fixed yet is that https traffic is dropped over the tunnel.  ssh, ping, and http traffic work just fine.

**Comment by ToddKopriva** [comment]
moved unmaintained tutorial to archive

https://github.com/GoogleCloudPlatform/community/pull/2425
