### ISSUE TITLE
Get Data from API to BigQuery using DataFlow

### ISSUE THREAD

**Issue by devendar-kachhwaha** [GoogleCloudPlatform/community#2318]
I want to get data from some rest API and create a table in BigQuery using DataFlow API. But I'm not able to find out how to do that.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
