### ISSUE TITLE
Tutorial Updation needed

### ISSUE THREAD

**Issue by Sangamesh-ts** [GoogleCloudPlatform/community#2321]
https://cloud.google.com/community/tutorials/container-image-management-with-harbor

the following tutorial doesn't work with google artifactory registry for docker. 
Can anyone who has been able to make it work update the tutorial?
Im getting the following error with artifactory registries. 
```
fer/image/transfer.go:357]: failed to check the existence of the manifest of artifact test/service:sha256:0bb353b0450ffb9b96be20bcdf8970a7cb2b605a1746473375592df415bd188e on the destination registry: http status code: 405, body: 
2023-01-30T20:00:01Z [ERROR] [/controller/replication/transfer/image/transfer.go:180]: http status code: 405, body: 
```

**Comment by ToddKopriva** [comment]
@jpatokal , could you take a look at this issue about a tutorial that you contributed?

**Comment by jpatokal** [comment]
The actual author of this tutorial is Marc Fong, I've pinged him separately.

**Comment by ToddKopriva** [comment]
Thanks, @jpatokal .

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
