### ISSUE TITLE
Not able to create Vm from a machine image having regional disk.

### ISSUE THREAD

**Issue by Avinash-jayakumar** [GoogleCloudPlatform/community#2335]
I have a Vm with regional disk. Took a machine image out of this VM. Now i am trying to create another vm using this machine image. But not able to do it.

Getting this error Invalid value for field '': ''. All regional disks must have replica zone overrides provided.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
