### ISSUE TITLE
Not able to create machine image with CMEK.

### ISSUE THREAD

**Issue by Avinash-jayakumar** [GoogleCloudPlatform/community#2336]
When we create a machine image for a VM which is encrypted with CMEK, it is showing that disks are google-managed encryption in machine image screen.  When we try to create a vm from this machine image , the disks are not encrypted with the CMEK key we provide

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
