### ISSUE TITLE
dist/ directory not found after `npm run build`

### ISSUE THREAD

**Issue by tpp254** [GoogleCloudPlatform/community#2364]
Following the tutorial for community/tutorials/securing-gcs-static-website/static-website and the build process doesn't work as expected. 

`npm run build` throws the following error: 

```
library: 'digital envelope routines',
reason: 'unsupported', 
code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

Added the following piece in package.json and it seems that it is working now: 

```
"scripts": {
    "serve": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
    "build": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build",
    "lint": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service lint"
},
```

**Comment by ToddKopriva** [comment]
Which document is this about?

**Comment by tpp254** [comment]
community/tutorials/securing-gcs-static-website/static-website

**Comment by ToddKopriva** [comment]
@xiangshen-dk , could you take a look at this report about a document that you worked on?

**Comment by xiangshen-dk** [comment]
Looks like this error only appears for certain node versions (v17.*). The suggested workaround gives an error for v19. Anyhow, I have added a note in the build step and created a PR.

**Comment by ToddKopriva** [comment]
Thanks, @xiangshen-dk .

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
