### ISSUE TITLE
EOL/Obsolete Operating System: Alpine Linux Version 3.8 Detected

### ISSUE THREAD

**Issue by shrikant6989** [GoogleCloudPlatform/community#2372]
In latest qualys security scan we found this vulnerability that the Linux apline version being used in the docker image is obsolete. 
Can you please rebuild it with latest version and all latest artifacts to fix the security vulnerabilities.

**Comment by ToddKopriva** [comment]
What document in this repository are you referring to?

**Comment by shrikant6989** [comment]
Sorry for raising the issue in general section, I am specifically referring to below file. It is using obsolete version of alpine linux 3.8. In case any other services are using it, you may want to update it. :
https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/gcp-cos-basic-fim/Dockerfile

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
