### ISSUE TITLE
Issue with tutorials/serverless-static-ip/index.md

### ISSUE THREAD

**Issue by MauroOyhanart** [GoogleCloudPlatform/community#2387]
Issue Description:
When I try to create the connector, with
```
gcloud compute networks vpc-access connectors create ${VPC_CONNECTOR} \
  --network ${NETWORK_NAME} \
  --region ${REGION} \
  --range ${CONNECTOR_IP_RANGE}
```
The Cloud Shell says

_Create request issued for: [my-connector]
Waiting for operation [projects/learning-vpc-nat/locations/us-west4/operations/aeab6a11-c59d-429a-b19a-efcf4e992ac9] to complete...failed.                                                     
ERROR: (gcloud.compute.networks.vpc-access.connectors.create) {
  "code": 9,
  "message": "Operation failed: Insufficient CPU quota in region."
}_

This happens both with us-central1, and with us-west4. I have practically zero use of GCP in us-central1, and absolutely no use in us-west4.
What could be about my configuration (I followed everything in the tutorial) that does not allow me to create the connector?

**Comment by jphalip** [comment]
Could this be useful? https://stackoverflow.com/questions/70562667/creating-new-gcp-serverless-vpc-access-connection-error-insufficient-cpu-quota

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
