### ISSUE TITLE
I want to export the GCP admin activity events to SIEM securonix. Did any one do this integration before?

### ISSUE THREAD

**Issue by Anilkumarsriramula** [GoogleCloudPlatform/community#2393]
Using the SIEM securonix, I want to monitor the activities done by admin id in my enterprise account in GCP platform (console.google.com and admin.google.com)

did any one perform this real-time integration before?
Did you pull the events logs from securonix siem?
Or did u posh from gcp admin platform?

it would be helpful if you could share your experience

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
