### ISSUE TITLE
Issue with tutorials/serverless-grafana-with-iap/index.md - Alerting

### ISSUE THREAD

**Issue by paulwer** [GoogleCloudPlatform/community#2409]
Alerting while using Cloud Run Service does not work fully, because background jobs are dont executed, when instance is not active.
We had to introduce a cpu allways allocated flag for the service, but we are not sure, if this works well, when multiple instances are running at the same time. Please check if this is sufficent and add it to the documentation, if so.

Thank you very much
Paul

**Comment by ToddKopriva** [comment]
@cgrotz and @annamuscarella , can you take a look at this question about a document that you contributed?

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.

**Comment by paulwer** [comment]
is there an alternative to this repo?

**Comment by ToddKopriva** [comment]
Tutorials and in-depth solutions guides are on the cloud.google.com site:
https://cloud.google.com/architecture
https://cloud.google.com/docs/tutorials

Many of the repositories here contain samples and instructional materials:
https://github.com/GoogleCloudPlatform/
