### ISSUE TITLE
Issue with tutorials/serverless-grafana-with-iap/index.md

### ISSUE THREAD

**Issue by ihalfred** [GoogleCloudPlatform/community#2412]
This tutorial makes it possible to use Grafana with Cloud Monitoring data source. It is possible to leverage MQL in dashboards.
But how to use Prometheus PromQL with the given stack though?
Is it possible to import Prometheus data source (instead of Cloud Monitoring)?
Or perhaps there is a different way to leverage PromQL in dashboards without making any changes to the data source?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
