### ISSUE TITLE
Machines in Madrid get high CPU and Load Average compare U.S machines

### ISSUE THREAD

**Issue by locksmithunit** [GoogleCloudPlatform/community#2413]
Hello, guys, how are you?
So i facing a very wired issue.
When i create my account on the cloud, almost 3 years ago.
I create it with a GMAIL from the U.S and i choose United States as the location of the cloud.

I had a couple of business in the EU (Spain).
1. I notice, installation of products (LITE SPEED, CPANEL, PLESK AND MORE) take more time when i choose machine in EU, sometimes machine get stuck (the same image from Google Cloud marketplace).
**In the same time when i install image on VM in the United States it's take 5 minutes maximum.**

2. I had 3 machines, identical, dedicated server for WordPress.
I did a little test and open the SSH, in the same time i open one website with VM in Virginia, and another website with VM in Madrid.
I do the same operations (actions).
Machine in Madrid get overloaded with Load Average of 40.00 - 20.00 CPUs:
![overload-1-tree-Screenshot 2023-07-06 194823](https://github.com/GoogleCloudPlatform/community/assets/37716063/8a5bf19e-5ed7-4cdb-98d3-fbccaeddfa0c)

![overload-32Screenshot 2023-07-06 194936](https://github.com/GoogleCloudPlatform/community/assets/37716063/8ee6229e-b11d-4429-9078-4731a558cf55)

As i said, the machines, the images from the marketplace, the websites, everything is the same. (e2-micro machines and i try even e2-small, the issue is the same)

**I little suspect it, maybe because the Google Cloud account set up in the United States.**

I am not sure, but still i don't find any reason why machine in United States work properly, and in Europe 2 machines of mine get the same issues, the same overload, when all of them actually identical.

I try it with a couple of images and all the time i get overloaded in EU.

For example, i install image of lite speed in Madrid, it took me 50 minutes.
When i install it on the same machine in Virginia, US, it took 5 minutes.

I start to suspect, maybe it will not happen if i will create a cloud in Spain? (when you create Cloud account in the first time he asked you each country you are)

But i still not sure this is the case, and why should i start hustle with 2 different accounts?

Solutions? Someone?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
