### ISSUE TITLE
Stop Google Cloud Logging

### ISSUE THREAD

**Issue by dhrumildev28** [GoogleCloudPlatform/community#2416]
I have created a GKE cluster(tried with both autopilot and standard). In that I saw that Cloud Logging billing service is being charged. As per documentation, it states that audit logs are used by google for monitoring purpose and when we checked logs it showed almost 350-400 logs/minute. My concern is that if there is a way when I can empty the logs so that I dont get charged or some configuration in account to do so. 
Thanks

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the Google Cloud community---including Google employees and other experts---help out on those forums.
