### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by aug70** [GoogleCloudPlatform/community#247]
This is not working! I'm running into problems deploying an Spring Boot application to GCP.
Here are the details: https://stackoverflow.com/questions/46302785/google-pubsub-v1-publisher-publish-gets-404

**Comment by jabubake** [comment]
@aug70 : 
Looks like there was a known deployment issue with Java applications on App Engine Flex.
Can you make sure `gcloud` is updated to the latest ? https://cloud.google.com/sdk/docs/#install_the_latest_cloud_tools_version_cloudsdk_current_version

If you still run into issues or cannot perform an update:
The workaround is to set use_deprecated_preparation using the following command:
$ gcloud config set app/use_deprecated_preparation True
Once the above property is set, please retry deployment.
