### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible

### ISSUE THREAD

**Issue by h00k3m** [GoogleCloudPlatform/community#255]
Documentation issue:
The codeblock in Step 3 says:
`"post-install-cmd": [
    "chmod -R 755 bootstrap\/cache",
    "php artisan cache:clear"
]`

However, the example snippet below it (of the entire composer.json file) shows this section in `post-deploy-cmd`.

I believe post-deploy-cmd is correct and that block 3 should be corrected.

**Comment by bshaffer** [comment]
@h00k3m We updated this command from `post-deploy-cmd` to `post-install-cmd`. Is it possible you are pulling from the previous docker image version?

**Comment by bshaffer** [comment]
As for the image, the wrong one was somehow uploaded but this is now fixed (it may take an hour for the edge caches to update). Thank you for pointing this out!
