### ISSUE TITLE
Issue with ghost-on-app-engine-part-1-deploying

### ISSUE THREAD

**Issue by alexerhardt** [GoogleCloudPlatform/community#257]
This tutorial is quite outdated; it is not valid for versions after Ghost 1.0 as they don't use config.js anymore.

**Comment by ToddKopriva** [comment]
@realmensah , can you comment on this bug? I see that you updated the tutorial somewhat recently in this PR:
https://github.com/GoogleCloudPlatform/community/pull/477/

**Comment by ToddKopriva** [comment]
Thanks for the confirmation. I'm closing this issue, then.
