### ISSUE TITLE
Error: .google.cloud.speech.v1.RecognizeRequest#bucket is not a field: undefined

### ISSUE THREAD

**Issue by alteredorange** [GoogleCloudPlatform/community#265]
Trying the Twilio Voice to Google Transcription tutorial.  Everything works except for the analyzeRecording function, which throws this error:
`Error: .google.cloud.speech.v1.RecognizeRequest#bucket is not a field: undefined`

Any thoughts?  bucket is defined, so I'm not sure what the problem is.

Tutorial: https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/cloud-functions-twilio-voice-record

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
