### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by ramimmadi** [GoogleCloudPlatform/community#271]
Many files like application-mysql-datasource are not there. Documentation is little confusing. Please update the page. anyhow I followed the given steps but facing error.
https://cloud.google.com/community/tutorials/run-spring-petclinic-on-app-engine-cloudsql ....I am trying to deploy petclinic on GAE using the above url. did all the mentioned steps but still facing SQL related errors.. "Unknown syntax DATABASE." please help me out. It is said that it is using HSQL as default storage option. Later I followed the steps to convert the datasource to Cloud SQL by following the given steps. But facing issues. (Documentation is not very clear. Please help me out)

**Comment by jabubake** [comment]
Hi @ramimmadi , thanks for pointing out the file name issues. I'll review and update. In the mean time, can you look at the copy of the source code here ? (which does have the expected file names).
https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/run-spring-petclinic-on-app-engine-cloudsql/spring-petclinic
