### ISSUE TITLE
Free UniFi controller

### ISSUE THREAD

**Issue by pfloyd2000** [GoogleCloudPlatform/community#277]
I'd like to use GCP to host a small UniFi controller. Ideally, I'd like to do it for free. My thinking is having a place to host a controller that isn't mission critical.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
