### ISSUE TITLE
data-science-extraction (convert_audio.py)

### ISSUE THREAD

**Issue by les-tallman** [GoogleCloudPlatform/community#280]
I download aesop_fables_volume_one_librivox_64kb_mp3.zip from librivox.org and unzipped the file. When I attempt to convert fables_01_02_aesop_64kb.mp3 using convert_audio.py I get the following error.

Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Converting fables_01_02_aesop_64kb.mp3
Traceback (most recent call last):
  File "convert_audio.py", line 62, in <module>
    main(args.mp3_files)
  File "convert_audio.py", line 49, in main
    f.read(), {'name': mp3_filename})
  File "/Users/username/Projects/google/venvp3/bin/../lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 129: invalid start byte

**Comment by jerjou** [comment]
Oh whoops - in line 49 of `convert_audio.py`, can you change `'r'` to `'rb'` and see if that fixes it?

**Comment by ToddKopriva** [comment]
@les-tallman , did jerjou's suggestion work for you?

**Comment by ToddKopriva** [comment]
closing issue because document is being archived
