### ISSUE TITLE
express-memcached-session-appengine (deprecated)

### ISSUE THREAD

**Issue by Crytiqal** [GoogleCloudPlatform/community#282]
Sat, 28 Oct 2017 14:18:03 GMT express-session deprecated undefined resave option; provide resave option at app.js:39:9
Sat, 28 Oct 2017 14:18:03 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:39:9

**Comment by ToddKopriva** [comment]
@Tabrarian , could you look at this issue and see what action is needed?

**Comment by ToddKopriva** [comment]
The memcache tutorial has been archived because it is out of date, so I'm closing this issue.
