### ISSUE TITLE
Analyzing a large amount of twitter data

### ISSUE THREAD

**Issue by arichanen** [GoogleCloudPlatform/community#285]
Would be nice to have a demo using both batch and streaming to the data and analyzing that data. A demonstration of building a good classifier that uses sentiment analysis and possibly topic analysis would be great.

**Comment by jmdobry** [comment]
@JustinBeckwith might have some insight on this

**Comment by JustinBeckwith** [comment]
Hey wait...  I already wrote that code!  It's hanging around somewhere.  I'll clean it up and get it on the GitHub.

**Comment by devlance** [comment]
Is one of these close to what you're looking for?

- [Real-Time Data Analysis with Kubernetes, Cloud Pub/Sub, and BigQuery](https://cloud.google.com/solutions/real-time/kubernetes-pubsub-bigquery)
- [Real-Time Data Analysis with Kubernetes, Redis, and BigQuery](https://cloud.google.com/solutions/real-time/kubernetes-redis-bigquery)

**Comment by ToddKopriva** [comment]
@arichanen , I'm closing this issue because it looks like @devlance has given you a good set of links.
