### ISSUE TITLE
Tutorial Request - Install MongoDB and NodeJS on Google Compute Engine

### ISSUE THREAD

**Issue by umtek12** [GoogleCloudPlatform/community#295]
There is no tutorial on installing both MongoDB and NodeJS on Google Compute Engine. I am running into so much issues with connections and inserting and it would truly help if someone came up with that guide.

**Comment by umtek12** [comment]
This is what I have so far:

Make Google Cloud Work:
1. Putty Key Generator
- Generate
- Move Mouse
- Key Comment is Username
- Key Passphrase is Password
- Save Public & Private Key

1. Google Cloud Add SSH Key
- SSH Keys
- Edit
- Copy Paste Putty Key Code

1. Google Cloud VM Instance
- VM Instance
- Create Instance
- CentOS
- SSH
- View gcloud command
- Run in Cloud Shell

1. Linux Code
- cd /
- sudo su
- sudo apt-get update
- sudo apt-get install apache2
- sudo apt install php5
- cd /var/www/
- chmod -R 0777 html/
- cd /etc/
- chmod -R 0777 apache2/

1. PHPStorm
- Tools > Deployment > Configuration...
- STFP host: {IP ADDRESS}
- Root Path: /var/www/html
- Username: admin
- Key Passphrase: password
- {Remove index.html}
- {Upload project}

1. Allow .htaccess
- Run command: a2enmod rewrite
- Change file /etc/apache2/apache2.conf
- Replace in <Directory /var/www/> "AllowOverride None" to "AllowOverride All"
- service apache2 restart

1. Install NodeJS
- cd /var/www/html/backend
- Go to website "https://github.com/nodesource/distributions
- curl -sL https://deb.nodesource.com/setup_9.x | bash -
- apt-get install -y nodejs
- node -v
- sudo apt-get update
- sudo apt-get install build-essential libssl-dev
- npm -v

1. Install Packages
- cd /var/www/html/backend
- {Have package.json already}
- npm install express --save
- npm install cors --save
- npm install body-parser --save
- npm install curl --save
- npm install -g nodemon --save

1. Run NodeJS forever
- cd /var/www/html/backend
- npm install -g forever
- sudo chown root /etc/rc.local
- sudo chmod 755 /etc/rc.local
- chmod -R 0777 /etc/rc.local
- chmod -R 0777 /etc/init.d/rc.local
- Edit rc.local file
Before exit 0, add:
sudo service mongod start
cd /var/www/html/backend
forever start -c nodemon server.js
- Upload file to /etc and /etc/init.d
- forever start -c nodemon server.js

1. Install MongoDB
- cd /
- sudo apt-get install git
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
- echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
- sudo apt-get update
- sudo apt-get install -y mongodb-org
- sudo service mongod start
- service mongod status
- cd /var/www/html/backend
- npm install mongodb --save

1. Open Port 8080 and 27017

**Comment by auedbaki** [comment]
I have setup Nodejs Project on Google Cloud App Engiene and Setup a MongoDB on MongoDB Atlas, when i try to connect that mongodb from cloud where Nodejs Project located, it gives error!. I am sure problem is in GCP App Engiene Setting, bacuase Mongodb hosting is working fine, i connect that server from my own Laptop.

**Comment by ToddKopriva** [comment]
Here is a tutorial that includes the installation of MongoDB and Node.js and uses Compute Engine:
https://cloud.google.com/community/tutorials/compute-quickstart
