### ISSUE TITLE
This line in the example should be using Spanner parameters not string interpolation.

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/community#298]
This line is using string interpolation to substitute the `id` into the query, without any kind of validation which would result in trivial SQL injection attacks. The sample should instead make use of the Spanner parameters feature.

https://github.com/GoogleCloudPlatform/community/blob/4f5e27d6df92bdaf939ba7989759de224e43ba44/tutorials/cloud-spanner-aspnet/BookWebApi/BookWebApi/Controllers/BookController.cs#L67

**Comment by ToddKopriva** [comment]
@benwulfe , could you have a look at this issue about a tutorial that you submitted?

**Comment by benwulfe** [comment]
Ivan is correct.  It should be using a parameter.

**Comment by ToddKopriva** [comment]
@ivannaranjo , If you make the fix that you suggested, I can review and merge it.

**Comment by ToddKopriva** [comment]
The tutorial that this issue is about has been archived.
