### ISSUE TITLE
Should show how to cache the SpannerConnection instances

### ISSUE THREAD

**Issue by ivannaranjo** [GoogleCloudPlatform/community#299]
https://github.com/GoogleCloudPlatform/community/blob/4f5e27d6df92bdaf939ba7989759de224e43ba44/tutorials/cloud-spanner-aspnet/BookWebApi/BookWebApi/Controllers/BookController.cs#L40

Given how expensive it is to create a Spanner connection, the sample should show how to cache the connections instead of creating a new connection in every request.

**Comment by ToddKopriva** [comment]
@benwulfe , could you comment on this suggestion regarding a tutorial that you contributed?

**Comment by benwulfe** [comment]
This is unnecessary as the spanner ADO.NET provider does caching under the covers.

**Comment by ToddKopriva** [comment]
Thanks, Ben. I'm closing this issue.
