### ISSUE TITLE
For App Engine Flexible PHP, add flex_exec to Laravel and Symfony

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/community#300]
This is important for database migrations

**Comment by tmatsuo** [comment]
Any updates?

**Comment by ToddKopriva** [comment]
@tmatsuo and @bshaffer :

I'm going through old issues to see if they are still relevant or if they are stale and can be closed. Can either of you comment on this issue?

**Comment by tmatsuo** [comment]
Yeah let's do it
