### ISSUE TITLE
Deploy Firebase and Parse API as micro-services within App engine - Tutorial

### ISSUE THREAD

**Issue by mrunal-modi** [GoogleCloudPlatform/community#304]
Can I please have the source code and step by step tutorial to deploy the demo (refer youtube URL)?
https://www.youtube.com/watch?v=WpWPMMC0q3E

Further, deploy Parse API to compare to Firebase?

Thanks

Mrunal

**Comment by ToddKopriva** [comment]
This tutorial shows deployment of a Parse server on App Engine:
https://cloud.google.com/community/tutorials/nodejs-parse-server-on-appengine
