### ISSUE TITLE
Tutorial request: Connect to BigQuery and stream data

### ISSUE THREAD

**Issue by FlorentPalomares** [GoogleCloudPlatform/community#316]
Hello,

I'm looking for a solution to stream data from user browsers to BigQuery.
- BigQuery JS API is too complex, as I don't want authentication process
- DataFlow is too complexe, as I don't want to transform data before insert

So, I'm looking for a tutorial to create an HTTP Cloud Function to run basic operations like a simple INSERT into my BigQuery dataset.

Creating an HTTP Cloud Function is well documented.
But connecting to BigQuery (libraries to include & authentication process), then running queries is not straightforward.

Thank you!

**Comment by ToddKopriva** [comment]
This tutorial shows how to stream data to BigQuery with Cloud Functions:
https://cloud.google.com/solutions/streaming-data-from-cloud-storage-into-bigquery-using-cloud-functions
