### ISSUE TITLE
[Tutorial request] Google Vision API use cases examples

### ISSUE THREAD

**Issue by skylinetech-team** [GoogleCloudPlatform/community#318]
hi, just wonder is there any end to end use case example in Python (or Java or Node JS) for using Google Vision API and cover the followings ?

1. customized REST API to take call from client - receiving image data in JSON format
2. upon receiving image JSON data, call a customized function for face verification or recognition - a.k.a I I have face verification / recognition functions in Python, would like to plugin these function in and invoke them
3. response back to calling client
4. make this customized REST API docker image, deploy to GCP registry
5. deploy to GCP load balancer
6. expose public external IP for calling client.

I have tried these myself in pieces, but would like to get your guys advises on the same, as these steps are pretty much common exercises.

thanks much !

**Comment by skylinetech-team** [comment]
ideally I would like to see a combination of using Google Vision API and Tensor flow, but any other models - like model from Inception Image V3 or model from face net would be fine too.

I also have Andrew Ng's course face verify / recognize functions would like to try in GCP.

just want to be architecturally correct when implementing it in GCP

**Comment by ToddKopriva** [comment]
This document is a good starting point:
https://cloud.google.com/solutions/creating-object-detection-application-tensorflow
