### ISSUE TITLE
Issue with https-load-balancing-nginx#install-your-ssl-certificates

### ISSUE THREAD

**Issue by arunoo** [GoogleCloudPlatform/community#323]
In [http-load-balancing-nginx](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/https-load-balancing-nginx/index.md), the first paragraph under "Install your SSL certificates", when trying to copy SSL certificates to the instances, I received permission denied errors as well as a warning about deprecated `copy-files` command:

```
arunl@ooo:~/temp/ssl-certs$ for i in {1..3};
>   do \
>     gcloud compute copy-files ~/temp/ssl-certs \
>       root@www-$i:/etc/apache2; \
>   done
WARNING: `gcloud compute copy-files` is deprecated.  Please use `gcloud compute scp` instead.  Note that `gcloud compute scp` does not have recursive copy on by default.  To turn on recursion, use the `--recurse` flag.
Warning: Permanently added 'compute.7159522622787349082' (ECDSA) to the list of known hosts.
root@35.185.72.59: Permission denied (publickey).
lost connection
ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1].
...
```

To work around it, on each instance, I scp-ed the SSL files to a tmp folder, then SSH-ed in to `sudo mv` the files from /tmp to /etc/apache2. Not sure if there is a better option.

**Comment by ToddKopriva** [comment]
I've assigned this issue to myself. I'll attempt to track down the right person to update this tutorial.

**Comment by ToddKopriva** [comment]
fixed with this PR:
https://github.com/GoogleCloudPlatform/community/pull/765
