### ISSUE TITLE
[Error - gcloud beta ml not working !! ] : gcloud beta ml init-project - command failed with errors !!!

### ISSUE THREAD

**Issue by skylinetech-team** [GoogleCloudPlatform/community#324]
when trying this code lab for transfer machine learning - Inception V3 

https://codelabs.developers.google.com/codelabs/cpb102-txf-learning/index.html?index=..%2F..%2Findex#2

in "Setup", when executing "gcloud beta ml init-project" - failed with errors.

please advise, thanks.

**Comment by skylinetech-team** [comment]
just created a new GCP project and running into the same issues, any ideas ??

mark_hu@my-gcp-ml-project:~$ **gcloud beta ml init-project**
ERROR: (gcloud.beta.ml) Invalid choice: 'init-project'.
Usage: gcloud beta ml [optional flags] <group>
  group may be           language | speech | video | vision
For detailed information on this command and its flags, run:
  gcloud beta ml --help
mark_hu@my-gcp-ml-project:~$

**Comment by ToddKopriva** [comment]
This GitHub repository is not the best place to submit reports about codelabs. 

You can submit issues for codelabs here: https://goo.gl/pKnjbS

I recommend bringing questions to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
