### ISSUE TITLE
[Tutorial request] GCP  Pub / Sub + ML Engine + Tiered Code Structures

### ISSUE THREAD

**Issue by skylinetech-team** [GoogleCloudPlatform/community#328]
Hi, we are trying to build an internal demo that compose the followings projects

1. mobile app project (node js based) that can take photo and send photo to GCP
2. service controller project (java based project) that can take request from item#1, get incoming photo bytes[] and save it to GCP pub / pub topic
3. another service controller project that can take images from pub / sub topic and encode it,
4. ML job / model instance that preload known coffee photos, and then process this encoded photo and predict what kind coffee it is and suggestion for how to drink it better
5. another node js project for showing results

we'd like to know how we can structure these many project types through one GCP instance
and would like your guys advises or better yet come up a quick code lab tutorial that covers similar details

thanks.

**Comment by ToddKopriva** [comment]
This should get you started:
https://cloud.google.com/solutions/image-search-app-with-cloud-vision
