### ISSUE TITLE
Live streaming using Google cloud API

### ISSUE THREAD

**Issue by shruna** [GoogleCloudPlatform/community#329]
Dear ,
I want to stream live video from Raspberry pi to Android app in real time and at the same time transfer character data from Android app to Raspberry pi. How should I achieved my task, is it possible to get it done using Google cloud ?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
