### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible

### ISSUE THREAD

**Issue by ravisipl** [GoogleCloudPlatform/community#331]
Hello,
I have deployed application on gcloud App Engine, I deployed successfully but getting *SQLSTATE[HY000] [2002] No such file or directory* while it working fine on local system.
I am following https://cloud.google.com/community/tutorials/run-laravel-on-appengine-flexible  this tutorial.

I also followed https://www.youtube.com/watch?v=QhQ1PrYH3q0&t=230s  but getting same issue.

Webstie url : https://phpsipl1.appspot.com/

My app.yml file is:

    runtime: php
    env: flex
    
    runtime_config:
      document_root: public
    
    # Ensure we skip ".env", which is only for local development
    skip_files:
      - .env
    
    env_variables:
      
      # Put production environment variables here.
      
      APP_LOG: errorlog
      APP_KEY: base64:DZaQGd2hg/irj0YeTQtZxb3bY6Em25gMlLmoY8oDK7E=
      STORAGE_DIR: /tmp
      CACHE_DRIVER: database
      SESSION_DRIVER: database
      DB_HOST: localhost
      DB_DATABASE: blog
      DB_USERNAME: root
      DB_PASSWORD: target@2017
      DB_SOCKET: "/cloudsql/phpsipl1:us-central1:phpsipl"
    beta_settings:
      cloud_sql_instances: "phpsipl1:us-central1:phpsipl" 

Please help me.

**Comment by tmatsuo** [comment]
I suspect that your project doesn't have `sqladmin` api enabled.

Go to:
https://console.cloud.google.com/apis/api/sqladmin.googleapis.com/overview

and enable the API if it's not enabled. Let me know if it's already enabled.

**Comment by grodriguez216** [comment]
Hello @tmatsuo I have the same issue.
Enabling the API did not solved it for me.
Is there any additional configuration needed apart from enabling the API?

**Comment by tmatsuo** [comment]
@grodriguez216 Is it possible to share the reproducible step, or share the actual project with me? Or maybe we can have a Video Conference to debug it together. Please let me know how you want to proceed.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to do troubleshooting and get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
