### ISSUE TITLE
Tutorial Request: Run an Elixir Phoenix app WITH ECTO on the Google App Engine Flexible Environment

### ISSUE THREAD

**Issue by damianM** [GoogleCloudPlatform/community#358]
There is no resources to find how to get phoenix app with ecto running (postgres)  

Technical Level
intermediate

Length
short (< 250 words)

**Comment by bbhoss** [comment]
This should be in the initial getting started tutorial. There's not much use to a phoenix app with no database

**Comment by bbhoss** [comment]
Since it uses distillery you would probably want to use the REPLACE_OS_VARS feature as shown here when building your image, then you'll be able to specify things in the app.yml file http://blog.leif.io/deploying-elixir-projects-with-docker-and-distillery/
