### ISSUE TITLE
Allow multiple tutorial authors

### ISSUE THREAD

**Issue by 4gn3s** [GoogleCloudPlatform/community#362]
With the current frontmatter, only one author is allowed in the tutorial text. Please implement support for multiple authors to prevent people from choosing an author using rock-paper-scissors.

**Comment by jmdobry** [comment]
Great idea!

**Comment by ToddKopriva** [comment]
@jmdobry , it looks like you have already done this. 

I see multiple tutorial authors here:
https://cloud.google.com/community/tutorials/singularity-containers-with-cloud-build

... and I see a CL from March 13th that implements it.
