### ISSUE TITLE
Google App Engine Standard - Java 8 with non blocking stack

### ISSUE THREAD

**Issue by visakha** [GoogleCloudPlatform/community#364]
Its unfortunate that a company like google has very little focus on quality and quantity of tutorials on using the GAE Standard.
I am struggling to find decent and recent tutorials on using, for example
a) Bookshelf App (the one from documentation) refactored for several stack combinations
a.1) Java 8 + Non Blocking all the way
a.2) Kotlin + Non Blocking all the way
a.3) Java 8 + Vertx
a.4) Java 8 + Cassandra DB
a.5) Java 8 + Reactive Microservices

**Comment by anantdamle** [comment]
@visakha Can you explain what do you mean by non-blocking all the way for point-a?

**Comment by visakha** [comment]
We know that Java Servlet is blocking and that the number of active
sessions (or concurrent users) are limited by number of the threads that
are on the host machine.
With coming of Netty and other reactive spec, we can by pass the servlet
technologoes and use the reactive and non blocking paradigms.

for the App Engine Standard I was able to stand up a KTOR based web app, my
question is
is that KTOR on the App Engine Standard -- is that servlet based ? in that
case its not scalable as the blocking http sessions would hold up a thread.
or is it not

thank you
V
