### ISSUE TITLE
interacting with aws db instance using google cloud functions

### ISSUE THREAD

**Issue by Praveenrajmani** [GoogleCloudPlatform/community#366]
Hi guys !,
I am trying to connect to aws db instance through cloud fucntions . Can you provide me a sample example or link explaining the above.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
