### ISSUE TITLE
NodeJS deploy on Compute Engine

### ISSUE THREAD

**Issue by vamshi9** [GoogleCloudPlatform/community#368]
I have established ssh connection and then cloned my git repository. When I run node app.js, it is showing the output app is running on 3000. But when I have opened http://external_IP:3000 , it not loading anything. There must be a better way to explore compute engine for node developers rather brainstorming.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
