### ISSUE TITLE
Tutorial Request: Connect Google Cloud Pub/Sub to Azure Service Bus

### ISSUE THREAD

**Issue by knitterb** [GoogleCloudPlatform/community#369]
I find that @ptone wrote a [very good article](https://cloud.google.com/community/tutorials/cloud-functions-sns-pubsub) on how to integrate AWS SNS with GCP Cloud Pub/Sub.  I've looked, but I can't find a similar article or details on how to connect Azure Service Bus to GCP Cloud Pub/Sub.  

When looking at Azure Service Bus there doesn't appear to be a similar capability to add a webhook to a topic to establish a subscription.  It does appear that by [using Event Grid](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-to-event-grid-integration-concept) (through Azure Functions) one could effectively push Service Bus messages to a webhook endpoint.

At the end of the day I'm looking to get Azure Monitoring to send notifications to a Cloud Pub/Sub topic.  I did find that [webhooks](https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/insights-webhooks-alerts) exist for Azure Monitoring, but this looks cumbersome to define a webhook for each alert/notification that is set up.  

I'd love a tutorial on Google Cloud Pub/Sub to Azure Service Bus integration!

**Comment by ptone** [comment]
Thanks for the feedback - I've filed this under an internal requested solutions tracker as well linking to this GH issue.

**Comment by Mute-camcorder** [comment]
@ToddKopriva, @ptone, is there any update for the community on the internal request for this issue?

**Comment by Manpreetchandi10** [comment]
@ToddKopriva  Hi , I am looking for  Connect Google Cloud Pub/Sub to Azure Service Bus , does we have any solution for this ??
