### ISSUE TITLE
Issue with ghost-on-app-engine-part-1-deploying

### ISSUE THREAD

**Issue by nohe427** [GoogleCloudPlatform/community#375]
Issue Description:

Really outdated and not updated for current major release.  Current major release has some major differences in it which would break a lot of this functionality.

**Comment by ToddKopriva** [comment]
Alexander, the tutorial has been significantly updated with this PR:
https://github.com/GoogleCloudPlatform/community/pull/477

I'm closing this issue, but feel free to open another with specific details about what needs to be updated if there are still changes needed.
