### ISSUE TITLE
Issue with nginx-ingress-gke

### ISSUE THREAD

**Issue by keirl** [GoogleCloudPlatform/community#378]
The tutorial does not take into account RBAC for Kubernetes and does not work out of the box on current GKE.

**Comment by vtuson** [comment]
Hi Keirl,

I work at Bitnami and I had a similar issue. Our kubernetes-sandbox image that you can find in Google Cloud Engine is a good way to test and get this to work. 

https://console.cloud.google.com/launcher/details/bitnami-launchpad/kubernetessandbox?q=kubernetes%20sandbox

Once you have launched and you ssh to it, under /home/bitnami/stack/kubernetes/manifests you can find two yaml files with rbac and controller configurations for ingress.

**Comment by ToddKopriva** [comment]
This pull request addresses this issue:
https://github.com/GoogleCloudPlatform/community/pull/374
