### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible - Queues

### ISSUE THREAD

**Issue by neilcrookes** [GoogleCloudPlatform/community#380]
@bshaffer I and the community would be most grateful if you could expand the article to cover if it's possible, and if so how, to use Laravel's built in Queue functionality on appengine flexible, and if not, explicitly state that it's a limitation and perhaps discuss an alternative, e.g. with Cloud Pub/Sub?

It's just that since queues are hugely important to larger applications, the likes of which developers might want to deploy on GCP, that there is no information on how to achieve them with Laravel, is, I would suggest, a significant hurdle in GCP adoption.

**Comment by ToddKopriva** [comment]
This tutorial was archived in this pull request:
https://github.com/GoogleCloudPlatform/community/pull/2143

The tutorial is still available in the /archived folder.
