### ISSUE TITLE
Tutorial Request: Chatbot that uses dialogflow and Google Cloud Speech

### ISSUE THREAD

**Issue by DheerajAluru** [GoogleCloudPlatform/community#391]
Hi..I'm developing a chatbot that uses google cloud speech API so that it recognizes input from any language..but i'm finding difficulty in integrating it to dialogflow. Help will be appreciated.Thanks 😃

**Comment by ToddKopriva** [comment]
This series is a good place to start:
https://cloud.google.com/solutions/building-and-deploying-chatbot-dialogflow
