### ISSUE TITLE
Issue with sudo apt-get install mysql-server php5-mysql php-pear

### ISSUE THREAD

**Issue by cmlong05** [GoogleCloudPlatform/community#394]
sudo apt-get install mysql-server php5-mysql php-pear

did not work while installing for Ubuntu 16

i think it should change the php5-mysql to php7.0-mysql

it works while me test .

**Comment by ToddKopriva** [comment]
Is this issue about a specific tutorial in this repository? 

I'm closing this issue because it's not clear what tutorial in this repository this issue is about. Feel free to resubmit your issue with a link to the specific tutorial in this repository with which you are having a problem.
