### ISSUE TITLE
Issue with sudo apt-get install phpMyAdmin

### ISSUE THREAD

**Issue by cmlong05** [GoogleCloudPlatform/community#395]
sudo apt-get install phpMyAdmin 

it did not works which responded that:

E: Unable to locate package phpmyadmin

The proper solutions is there 
https://askubuntu.com/questions/866663/cant-install-phpmyadmin-package-cannot-be-located/866666

which suggested that 

Before installing phpmyadmin, you should be using a non-root user with sudo privileges, as described in Here, also you should have a complete LAMP (Linux, Apache, MySQL, and PHP) installation on. If you don't,then you can Follow this guide on installing a LAMP stack on Ubuntu

If everything is okay,add this ppa

sudo add-apt-repository ppa:nijel/phpmyadmin
sudo apt-get update

then install phpmyadmin

sudo apt-get install phpmyadmin

**Comment by ToddKopriva** [comment]
Is this issue about a specific tutorial in this repository? 

I'm closing this issue because it's not clear what tutorial in this repository this issue is about. Feel free to resubmit your issue with a link to the specific tutorial in this repository with which you are having a problem.
