### ISSUE TITLE
Issue with Test phpMyAdmin 404 not found

### ISSUE THREAD

**Issue by cmlong05** [GoogleCloudPlatform/community#396]
refers to https://help.ubuntu.com/community/phpMyAdmin

sudo ln -s /etc/phpmyadmin/apache.conf /etc/apache2/conf-available/phpmyadmin.conf
sudo a2enconf phpmyadmin
sudo /etc/init.d/apache2 reload

**Comment by ToddKopriva** [comment]
Is this issue about a specific tutorial in this repository? 

I'm closing this issue because it's not clear what tutorial in this repository this issue is about. Feel free to resubmit your issue with a link to the specific tutorial in this repository with which you are having a problem.
