### ISSUE TITLE
Issue with could not figure phpMyAdmin 

### ISSUE THREAD

**Issue by cmlong05** [GoogleCloudPlatform/community#400]
Below seciton, I thought there has something wrong, it could not work while i configure follow it

CentOS 6 and 7

By default, phpMyAdmin allows connections from only localhost. To access the database from a workstation, modify the Allow directive in the Apache configuration file for phpMyAdmin.

    In your text editor, open phpMyAdmin.conf.

    sudo nano /etc/httpd/conf.d/phpMyAdmin.conf

    To allow hosts on your network to access phpMyAdmin, modify the Allow directive for Apache 2.2, adding your workstation's IP address. See an example.

    Restart the Apache service:

**Comment by ToddKopriva** [comment]
Is this issue about a specific tutorial in this repository? 

I'm closing this issue because it's not clear what tutorial in this repository this issue is about. Feel free to resubmit your issue with a link to the specific tutorial in this repository with which you are having a problem.
