### ISSUE TITLE
how to store images on google cloud with codeigniter.

### ISSUE THREAD

**Issue by alcantara64** [GoogleCloudPlatform/community#404]
i have trying what i saw online but all to no avail

**Comment by Jessi1220** [comment]
P00P

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
