### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by ravisipl** [GoogleCloudPlatform/community#412]
I followed https://cloud.google.com/appengine/docs/standard/php/getting-started/deploying-to-app-engine link but i am always getting SQLSTATE[HY000] [2002] No such file or directory error
Please see the below my yam file 
runtime: php
env: flex

runtime_config:
  document_root: public
# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
  - .exe
env_variables:
  APP_KEY: 6f58KkGceOcMoOWgWEIS2XFyl5C67i9M
  APP_LOG: errorlog
  CACHE_DRIVER: database
  DB_DATABASE: db_ampintel
  DB_HOST: localhost
  DB_PASSWORD: target@2020
  DB_SOCKET: "/cloudsql/XXXXXXXXX"
  DB_USERNAME: ampintel
  SESSION_DRIVER: database
  STORAGE_DIR: /tmp
beta_settings:
  cloud_sql_instances: "XXXXXXXXXXX"

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
