### ISSUE TITLE
Prediction on GCP with ML Engine

### ISSUE THREAD

**Issue by SofiaAmel** [GoogleCloudPlatform/community#419]
Hello people,
I am working on GCP to predict, I'm using the census dataset, actually I'm discovering google APIs ( ML Engine ...).

When I launch the prediction job , the job runs successfully, but it doesn't display
![capture](https://user-images.githubusercontent.com/25504507/38998412-cc26c8ae-43ef-11e8-8faa-4a7ab9b2d583.PNG)
 the result.

Can anyone help ? Do you have any idea why it doesn't generate an output ?

Thanks in advance :)

**Comment by puneith** [comment]
You don't have the correct model tag for the SavedModel (model trained using TF). Can you let me know where did you train your model (local training or CMLE) and which TF version did you use? Also which TF version did you specify when creating prediction service from trained model?

**Comment by SofiaAmel** [comment]
I trained my model on CMLE , the TF version is 1.7.0,  first I specified the "runtime-version 1.4" and I tried with 1.6.

**Comment by SofiaAmel** [comment]
Hey @puneith , I downgraded my TF and TB version to 1.6 and I trained my model and I run the prediction with --runtime-version 1.6, and unfortunately still have error in prediction , you can see it below.
If you have any idea, it may help.
Thanks in advance
![image](https://user-images.githubusercontent.com/25504507/39189894-b17c4d0c-47d3-11e8-9db4-735f3f0e9fde.png)

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
