### ISSUE TITLE
Issue with nginx-ingress-gke

### ISSUE THREAD

**Issue by MarkEdmondson1234** [GoogleCloudPlatform/community#421]
## Issue Description

Running the line in the tutorial [here](https://cloud.google.com/community/tutorials/nginx-ingress-gke):

```
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'      
```

resulted in this error:

```
Error from server (NotFound): deployments.extensions "tiller-deploy" not found
```

**Comment by MarkEdmondson1234** [comment]
I got through this by following [this guide](https://docs.bitnami.com/kubernetes/how-to/configure-rbac-in-your-kubernetes-cluster/):

## Step 2: Bind the Tiller service account to the cluster-admin role

Create a tiller-clusterrolebinding.yaml file with the following contents:

      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: tiller-clusterrolebinding
      subjects:
      - kind: ServiceAccount
        name: tiller
        namespace: kube-system
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: ""

Deploy the ClusterRoleBinding:

    kubectl create -f tiller-clusterrolebinding.yaml

**Comment by EdByrnee** [comment]
Did not work :(

**Comment by judepereira** [comment]
@EdByrnee I wrote a complete guide for this here: https://judepereira.com/blog/nginx-ingress-helm-k8s-rbac/

Can you try that and let me know if it works?

**Comment by ToddKopriva** [comment]
@ameer00 , this issue seems to be with a tutorial that you contributed. Could you have a look?

**Comment by ameer00** [comment]
@MarkEdmondson1234, thanks for bringing this to my attention.  You do not need to use the `kubectl patch command` while installing `tiller`.  If you skip that step, everything else should work fine.  
Instead of:
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'      
helm init --service-account tiller --upgrade
```
Please use:
```
kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller   
helm init --service-account tiller
```
I have a PR in for this already.  
Thx

**Comment by ToddKopriva** [comment]
I'm closing this issue, because I think that it's addressed by this PR:
https://github.com/GoogleCloudPlatform/community/pull/639

Let us know if there's still a problem.
