### ISSUE TITLE
Connecting to cloudsql with node.js and express.js

### ISSUE THREAD

**Issue by marcouadro** [GoogleCloudPlatform/community#424]
I have a problem connecting to my database. 

In my config.js file I have the following code: https://pastebin.com/z9i1iR2U
In my db-connection.js file I have: https://pastebin.com/Ze7jFjti

I get the following error: 

> Error: ER_BAD_DB_ERROR: Unknown database 'booking'

But that database exists: https://i.stack.imgur.com/6PQr9.png

So. How can I run the app locally and deploy it. I have tried with the following guide, but with no success: https://cloud.google.com/sql/docs/mysql/connect-app-engine

NOTE: The app engine and cloudsql are both in the same region and project.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
