### ISSUE TITLE
This is probably dead simple but I can't find it in the tutorials

### ISSUE THREAD

**Issue by ingenium21** [GoogleCloudPlatform/community#425]
Hi guys,

I'm trying to create a "collapsible" list application using python on google app engine.  All I want it to do is give me a list of 5 entries, have the user click on one of those entries, and then have it enumerate with their corresponding child entries.  

Anyone know what are the best modules to use?

Thanks

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
