### ISSUE TITLE
FireStore and iOS

### ISSUE THREAD

**Issue by vinceyoumans** [GoogleCloudPlatform/community#426]
There is an instructional for setting up Firestore on iOS... but I think it has some problems.

perhaps someone could take a look at my issue,  and do a tutorial on it. 
https://stackoverflow.com/questions/50101518/firestore-on-new-swift-project-firauth-getuid-implementation

**Comment by ToddKopriva** [comment]
This is a good place to start:
https://firebase.google.com/docs/ios/setup
