### ISSUE TITLE
2 issues: with pushing of a docker image to gcr and with running of a particular docker container

### ISSUE THREAD

**Issue by AndreV84** [GoogleCloudPlatform/community#432]
Hello,
Unfortunately I can run basic docker containers at my Docker - Optimized instance, but when I run 
the below executes just fine:
"docker run --name redis -p 6379:6379 -d redis redis-server"
"docker run --name mysql -e  -d mysql"
but the below will throw the error
" docker run --rm -v $(pwd):/build --link redis:redis --link mysql:mysql custom-image ./program"
_error:
standard_init_linux.go:178: exec user process caused "permission denied"_

The second issue is that it wont push the custom-image to gcr.io whatever permissions I do set to whatever accounts.
So far I tried :+1: 
docker tag custom-image gcr.io/custom-name/imagename
docker push gcr.io/custom-name/imagename
I tried set IAM of 
I tried  suggestions from https://cloud.google.com/container-registry/docs/access-control
that include gsutil iam ch 

What is noteiceable that when I am pushing fropm my personal computer with the same account it works and creates a bucket, but when I push from within gcp it wont create:
Select the artifacts.[PROJECT-ID].appspot.com and/or [REGION].artifacts.[PROJECT-ID].appspot.com buckets' checkboxes, neither it reflects at the web-interface the above section to mark with checkboxes using the instruction from https://cloud.google.com/container-registry/docs/access-control
I also tried :
   docker-credential-gcr configure-docker
   12  docker-credential-gcr gcr-login
The error is below:
denied: Token exchange failed for project "custom-project"
Caller does not have permission 'storage.buckets.create'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
username@instancename ~/folder $ 

References:
https://cloud.google.com/container-registry/docs/support
https://cloud.google.com/container-registry/docs/access-control
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications

**Comment by AndreV84** [comment]
curl https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<your access token>
returns:
"scope": "https://www.googleapis.com/auth/trace.append https://www.googleapis.com/auth/service.management.readonly https://www.googleapis.com/auth/servicecontrol https://www.googleapis.com/auth/monitoring.write https://www.googleapis.com/auth/logging.write https://www.googleapis.com/auth/devstorage.read_only",
 "expires_in": 2732,
 "access_type": "offline"
}

**Comment by AndreV84** [comment]
They say in the instruction:

> ". For an example, for tokens generated specifically for the default service account on your Compute Engine virtual machine, you will need to fix the scope setting for that virtual machine and recreate it."

Could anyone explain how to do that, please?

**Comment by AndreV84** [comment]
the second issue has been resolved via the scopes adjustment.
But can anyone comment on the belo error, please?
" docker run --rm -v $(pwd):/build --link redis:redis --link mysql:mysql custom-image ./program"
error:
standard_init_linux.go:178: exec user process caused "permission denied"

**Comment by kobkrit** [comment]
me too!

**Comment by l15k4** [comment]
me too : 
```
denied: Token exchange failed for project 'foo'. Caller does not have permission 'storage.buckets.get'
```
this occurs non-deterministically, sometimes it works, sometimes it does not :-/

**Comment by l15k4** [comment]
I have 6 builds running in parallel on Drone, each pushing a docker image to GCR, and one of them always  randomly fails on this error :-/

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place for troubleshooting and to get questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
