### ISSUE TITLE
Tutorial Request : Prometheus deployment on GKE

### ISSUE THREAD

**Issue by srinisbook** [GoogleCloudPlatform/community#437]
Could you please add tutorial to deploy Prometheus on Google Kubernetes Engine.

**Comment by ToddKopriva** [comment]
These articles cover Prometheus and GKE:

https://cloud.google.com/solutions/monitoring-apps-running-on-multiple-gke-clusters-using-prometheus-and-stackdriver

https://cloud.google.com/solutions/white-box-app-monitoring-for-gke-with-prometheus
