### ISSUE TITLE
NGINX configs for the rules

### ISSUE THREAD

**Issue by CloudGrimm** [GoogleCloudPlatform/community#438]
-I have managed to follow the tutorial for deploying nginx-controller to GKE using helm but when I add more applications on top of it i receive errors of resources not found. My question is, does one have to manually configure the nginx-controller from helm or its only working with the ingress resources to access internal resources externally in kubernetes?

**Comment by ameer00** [comment]
@cloudgrimm, can you please explain how are you adding more applications on the nginx ingress controller? Are you using the kubernetes ingress resource to configure the nginx controller? My understanding is, that is the intended way to use the nginx ingress controller.
Please share code snippets including error messages if you can. Thx

**Comment by ToddKopriva** [comment]
It seems that this discussion is stalled here. The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
