### ISSUE TITLE
Tutorial request: Request for the Prestashop deployment on the GKE with Cloud SQL 

### ISSUE THREAD

**Issue by aujla0991** [GoogleCloudPlatform/community#440]
Hello 

I would be helpful for the community to add tutorial for the open-source Prestashop on GKE with the Cloud SQL integration. 

References: https://github.com/PrestaShop/docker

**Comment by gabihodoroaga** [comment]
Hi,

I created a tutorial on how to deploy Prestashop on GKE 
https://hodo.dev/posts/post-22-gcp-scalable-prestashop/
How can I added here?

Thanks
g.

**Comment by ToddKopriva** [comment]
> Hi,
> 
> I created a tutorial on how to deploy Prestashop on GKE
> https://hodo.dev/posts/post-22-gcp-scalable-prestashop/
> How can I added here?
> 
> Thanks
> g.

Follow the instructions here:

https://cloud.google.com/community/tutorials/write
