### ISSUE TITLE
Integration tests for creating local spanner db instance for integration tests.

### ISSUE THREAD

**Issue by vineela-gampa** [GoogleCloudPlatform/community#446]
Looking for options to spin up in memory spanner instance to run integration tests. Can you please advise on good way to do integration testing ?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
