### ISSUE TITLE
Issue with nodejs-mongodb-on-appengine - 'strict' mode causes error in mongodb driver call

### ISSUE THREAD

**Issue by a-harrison** [GoogleCloudPlatform/community#449]
Tutorial app as designed throws the following error: 

```
const collection = db.collection('IPs');
		                      ^

TypeError: db.collection is not a function
```

Per https://stackoverflow.com/questions/47662220/db-collection-is-not-a-function-when-using-mongoclient-v3-0 the app needs to be updated to use a client object to obtain collection names.

**Comment by ToddKopriva** [comment]
@a-harrison , would you be willing to make the necessary change yourself? The tutorial that you refer to is a community-maintained tutorial. If you submit a PR with the change, I'll review it.

**Comment by a-harrison** [comment]
Sure thing. Pull request created:
https://github.com/GoogleCloudPlatform/community/pull/643

-Adam

**Comment by ToddKopriva** [comment]
Thanks for the fix. Closing this issue.
