### ISSUE TITLE
Issue with cloud-functions-twilio-voice-record

### ISSUE THREAD

**Issue by complexsplit** [GoogleCloudPlatform/community#451]
I get the following error in my analyzeRecording function:

```
"TypeError: require(...) is not a function
    at exports.analyzeRecording (/user_code/index.js:119:47)
    at /var/tmp/worker/worker.js:716:24
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"   
```

Same issue as seen at https://stackoverflow.com/questions/47149560/google-cloud-functions-require-is-not-a-function-google-cloud

**Comment by ToddKopriva** [comment]
The tutorial has been updated with this PR:
https://github.com/GoogleCloudPlatform/community/pull/498
