### ISSUE TITLE
Style guide table formatting not showing up on cloud.google.com

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/community#452]
The table formatting recommended in the [styleguide markdown file](https://github.com/GoogleCloudPlatform/community/blame/master/tutorials/styleguide.md) isn't being correctly rendered on [cloud.google.com here](https://cloud.google.com/community/tutorials/styleguide).

This markdown:

```markdown
| Table | header | row | default is centered |
| :- | :--: | ---: | ---- |
| Table | data | row | default is left |
| ----------------- |  ----------------- |  ----------------- |  ---------------------------------------------- |
```

is being rendered without any left/right/centering of the text as:

```
<table>
<thead>
<tr>
<th>Table</th>
<th>header</th>
<th>row</th>
<th>default is centered</th>
</tr>
</thead>
<tbody>
<tr>
<td>Table</td>
<td>data</td>
<td>row</td>
<td>default is left</td>
</tr>
<tr>
<td>-----------------</td>
<td>-----------------</td>
<td>-----------------</td>
<td>----------------------------------------------</td>
</tr>
</tbody>
</table>
```

**Comment by ToddKopriva** [comment]
A lot of the items in the style guide aren't being rendered as expected on cloud.google.com. I'll revisit this soon.

**Comment by ToddKopriva** [comment]
This issue is moot now that the style guide doesn't include this table example.
