### ISSUE TITLE
Tutorial Request : Send Sensor data from Arduino to GCP and Display it on Mobile Android App

### ISSUE THREAD

**Issue by vinaytumbemane** [GoogleCloudPlatform/community#453]
Please make tutorial on How to read Battery Voltage level from Arduino and Send it to GCP using MQTT/HTTP or PUB/SUB and store it in google cloud. 

Display the stored data on Android Mobile App. Real time data at every 3 min interval. Every three  minute data should be updated in Cloud and mobile app.

**Comment by ToddKopriva** [comment]
This tutorial gives the details of how to use an Arduino Microcontroller to provide analog sensor readings to a Raspberry Pi, connect the devices to Cloud IoT Core, post telemetry data from the devices, and analyze the data in real time:
https://cloud.google.com/community/tutorials/ardu-pi-serial-part-1

This should be enough to get you started..

**Comment by kursatgol** [comment]
Hi. Did you remove tutorial page from google cloud community? How can i reach it? Could you please provide again? Thanks.

**Comment by ToddKopriva** [comment]
> Hi. Did you remove tutorial page from google cloud community? How can i reach it? Could you please provide again? Thanks.

The tutorial was removed because it was outdated.

**Comment by kursatgol** [comment]
> 

Hi @ToddKopriva . Even if it is being outdated could you please share as a pdf or any other type whatever you choose?
Thanks in advance very much.

**Comment by kursatgol** [comment]
@ToddKopriva But how can i reach explanations? Aggree i see png files and codes but i guess i need explanations as well? They would be better to have. Thanks.

**Comment by kursatgol** [comment]
For instance part list and function descriptions and gcloud screenshots. Thanks.

**Comment by kursatgol** [comment]
Now i found my way but let me ask last question. Where is part2 @ToddKopriva ? Could you please direct me latest? Thanks.

**Comment by ToddKopriva** [comment]
I will not be providing support for a document that we removed because it is outdated.
