### ISSUE TITLE
Places API autocomplete for custom search using file served on Cloud Storage

### ISSUE THREAD

**Issue by jasminderk** [GoogleCloudPlatform/community#455]
I am trying to use the code provided by google places api :
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform
I want to read the input for autocomplete from a  file served on cloud storage using php or javascript but I am stucked over how to implement this logic. I get the file contents using:
```
$target_url = 'https://storage.googleapis.com/bucketname/filename.txt';
$content=file_get_contents($target_url);
echo($content);
```
and I have modified html code in the link in this way:
```
<input id="autocomplete" name="address" value="<?php echo($content);?>"
           onFocus="geolocate()"  type="text"></input>
```
but the code doesn't execute after echo of content. What could be the possible solution to this?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
