### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform

### ISSUE THREAD

**Issue by dsmithuk** [GoogleCloudPlatform/community#456]
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable cloudresourcemanager.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable cloudbilling.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable iam.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud service-management enable compute.googleapis.com
ERROR: (gcloud.service-management.enable) The `service-management enable` command has been replaced by `services enable`.
admin_@cloudshell:~ (davecloud-globalservices)$
admin_@cloudshell:~ (davecloud-globalservices)$ gcloud organizations add-iam-policy-binding ${TF_VAR_org_id} \
>   --member serviceAccount:global-terraform@${TF_ADMIN}.iam.gserviceaccount.com \
>   --role roles/resourcemanager.projectCreator

**Comment by jlucktay** [comment]
This issue looks like a duplicate of #448

**Comment by ToddKopriva** [comment]
closing as duplicate
