### ISSUE TITLE
Issue with the document `managing-gcp-projects-with-terraform`

### ISSUE THREAD

**Issue by dy-kim** [GoogleCloudPlatform/community#462]
## Issue Description
* `gcloud.service-management.enable` seems to be deprecated, but it used in the document [managing-gcp-projects-with-terraform](https://cloud.google.com/community/tutorials/managing-gcp-projects-with-terraform)
  * ```
    gcloud service-management enable cloudresourcemanager.googleapis.com
    gcloud service-management enable cloudbilling.googleapis.com
    gcloud service-management enable iam.googleapis.com
    gcloud service-management enable compute.googleapis.com
    ```
* Error message
  ```
  ERROR: () The `service-management enable` command has been replaced by `services enable`.
  ```

## Environment
```
> gcloud version

Google Cloud SDK 206.0.0
beta 2018.06.12
bq 2.0.34
core 2018.06.18
gsutil 4.32
```

**Comment by jlucktay** [comment]
This issue looks like a duplicate of #448

**Comment by dy-kim** [comment]
@jlucktay Thanks! I'll close this.
