### ISSUE TITLE
[githubAutoDeployer] webhook post body variables may have changed causing 500 error

### ISSUE THREAD

**Issue by mikesparr** [GoogleCloudPlatform/community#471]
Cloned community repo today, July 1, 2018 following instructions here: https://cloud.google.com/community/tutorials/cloud-functions-github-auto-deployer

1. Configured app and deployed http-triggered function. 
2. Added webhook for repo in Github and it failed with 500 error. 

### Error
```
TypeError: Cannot read property 'owner' of undefined
    at exports.githubAutoDeployer (/user_code/index.js:236:35)
    at /var/tmp/worker/worker.js:684:7
    at /var/tmp/worker/worker.js:668:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I viewed the payload from Github webhook and see no `name` field but it has a `login` field.

 * Suggest testing the app and possibly changing to the following:

![screenshot 2018-07-02 11 12 47](https://user-images.githubusercontent.com/5553105/42177202-1f47449a-7de9-11e8-8f8e-b5a17cecb1b2.png)

**Comment by mikesparr** [comment]
I'm unsure if since my functions repo is private under an Org, perhaps the `repository.owner.name` field is not present and instead it uses `repository.owner.login` or if that field just is wrong.

**Comment by mikesparr** [comment]
It looks like this contribution may work for public repos, but not for private repos. After solving the first issue above, it then results in a 404 error trying to retrieve `org/repo/archive/master.zip` file. After tracing back to the `download-git-repo` NPM library, I see they have flags for using clone which must be true, and add SSH keys, in order to support private repos.

As-is, the contribution will only work for public repos unless I'm missing something. Great start, however, and adding a couple more configs and configurable clone flag might make it usable for either.

**Comment by ToddKopriva** [comment]
@Avulpe , could you have a look at this issue regarding a tutorial that you contributed?
