### ISSUE TITLE
Using OAuth 2.0 and Google Cloud Functions to access Google services - Background function

### ISSUE THREAD

**Issue by robertobitbond** [GoogleCloudPlatform/community#473]
Dear All,

I am finding examples and tutorials only for HTTP Google Cloud Function.

Is there a chance to create an example also for Background Google Cloud Function.
My desire is to authenticate "offline" to Gmail API.

exports.background_function = (event, callback) => {
    // CODE
    callback();
};

I am having troubles since several days.

Thanks.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
