### ISSUE TITLE
Issue with run-meteor-on-google-app-engine

### ISSUE THREAD

**Issue by paulincai** [GoogleCloudPlatform/community#478]
In the documentation [https://cloud.google.com/community/tutorials/run-meteor-on-google-app-engine](here), the link to Mongo DB "Create a MongoDB instance as described here." is broken.

**Comment by ToddKopriva** [comment]
Thanks for the report. I see a couple of broken links there. I'll get those fixed.

**Comment by ToddKopriva** [comment]
There are also broken codeblocks on that page. I'll fix those, too.

**Comment by ToddKopriva** [comment]
I fixed the codeblocks.

The link is broken because that page was removed. I'm trying to track down the right place to link to now.

**Comment by ToddKopriva** [comment]
This tutorial has been archived:
https://github.com/GoogleCloudPlatform/community/pull/1014
