### ISSUE TITLE
Issue with cloud-functions-twilio-voice-record

### ISSUE THREAD

**Issue by grevian** [GoogleCloudPlatform/community#481]
The last block on [Analyzing the recording](https://cloud.google.com/community/tutorials/cloud-functions-twilio-voice-record#analyzing-the-recording) has code to interact with Cloud Speech that is wrong, possibly outdated? One cannot call `recognize` directly on the `speech` module, instead one must instantiate a `SpeechClient` as [demonstrated here](https://github.com/googleapis/nodejs-speech#using-the-client-library) then call `recognize` on that

It seems the returned results may be structured differently too

**Comment by ToddKopriva** [comment]
The tutorial has been updated:
https://github.com/GoogleCloudPlatform/community/pull/498
