### ISSUE TITLE
How to import external hosted data in to Cloud for processing?

### ISSUE THREAD

**Issue by droidika** [GoogleCloudPlatform/community#502]
Hi I want to import data from different external hosted sources, a server at home, an api hosted on the web etc. That information has to be stored and processed for further use in GCP.
I'm fine with SQL solution, JSON etc.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
