### ISSUE TITLE
Deploying a local jar file as part of appengine:deploy

### ISSUE THREAD

**Issue by nitesh-shroff** [GoogleCloudPlatform/community#519]
Description
Most of us have a local jar or war file that we want to package as part of our appengine application. I would like to learn the right way of doing this. 

Technical Level
beginner 

Length
short (< 250 words) | medium (250-500 words) | long (1000 words )

**Comment by ToddKopriva** [comment]
I think that this is what you're looking for:
https://cloud.google.com/appengine/docs/standard/java11/testing-and-deploying-your-app#other_deployment_options
