### ISSUE TITLE
Tutorial Request: Hosting a Slash Command on Google App Engine - Part 1 - Custom Integration

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/community#52]
https://github.com/GoogleCloudPlatform/slack-samples/blob/master/command/1-custom-integration

**Comment by tswast** [comment]
Code moved to https://github.com/GoogleCloudPlatform/slack-samples/tree/master/go/command/1-happy-clouds

**Comment by tswast** [comment]
Dina has some more up-to-date sample code using the Slack Events API.

**Comment by dinagraves** [comment]
https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html#0 - The "Extra credit" includes slash commands. Using Cloud Run instead of GAE.

**Comment by ToddKopriva** [comment]
Thanks, @dinagraves .
