### ISSUE TITLE
Google vision api

### ISSUE THREAD

**Issue by muralikk171** [GoogleCloudPlatform/community#527]
Hi I am using Google vision API for text extraction using TEXT_DETECTION/DOCUMENT_TEXT_DETECTION. But few characters are missing from the out put
Below is the code i have used.
        try (ImageAnnotatorClient vision = ImageAnnotatorClient.create()) {
            
            // The path to the image file to annotate
            String fileName = "......DOC051818_3.jpg";

            // Reads the image file into memory
            Path path = Paths.get(fileName);
            byte[] data = Files.readAllBytes(path);
            ByteString imgBytes = ByteString.copyFrom(data);

            // Builds the image annotation request
            List<AnnotateImageRequest> requests = new ArrayList<>();
            Image img = Image.newBuilder()
                             .setContent(imgBytes)
                             .build();
//            ImageContext imageContext =
//                  ImageContext.newBuilder().addLanguageHints("en-t-i0-handwrit").build();
            Feature feat = Feature.newBuilder()
                                  .setType(Type.DOCUMENT_TEXT_DETECTION)
                                  .build();
            AnnotateImageRequest request = AnnotateImageRequest.newBuilder()
                                                               .addFeatures(feat)
                                                               .setImage(img)
                                                               .build();
            requests.add(request);

            
            BatchAnnotateImagesResponse response = vision.batchAnnotateImages(requests);
            List<AnnotateImageResponse> responses = response.getResponsesList();
            for (AnnotateImageResponse res : responses) {
                
                if (res.hasError()) {
                    return;
                }

                for (EntityAnnotation annotation : res.getTextAnnotationsList()) {
                    System.out.println(annotation.getConfidence());
                    System.out.printf("Text: %s\n", annotation.getDescription());
                          System.out.printf("Position : %s\n", annotation.getBoundingPoly());
                }
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }

But could see missing characters from output.
Could you please help me in getting complete text from the image?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
