### ISSUE TITLE
tutorial on how to authenticate and work with cloud datastore for a nodejs app on appengine 

### ISSUE THREAD

**Issue by arunkumar413** [GoogleCloudPlatform/community#528]
Hi Team,

I'd like to have a good tutorial series on how to authenticate with the google cloud datastore and working with the datastore and some of the common tasks that we perform like find by id, adding new entry, updating, deleting etc,. For authentication the official documentation says that we should use the json file. However on the app engine UI there isn't any option to put the json file.

The official documentation isn't much useful and is very confusing because of the different terminology involved compared to mongodb.

Thanks,
Arun

**Comment by ToddKopriva** [comment]
This is a good place to start:
https://cloud.google.com/appengine/docs/standard/nodejs/using-cloud-datastore

It includes sample code.
