### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by abdellahaski** [GoogleCloudPlatform/community#531]
Hi,
Well It's an issue with the [tutorial ](https://cloud.google.com/community/tutorials/run-spring-petclinic-on-app-engine-cloudsql)

There is an error on the spring datasource url :

`jdbc:mysql://google/petclinic?cloudSqlInstance=INSTANCE_CONNECTION_NAME=com.google.cloud.sql.mysql.SocketFactory`

The second parameter name is missing it should be like that: 

`jdbc:mysql://google/petclinic?cloudSqlInstance=INSTANCE_CONNECTION_NAME&socketFactory=com.google.cloud.sql.mysql.SocketFactory`

I tried to update it using that "Edit on Github" button but it shows that it's edited but only on github and it's not updated on that Google Community Tutorials site.

Well I hope it gets updated because that error might turn someone crazy, jkd but seriously it made me lost a day and a half trying to figure out why my app connection to Cloud SQL timeouts (that's the error that the logs give so that's why it's hard to know the source of the problem until I came a across a lifesaver [comment](https://cloud.google.com/community/tutorials/run-spring-petclinic-on-app-engine-cloudsql?google_comment_id=z13zwblijxqzhf25t04cf3bb2kvgir1hmg4) mentioning that error.

Thanks

**Comment by ToddKopriva** [comment]
The correct code appears in the GitHub source. I'll check back on this when we have finished our work on updating how HTML is sanitized.

**Comment by ToddKopriva** [comment]
fixed with new Markdown processor and sanitizer
