### ISSUE TITLE
How to connect from Phoenix/Elixir to Google Cloud Spanner or Google Cloud Bigtable

### ISSUE THREAD

**Issue by 4dcoder** [GoogleCloudPlatform/community#537]
Elixir/Pheonix and Google Serverless DBs hold the promises I need: Mission-critical, scalable, relational database service with transactional consistency, global scale and high availability, suitable for both real-time access and analytics workloads. So how to connect from Phoenix/Elixir to Google Cloud Spanner or Google Cloud Bigtable? Any link for Doc or tutorial would be appreciated. Thanks

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
