### ISSUE TITLE
Tutorial Request: Building a Botkit-based Slack Bot that uses the GCP NL API and runs on Google Container Engine

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/community#55]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/language/slackbot

**Comment by bboymojala** [comment]
I'd like to see this too.  I've got a bot that runs on Windows command line and in Heroku, but not GCP

**Comment by ToddKopriva** [comment]
The existing Botkit tutorials get very low numbers of page views, so I am going to close this request. If someone disagrees with this decision, feel free to reopen the request.
