### ISSUE TITLE
Tutorial Request: How to authenticate with the Cloud Speech API when you are building a website

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/community#56]
actually kind of tricky at the moment and the safest way is using a proxy

**Comment by ToddKopriva** [comment]
It seems that authentication for the speech API is covered here:
https://cloud.google.com/speech-to-text/docs/libraries#setting_up_authentication

If that page is not adequate, then the best thing to do would be to improve that page.
