### ISSUE TITLE
Issue with docker-gcplogs-driver

### ISSUE THREAD

**Issue by ccjon** [GoogleCloudPlatform/community#560]
tags appear to no longer be included in logs and so that choosing the vm instance metric is the only way to see the logs in the console

**Comment by ToddKopriva** [comment]
@tswast , could you look at this issue?

**Comment by tswast** [comment]
@ccjon were you able to investigate this further? This repo only covers issues with the tutorial, not the gcplogs driver itself (which is maintained as part of the docker daemon).

**Comment by tswast** [comment]
Closing, as I have insufficient detail to investigate.
