### ISSUE TITLE
How can I do 301 Permanent Redirection in GCP 

### ISSUE THREAD

**Issue by ShihabInhabitr** [GoogleCloudPlatform/community#561]
How can I redirect URL's in GCP which is not able to handle inside my application?. Earlier I'm doing this on  haccess, when migrated to GCP I couldn't find proper documentation for this.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
