### ISSUE TITLE
Issue with docker-compose-on-container-optimized-os

### ISSUE THREAD

**Issue by geoidesic** [GoogleCloudPlatform/community#566]
This tutorial is presumably out of date as it does not work currently.
The code all executes but the external IP address is not accessible.

**Comment by ToddKopriva** [comment]
@tswast , could you look at this issue?

**Comment by tswast** [comment]
This sounds like a firewall issue to me. If the code is running correctly, likely a port needs to be opened in the project firewall settings to allow external connections.

**Comment by ToddKopriva** [comment]
Thanks, @tswast .
