### ISSUE TITLE
how to change version of php?

### ISSUE THREAD

**Issue by kkkasio** [GoogleCloudPlatform/community#568]
Hello friends, I'm using the google cloud tool for the first time.
I already made the clone of my application via git from github .. however in the initial configuration of gcloud I am with php in PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS ) version
and my application only runs on version 7.1 how do I upgrade?
ps: I'm already using the flexible environment.
thank you.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
