### ISSUE TITLE
Typo: kotlin-ktor-app-engine-java8

### ISSUE THREAD

**Issue by AdamSHurwitz** [GoogleCloudPlatform/community#569]
# Issue Description

There is a typo in the **Create your Ktor Application** section as seen below.

> You can go ahead and run this locally, but but let's add App Engine configuration and

![screen shot 2018-10-19 at 8 53 13 pm](https://user-images.githubusercontent.com/3938076/47251002-1ea48180-d3e1-11e8-9758-ec0ca7befc8d.png)

**Comment by ToddKopriva** [comment]
fixed:
https://cloud.google.com/community/tutorials/kotlin-ktor-app-engine-java8
