### ISSUE TITLE
(minor) Issue with automated-publishing-cloud-build

### ISSUE THREAD

**Issue by dantwining** [GoogleCloudPlatform/community#574]
The document says to create a trigger under the Container Registry menu; I found this under the Cloud Build menu (I guess google moved it!).

Other than that, the tutorial was *perfect* and exactly what I needed to get up and running, thanks so much for writing it.

**Comment by dantwining** [comment]
I will put in a PR for this

**Comment by dantwining** [comment]
https://github.com/GoogleCloudPlatform/community/pull/575

**Comment by ToddKopriva** [comment]
Closing this issue because the PR referred to above fixes the issue. Thanks for that.
