### ISSUE TITLE
Issue with nginx-ingress-gke

### ISSUE THREAD

**Issue by BasmaBoulekhras** [GoogleCloudPlatform/community#576]
I was trying to work with this trial on applications running on different namespaces (dev, test.staging). But, it is always failing. When I create one single ingress resource for one single namespace and then run all my applications, the ingress controller was able to detect the ingress resource and route the traffic successfully. But, once I create 3 ingress-resources ( each one for a different namespace ) and leave the ingress controller in the default namespace, the traffic wasn't balanced to my services! Can you suggest any solution please?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
