### ISSUE TITLE
Issue with elixir-phoenix-on-google-compute-engine

### ISSUE THREAD

**Issue by synalysis** [GoogleCloudPlatform/community#582]
The first step of "Create and configure a Compute Engine instance" fails because **debian-8** is not available - only **debian-9**.

**Comment by ToddKopriva** [comment]
@dazuma , could you take a look at this issue?

**Comment by synalysis** [comment]
The issue is not only that a "8" has to be changed to a "9" but that after deployment the Erlang VM has an incompatible version...

**Comment by dazuma** [comment]
I'm updating the Elixir tutorials now, and will look at this.

**Comment by ToddKopriva** [comment]
Thanks, Daniel.
