### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform

### ISSUE THREAD

**Issue by Sgydoo** [GoogleCloudPlatform/community#589]
Unfortunately I didn't manage to get this to work - 'terraform apply' kept failing with the following:

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * google_compute_instance.default: 1 error(s) occurred:
> 
> * google_compute_instance.default: The zone 'projects/XXXX/zones/europe-west2-c' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.

At one point, the document mentions that the GOOGLE_CREDENTIALS environment variable will be set later in the tutorial but this never happens. Perhaps there's a missing stage?

Anyway, just thought you should know I had to give up on this.

Simon.

**Comment by ToddKopriva** [comment]
@danisla and @miketruty , since you are the original author and most recent contributor to this tutorial, respectively, could you have a look at this issue?

**Comment by Sgydoo** [comment]
To confirm, I think there was a general problem with Trial accounts at the time. It turned out that I couldn't reliably launch VMs via the GCP console either, so it wasn't specific to the Terraform solution suggested by the document.

It would still be good to clarify the GOOGLE_CREDENTIALS reference though.

**Comment by miketruty** [comment]
I've re-run this successfully. I think the original error was transient. But, I did correct the docs with this PR.
https://github.com/GoogleCloudPlatform/community/pull/884

**Comment by ToddKopriva** [comment]
Thanks, Mike. I'll close this issue based on the fix in PR #884.
