### ISSUE TITLE
Upload json data into big table

### ISSUE THREAD

**Issue by jtewari08** [GoogleCloudPlatform/community#591]
Hi ,
Is there any straight forward tutorial to upload json data into bigtable.
I followed csv upload tutorial which work like charm. Is there any similar example available to upload JSON , or same example will work for JSON?

**Comment by ToddKopriva** [comment]
See Solomon's answer here:
https://stackoverflow.com/questions/47345794/load-google-cloud-storage-data-into-bigtable
