### ISSUE TITLE
Issue with how-to-roll-your-app-engine-managed-vms-app-back-to-a-previous-version-part-1

### ISSUE THREAD

**Issue by axsaviour** [GoogleCloudPlatform/community#595]
Issue Description
Rollback section of the document is outdated. The "MAKE DEFAULT" button does not exist anymore in current UI.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll get someone to deal with this.

**Comment by ToddKopriva** [comment]
The correct UI and process are here:
https://cloud.google.com/appengine/docs/flexible/nodejs/migrating-traffic#migrating_traffic_to_a_new_version

Because this tutorial is out of date, I'll archive it.

**Comment by ToddKopriva** [comment]
https://github.com/GoogleCloudPlatform/community/pull/1565
