### ISSUE TITLE
How to create a GAE app in microservices architecture [Python, standard env]

### ISSUE THREAD

**Issue by haopei** [GoogleCloudPlatform/community#596]
A practical tutorial on how to build and deploy an app that is organized in microservices. 

There is currently many bits and pieces of the documentation which provides a conceptual understanding of microservices but does not provide a practical guide.

Thank you.

**Comment by ToddKopriva** [comment]
Here are some tutorials:

https://medium.com/google-cloud/node-python-and-go-microservices-in-a-single-google-app-engine-project-54aac3d60225

https://codelabs.developers.google.com/codelabs/cloud-vision-app-engine/index.html?index=..%2F..index#0
