### ISSUE TITLE
Tutorial Request: Pipeline using Bucket, Pub/Sub, and a watcher Cloud Function

### ISSUE THREAD

**Issue by Firedrops** [GoogleCloudPlatform/community#601]
I believe one can create a cloud function to Publish in Pub/Sub when triggered by cloud storage(Bucket)'s "finalize" event. Looked around on existing documentation but all are incomplete and/or outdated. Could anyone please write a guide on the function and deployment, preferably in python?

**Comment by nielm** [comment]
GCS can do this directly: 
https://cloud.google.com/storage/docs/pubsub-notifications

If you really want to use cloud functions, then you use the [python API](https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-resources-python) to send the pub/sub message from within your cloud function.

**Comment by ToddKopriva** [comment]
@Firedrops , I'm closing this request because the comment by @nielm indicates that such a tutorial may not be necessary. If you disagree, feel free to re-open this request.
