### ISSUE TITLE
request to have auto delete flag for dynamically provisioned persistent disks on cluster deletion

### ISSUE THREAD

**Issue by vinayus** [GoogleCloudPlatform/community#607]
I have a kubernetes cluster on GCP with dynamic persistence volume attached using pd-ssd
Everything works fine but when i delete the cluster, I don't see the dynamically created the pvc or persistence disks being deleted.

I tried adding reclaim policy into storage class and pv but it didn't help.

On searching into multiple docs i did see a flag "Keep disk" at instance level. And similar flag in gcloud compute instances set-disk-auto-delete sdk page. For these dynamically provisioned disks it says Keep Disk as true whereas for boot-disk it is automatically set as false.

So to overcome the hidden billing and usage, I only found these options
1: delete all the deployments/statefulsets which are bounded to these disks so they are deleted(when retainpolicy is set to delete) before cluster deletion is initiated
2: write a script and handle at instance level to auto-delete flag as true using "gcloud compute instances set-disk-auto-delete <INSTANCE> --disk=<PVC DISK> --auto-delete"

So this will be like a feature request or wishlist to have option to auto delete the disks when the respective cluster is removed. I do understand the disaster recovery scenario of retaining disks but a flag would be helpful. Kindly move this to other thread if this is wrong place for requests.

**Comment by ToddKopriva** [comment]
See this page for how to report bugs and request features for GCP:
https://cloud.google.com/support/docs/community#report_bugs_and_request_features
