### ISSUE TITLE
Issue with bigtable-stackdriver

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#610]
I'm copying this issue over from our internal bug system. This report comes from someone trying to use the  bigtable-stackdriver tutorial:

> This link shows 404 for me:
> https://cloud.google.com/community/tutorials/monitoring_metrics.ipynb
> 
> https://cloud.google.com/community/tutorials/bigtable-stackdriver

@waprin , I'm tagging you because you contributed the tutorial. Could you have a look?

**Comment by waprin** [comment]
It's supposed to link to this:

```
https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/bigtable-stackdriver/monitoring_metrics.ipynb
```

**Comment by ToddKopriva** [comment]
Thanks, Bill.
