### ISSUE TITLE
Issue with setting-up-lemp

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#613]
https://cloud.google.com/community/tutorials/setting-up-lemp

Here are problems that a user encountered when trying to use this tutorial:

"Creating a virtual machine instance" section, step 6: 
- "In the OS images tab, choose a Debian 7.x, Ubuntu 14.04, or CentOS 6.x version." 
- There are no Debian 7.x images available. So I chose Debian 8 instead. 

"Install nginx and PHP on your instance" section, step 3:
- "Uncomment selected lines in the PHP section [of my nginx config file]"
-  One of the lines does not exist in my nginx config file; specifically, `include fastcgi_params;` does not exist. 

"Test nginx and PHP" section, in step 2:
- I tried the Debian 7 bullet, but the command (`sudo sh -c 'echo "" > /usr/share/nginx/www/phpinfo.php'`) gave the following error: `sh: 1: cannot create /usr/share/nginx/www/phpinfo.php: Directory nonexistent`. 
- I subsequently tried the Ubuntu 14.04/CentOS 6 version of the command, which returned no error. 
- I'm not sure why we're writing a blank string ("") to that phpinfo script?

"Test nginx and PHP" sectiopn, in step 3:
- When I browse to test the phpinfo.php file that should have been made in the previous step, I get a blank page, not a PHP Info page.

**Comment by dazuma** [comment]
The blank string in the section on "Testing nginx and PHP" is fixed by #633

**Comment by ItsPugle** [comment]
This article has quite a few issues that need to be addressed. Probably the easiest thing to do would just to do a clean start on the article, to be honest.

**Comment by ToddKopriva** [comment]
@steveperry-53 , since you're the original author of this tutorial, could you have a look at it with the above comments in mind?

**Comment by steveperry-53** [comment]
Yes, I'll take a look.
Couple of questions:

* Where did the file go? This file isn't there any more: https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/setting-up-lemp

* Why was this moved from cloud.google.com to community?

**Comment by ToddKopriva** [comment]
Thanks for looking at this, Steve. I'll see if I can find someone to update this, and I may take it down in the meantime. What is your opinion on whether the document should stay up in its current state?

**Comment by steveperry-53** [comment]
I don't think it should stay up in its current state.

**Comment by ToddKopriva** [comment]
Thanks again. I'll take it down.

**Comment by ToddKopriva** [comment]
This tutorial is out of date, so it was archived with PR #682 .

To republish this tutorial, submit a pull request that updates the tutorial and moves it to the /community/tutorials directory.
