### ISSUE TITLE
Issue with ssh-port-forwarding-set-up-load-testing-on-compute-engine

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#614]
https://cloud.google.com/community/tutorials/ssh-port-forwarding-set-up-load-testing-on-compute-engine

I'm opening this issue to pass along feedback from a customer. @deb-saunders , could you have a look?

> This tutorial says that the tunnel can be established with these instructions: 
> 
> To set up the SSH port forwarding for Compute Engine, use the following command:
> 
> gcloud compute ssh  --zone  -- -L 24000:127.0.0.1:24000  \
> -R 25000:127.0.0.1:25000 \
> -L 26000:127.0.0.1:26000  -N -f
> 
> But the command is missing the instance name and the zone. 
> 
> Running the command as per the tutorial will get an error
> "ERROR: gcloud crashed (ValueError): list.remove(x): x not in list"

**Comment by dazuma** [comment]
This is fixed by #633

**Comment by ToddKopriva** [comment]
Dan's fix had to be reverted. I'll check back in on this after our current work to change how we sanitize HTML is complete.
