### ISSUE TITLE
Issue with setting-up-ruby-discourse

### ISSUE THREAD

**Issue by shanel** [GoogleCloudPlatform/community#626]
Is this still currently viable? I seem to continually run into issues with connecting to the Redis instance. I have tried using Cloud MemoryStore and running my own instance as well. Both end up with the same connection issues:

https://gist.github.com/shanel/a4591828c52e1a02e03526321cd8baff

**Comment by dazuma** [comment]
/sub @dazuma 

Can you check your Redis config? Looking at the gist you posted, the redis host doesn't appear to be a valid IP address:

```
Redis::CannotConnectError: Error connecting to Redis on 10.0.03:6379 (Redis::TimeoutError)
```

**Comment by shanel** [comment]
I rechecked this multiple times. I also explicitly upped the timeout to 5
seconds.

I wonder if it could be that things have changed since you set it up and
wrote the how to? I also had to turn off CLIENT operations to redis by
setting id to nil.

**Comment by ToddKopriva** [comment]
There hasn't been any movement on this issue, so I'm going to close it.

In general, the Issues section of this GitHub repository is not the best place for troubleshooting. If you're still having trouble, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
