### ISSUE TITLE
Tutorial Request: Productionizing a Botkit Bot on Google Container Engine

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/community#63]
Part II of https://github.com/GoogleCloudPlatform/community/issues/54

1. Show how to [update the bot to a new version](https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html?index=..%2F..%2Findex#14).
2. Show how to use the [datastore storage module](https://github.com/fabito/botkit-storage-datastore) instead of the default local file storage.

**Comment by ToddKopriva** [comment]
The existing Botkit tutorials get very low numbers of page views, so I am going to close this request. If you disagree with this decision, feel free to reopen the request.
