### ISSUE TITLE
Oh whoops - in line 48 of `convert_audio.py`, can you change `'r'` to `'rb'` and see if that fixes it?

### ISSUE THREAD

**Issue by dtthanh1971** [GoogleCloudPlatform/community#636]
Oh whoops - in line 48 of `convert_audio.py`, can you change `'r'` to `'rb'` and see if that fixes it?

_Originally posted by @jerjou in https://github.com/GoogleCloudPlatform/community/issues/280#issuecomment-339751737_

I have change "r" to "rb"
It did not fix.

**Comment by ToddKopriva** [comment]
Please add this response to the original thread so that the conversation is easier to follow.

https://github.com/GoogleCloudPlatform/community/issues/280
