### ISSUE TITLE
Issue with nginx-ingress-gke

### ISSUE THREAD

**Issue by rgembalik** [GoogleCloudPlatform/community#654]
It would be great if the page would tell the reader what are the benefits of using nginx ingress vs built-in load balancers ingresses. Simple pros/cons/pricing comparison would improve this content a lot.

**Comment by rgembalik** [comment]
@ToddKopriva I understand, but I also think, that the distinction should be clear there. Not everyone would know how does nginx ingress differ from GCE's one, and many times people who are just learning kubernetes (and GKE is one of the best places to do it) might mix one with another as by default GCE ingress is referred to in the docs as just ingress.

I happen to have already bare metal k8s installed and managed on our own servers for a few months, and still, the distinction was not clear enough to me while reading (although that might be just me).

**Comment by ahmetb** [comment]
Unassigning myself.

I have a comparison doc of Ingress (GKE) and Service LB; but not GKE-Ingress vs NGINX-Ingress. You kind of have to figure out that yourself. GKE ingress uses Google Cloud Load Balancing features so it's not a big set of features compared to a generic proxy like NGINX.

**Comment by ToddKopriva** [comment]
Thanks for the response, @ahmetb .

**Comment by ameer00** [comment]
IMO there are too many ingress controllers out there.  HAProxy, NGINX, Kong, Envoy and then more with Istio ingress gateway.  I look at these tools from a few different dimensions: feature set (do I have what I need with the particular controller?), skillset (can I do what I need to do with the tool?), managed (is it managed or OS?) and perhaps optionally maturity (how resilient is the tool as well if there is a good community around it?).  Based on these (or a subset of these), the right tool should arise.

**Comment by ToddKopriva** [comment]
Thanks, @ameer00 .


@rgembalik , I'm going to close this issue, since the issues section of this GitHub isn't the best place for extensive discussion.

If you want to continue the conversation, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
