### ISSUE TITLE
Jenkins Master - Slave for Windows Docker Container

### ISSUE THREAD

**Issue by diangogav** [GoogleCloudPlatform/community#671]
Hello everyone!
Someone could guide me how I can implement a CI CD process in Google Compute Engine for a .Net 4.5 application in Google Compute Engine.

**Comment by diangogav** [comment]
The application is already in a Docker container

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
