### ISSUE TITLE
Tutorial Request: Business Card Scanner/Reader

### ISSUE THREAD

**Issue by vivek081166** [GoogleCloudPlatform/community#691]
Request you to create a Business Card Scanner iOS/Android App
Capture Image --> Crop Image for business card  --> Make Corrections for OCR --> Cloud Vision API --> Extract Text -->  Cloud Natural Language API --> Get Relevant Information

**Comment by ricalo** [comment]
Hi @vivek081166,

This sounds interesting. Quick question, what kind of corrections do you think are needed for OCR?

**Comment by vivek081166** [comment]
> Hi @vivek081166,
> 
> This sounds interesting. Quick question, what kind of corrections do you think are needed for OCR?

By "Make Corrections for OCR" I meant to process the image for better OCR results. I don't know in detail but it could be applying homography, binarization in order to improve OCR results.

**Comment by ricalo** [comment]
Hi,

It looks like the Google Cloud blog explains in good detail how to achieve this functionality. Check [How RealtimeCRM built a business card reader using machine learning](https://cloud.google.com/blog/products/ai-machine-learning/how-realtimecrm-built-a-business-card-reader-using-machine-learning).

You would just have to plug in the mobile client following a pattern similar to the one explained in [Adding speech translation to your Android app](https://cloud.google.com/solutions/mobile/speech-translation-android-microservice).

Closing this issue but feel free to reopen or comment if you have any questions.
