### ISSUE TITLE
Firebase flask with Google Sign-in and Sign-out 

### ISSUE THREAD

**Issue by Hishman** [GoogleCloudPlatform/community#714]
Description

Technical Level: intermediate

Hi,
I am trying to build  falsk admin dashboar and implement Firebase Google sign in/out. Is there any simple way of doing this.

Thanks

**Comment by ToddKopriva** [comment]
This should get you going:
https://cloud.google.com/appengine/docs/standard/python/authenticating-users-firebase-appengine
