### ISSUE TITLE
Issue with run-meteor-on-google-app-engine

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#717]
Multiple users report that this tutorial is not working with versions of Meteor above 1.4.0.1.

https://cloud.google.com/community/tutorials/run-meteor-on-google-app-engine

**Comment by ToddKopriva** [comment]
@ace-n , would you be able to update this tutorial?

**Comment by ace-n** [comment]
@fhinkel is this something we want to maintain, or should we deprecate? I believe we've leaned towards the latter in the past...

**Comment by ToddKopriva** [comment]
This tutorial has been archived:
https://github.com/GoogleCloudPlatform/community/pull/1014
