### ISSUE TITLE
Issue with running-nodejs-on-google-cloud

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#718]
This page needs to be updated.

One thing that needs to be considered in an update is that Node.js also works in App Engine standard environment now.

https://cloud.google.com/community/tutorials/running-nodejs-on-google-cloud

**Comment by ToddKopriva** [comment]
@fhinkel , would you be able to update this document?

**Comment by fhinkel** [comment]
AFAIK we don't have the bandwidth to update community articles. Don't they have a disclaimer that they might be outdated?
