### ISSUE TITLE
Issue with run-symfony-on-appengine-standard

### ISSUE THREAD

**Issue by ledux6** [GoogleCloudPlatform/community#732]
The Javascript and CSS don't load.

**Comment by bshaffer** [comment]
Please ensure your `app.yaml` matches [this one](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/symfony-framework/app.yaml), and that the `url_handlers` section is configured properly!

**Comment by ToddKopriva** [comment]
Thanks for the fix, Brent.
