### ISSUE TITLE
I need help using text to speech

### ISSUE THREAD

**Issue by mateuswolf56** [GoogleCloudPlatform/community#734]
Well I signed up for the google cloud service with the goal of using the text-to-speech tool for a project, which was not expected as I thought it would be serious as other platforms example google translator that you just type the text there and generate the audio, plus the text-to-speech require connection with API and settings that I do not know configure until I read the documentations but I could not understand, I am a PHP Programmer, I would like to help me explain how to use this tool on my computer and configure and where I put the text to generate the audio, I already created the requested JSON file key, I already have the active service account for payments and collections of the tool, and also activated the API, I just do not know how to configure and use now, the Google Cloud SDK, if you can help me and take the steps, thank you.

**Comment by mateuswolf56** [comment]
Error ->

Fatal error: Uncaught exception 'DomainException' with message 'Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information' in C:\wamp\www\teste\voice\vendor\google\gax\src\CredentialsWrapper.php on line 200
( ! ) DomainException: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information in C:\wamp\www\teste\voice\vendor\google\auth\src\ApplicationDefaultCredentials.php on line 156
Call Stack
#	Time	Memory	Function	Location
1	0.0019	257328	{main}( )	...\index.php:0
2	0.0504	1149888	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->__construct( )	...\index.php:14
3	0.0539	1182368	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->setClientOptions( )	...\ImageAnnotatorGapicClient.php:210
4	0.0662	1282608	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->createCredentialsWrapper( )	...\GapicClientTrait.php:309
5	0.0686	1324592	Google\ApiCore\CredentialsWrapper::build( )	...\GapicClientTrait.php:326
6	0.1131	2035944	Google\ApiCore\CredentialsWrapper::buildApplicationDefaultCredentials( )	...\CredentialsWrapper.php:115
7	0.1160	2058624	Google\Auth\ApplicationDefaultCredentials::getCredentials( )	...\CredentialsWrapper.php:198
( ! ) Google\ApiCore\ValidationException: Could not construct ApplicationDefaultCredentials in C:\wamp\www\teste\voice\vendor\google\gax\src\CredentialsWrapper.php on line 200
Call Stack
#	Time	Memory	Function	Location
1	0.0019	257328	{main}( )	...\index.php:0
2	0.0504	1149888	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->__construct( )	...\index.php:14
3	0.0539	1182368	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->setClientOptions( )	...\ImageAnnotatorGapicClient.php:210
4	0.0662	1282608	Google\Cloud\Vision\V1\Gapic\ImageAnnotatorGapicClient->createCredentialsWrapper( )	...\GapicClientTrait.php:309
5	0.0686	1324592	Google\ApiCore\CredentialsWrapper::build( )	...\GapicClientTrait.php:326
6	0.1131	2035944	Google\ApiCore\CredentialsWrapper::buildApplicationDefaultCredentials( )	...\CredentialsWrapper.php:115

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by mateuswolf56** [comment]
Ok, thank you.
