### ISSUE TITLE
google cloud compute engine metadata

### ISSUE THREAD

**Issue by krneeraj123** [GoogleCloudPlatform/community#736]
can any one tell me how to get key value pair of compute engine metadata using google cloud sdk shell ? thanks in advance

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
