### ISSUE TITLE
How to host website on google cloud ?

### ISSUE THREAD

**Issue by akshayjain2907** [GoogleCloudPlatform/community#738]
I have created dns zone,compute engine got the external ip and created bucket with public purmission.But it's loading apache web page instead of my bucket index.html file.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
