### ISSUE TITLE
Issue with modular-load-balancing-with-terraform

### ISSUE THREAD

**Issue by betsy-lichtenberg** [GoogleCloudPlatform/community#739]
When running 'terraform plan', I'm getting errors that look like this:

Error: module.mig1.google_compute_instance_group_manager.default: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig1.google_compute_instance_group_manager.default: "auto_healing_policies.0.health_check": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig1.google_compute_instance_group_manager.default: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig1.google_compute_instance_group_manager.default: "rolling_update_policy": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig1.google_compute_instance_template.default: "network_interface.0.address": [REMOVED] Please use network_ip

Error: module.mig2.google_compute_instance_group_manager.default: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig2.google_compute_instance_group_manager.default: "auto_healing_policies.0.health_check": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig2.google_compute_instance_group_manager.default: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig2.google_compute_instance_group_manager.default: "rolling_update_policy": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig2.google_compute_instance_template.default: "network_interface.0.address": [REMOVED] Please use network_ip

Error: module.mig3.google_compute_instance_group_manager.default: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig3.google_compute_instance_group_manager.default: "auto_healing_policies.0.health_check": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig3.google_compute_instance_group_manager.default: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig3.google_compute_instance_group_manager.default: "rolling_update_policy": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.mig3.google_compute_instance_template.default: "network_interface.0.address": [REMOVED] Please use network_ip

**Comment by chrisst** [comment]
@betsy-lichtenberg we changed the terraform google provider to move beta functionality into its own repo. Right now whatever terraform config you are running against appears to using the `google` provider instead of the `google-beta` but it's trying to use beta features in the instance group manager. 

Your options are either peg the version of the google provider that the example is running against. eg:
```
provider "google" {
  credentials = "${file("account.json")}"
  project     = "my-project-id"
  region      = "us-central1"
  version     = "1.19.0"
}
```
Or use the `google-beta` provider. There should be examples of how to do this in [terraform.io/docs/providers/google/provider_versions.html](https://terraform.io/docs/providers/google/provider_versions.html)


Also I think the real problem is in one of the submodules, so you might file the bug against https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group as I think that's where the fix will need to be applied.
