### ISSUE TITLE
upload file bucket functions

### ISSUE THREAD

**Issue by ChinchillaReactor** [GoogleCloudPlatform/community#741]
Hi, I'm trying to upload a file to the Bucket via G Functions , POST and multipart method. The error I receive is:
"Anonymous caller does not have storage.objects.create access to..."

What I understand is that I need a signature.
I have a Json file with the "project owner" credentials.

I have no idea how to sign the file. Where can I get a working example?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
