### ISSUE TITLE
Issue with Deploying Ghost on App Engine Flexible Environment

### ISSUE THREAD

**Issue by peterlobster** [GoogleCloudPlatform/community#746]
[The Ghost tutorial](https://cloud.google.com/community/tutorials/ghost-on-app-engine-part-1-deploying) references **installing Ghost as an NPM Module which is no longer supported by the new version of Ghost.** [Furthermore, Ghost has removed the instructions from their V1 documentation on their website.](https://docs.ghost.org/v1/docs/using-ghost-as-an-npm-module) Therefore, it would be safe to assume that this installation method is no longer supported/offered by Ghost. It would be nice if the tutorial could reflect these changes; as the updates render the whole knowledge base article invalid.

**Comment by ToddKopriva** [comment]
Thanks for the report. I'm tagging a couple of people who have contributed to this document before to see if they have any insight or are willing to help with the update: @hnipps @realmensah 

If I can't find someone to update this soon, I'll archive it.

**Comment by ToddKopriva** [comment]
The new Ghost installation instructions are here:
https://ghost.org/docs/install/local/

I'll update the document with that link.

**Comment by ToddKopriva** [comment]
updated with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1566
