### ISSUE TITLE
[nginx-ingress-gke] - SSL Support

### ISSUE THREAD

**Issue by chalcedonyt** [GoogleCloudPlatform/community#752]
Any chance that the tutorial could explain if/how SSL could be integrated into nginx using shared certs?

**Comment by ToddKopriva** [comment]
@ameer00 , I'm tagging you so that you see this request regarding one of your tutorials.

**Comment by anandsunku** [comment]
i would like to have a basic tutorial for coming up with nodejs and ssl support
