### ISSUE TITLE
Xamarin Forms + Google Cloud Datastore + Cloud Storage

### ISSUE THREAD

**Issue by waghekapil** [GoogleCloudPlatform/community#755]
Hello,

I want to connect with Google Cloud Datastore and Cloud Storage with Xamarin Forms app. I'm very new to GCP. I'm trying with `Google.Cloud.Datastore.V1`  NuGet package for datastore but not able to do it.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
