### ISSUE TITLE
How to upload videos into google cloud storage in php using Interoperability keys?

### ISSUE THREAD

**Issue by ashok-potnuru** [GoogleCloudPlatform/community#756]
How to upload videos into cloud storage using php??

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
