### ISSUE TITLE
<script> | pixel | tag +collect information

### ISSUE THREAD

**Issue by Eugeniobm** [GoogleCloudPlatform/community#760]
Hi every body,

I have some doubts about how to collect and store an especific information.

Basically I would like to collet information from a (<script> | pixel | tag ) that I have implemented in a web site. Which tool or GCP pipeline I need to use for it.?

Eugenio B.

Thanks so much

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
