### ISSUE TITLE
Issue with docker-gcplogs-driver

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#762]
in the section 'Viewing your logs' number 2, where it says to check the 'Global' logs menu in Stackdriver Logging, this is not accurate in newer projects. 

The logs appear under 'GCE VM instance' logs for the specific instance.

**Comment by bshaffer** [comment]
I was able to reproduce this issue. The container may have changed so the default resource being logged looks like this:

```
 resource: {
  labels: {
   instance_id:  "#########"    
   project_id:  "some-project-id"    
   zone:  "us-central1-a"    
  }
  type:  "gce_instance"   
 }
```

**Comment by ToddKopriva** [comment]
Thanks, Brent.

**Comment by pietrodn** [comment]
I confirm this issue as of today. The documentation [here](https://cloud.google.com/community/tutorials/docker-gcplogs-driver) needs to be updated.

**Comment by ToddKopriva** [comment]
Thanks for that confirmation, @pietrodn .
