### ISSUE TITLE
Authentication with Gcloud

### ISSUE THREAD

**Issue by guptasakshi01** [GoogleCloudPlatform/community#766]
Hi 

I am able to authenticate using json file and also able to deploy configuration using deployment manager.
But, Is there any way of authenticating using client_id and client_secret without using json file ?

Please help.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
