### ISSUE TITLE
Issue with setting-up-postgres - "Ubuntu 14.04 LTS" is EOL on April 30th 2019

### ISSUE THREAD

**Issue by kyle-cackett** [GoogleCloudPlatform/community#769]
This article references the Ubuntu image "Ubuntu 14.04 LTS" which according to google will reach EOL on April 30th 2019. This reference should be replaced with a non-deprecated image.

**Comment by ToddKopriva** [comment]
Thanks for the suggestion.

**Comment by ToddKopriva** [comment]
fixed with this pull request:
https://github.com/GoogleCloudPlatform/community/pull/1534
