### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform

### ISSUE THREAD

**Issue by ncjones** [GoogleCloudPlatform/community#773]
The published document is truncated. It looks like the "<<EOF" might be causing the isssue.

https://cloud.google.com/community/tutorials/managing-gcp-projects-with-terraform
https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/managing-gcp-projects-with-terraform/index.md

**Comment by ToddKopriva** [comment]
Thanks for catching that.

**Comment by ToddKopriva** [comment]
I have a fix in progress with this PR:
https://github.com/GoogleCloudPlatform/community/pull/776
