### ISSUE TITLE
The Elixir-GCE tutorial should avoid mounting the app as a docker volume

### ISSUE THREAD

**Issue by dazuma** [GoogleCloudPlatform/community#774]
The tutorial tutorials/elixir-phoenix-on-google-compute-engine uses docker to cross-compile an application release, but does so by mounting the app directory as a volume. We received feedback that this is problematic, and may have resulted in trouble for a customer trying to follow the tutorial. This part of the tutorial should be modified instead to COPY the app directory into the docker image, and use `docker cp` to extract the resulting build artifact.

Reference: https://elixirforum.com/t/deployment-to-google-compute-engine/20409/58

**Comment by dazuma** [comment]
Please feel free to assign this to me, btw. (I'm filing this issue to document it, but I don't have permissions to set the assignee.)

**Comment by ToddKopriva** [comment]
It's all yours.

**Comment by AzimLord** [comment]
Any update on this?

**Comment by voshawn** [comment]
Hey @dazuma! This is a great tutorial and I would love to see this issue updated as well. Does this guide over at Distillery address this issue? It uses the cp command: https://hexdocs.pm/distillery/guides/building_in_docker.html 

In addition, with Elixir 1.9's Release feature, it would be nice to see if we can swap out Distillery (might be a separate issue). 

I might have some time to take a stab at it next week and can share any notes.

**Comment by dazuma** [comment]
Updated the tutorial.
