### ISSUE TITLE
Issue with run-laravel-on-appengine-standard

### ISSUE THREAD

**Issue by A-Marzouk** [GoogleCloudPlatform/community#777]
I have followed the steps to deploy laravel app, I still get this error : 

There is no existing directory at "/storage/logs" and its not buildable: Read-only file system

I have tried every solution I found online, but nothing helped! I will be grateful for any help.

**Comment by ToddKopriva** [comment]
@bshaffer , I'm tagging you so that you can see this issue submitted about a tutorial that you contributed.

**Comment by wrimik** [comment]
For view cache I had to dynamically set the compiled path in the the config/views.php - maybe making the path dynamic in the config/logging.php with help
`
...
    'compiled' => env(
        'APP_STORAGE',
//        storage_path(), //'VIEW_COMPILED_PATH',
        realpath(storage_path('framework/views'))
    ),
///
`

**Comment by bshaffer** [comment]
Try adding this to your `app.yaml` under `env_variables`:

```yaml
env_variables:
  # ...
  LOG_CHANNEL: stderr
```

Alternatively, follow the instructions later in the tutorial to integrate with Stackdriver Logging. Either of these should fix your issue.

**Comment by ToddKopriva** [comment]
@A-Marzouk , did you try the suggestion from @bshaffer ? 

Because his suggestion indicates that the problem should not occur if you follow steps later in the same tutorial, I am closing this issue. Let me know if this doesn't work for you and this issue should be reopened.
