### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by prateek-infoobjects** [GoogleCloudPlatform/community#795]
Can you also please clearly mention the steps to deploy on appengine standard environment please?

Thanks in advance!

**Comment by ToddKopriva** [comment]
Prateek, the Issues section of this GitHub repository is not the best place to get questions like this answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
