### ISSUE TITLE
Issue with gcp iot core gateway rpi tutorial 

### ISSUE THREAD

**Issue by bharatchauhan51** [GoogleCloudPlatform/community#800]
I was trying the cloud IOT core and can not successfully run the system entirely even after trying for a lot of times.
Ive been through the documentation a couple of times. Need help.

https://cloud.google.com/community/tutorials/cloud-iot-gateways-rpi

**Comment by ToddKopriva** [comment]
As I mentioned on your other post, the Issues section of this GitHub repository is not a good place to get troubleshooting help.

I recommend bringing your issue to one of the forums here:
https://cloud.google.com/support/docs/community

Many members of the GCP experts, including Google employees, help out on those forums.

**Comment by bharatchauhan51** [comment]
Thanks sir
