### ISSUE TITLE
Issue with cloud-iot-gateways-rpi

### ISSUE THREAD

**Issue by stevebramhall** [GoogleCloudPlatform/community#803]
Issue Description
An error resulted when sourcing run-gateway due to a syntax on line 277 for file cloudiot_mqtt_gateway.py

I needed to add parenthesis around the whole print statement.

BEFORE (error): 
print "[%s]: From Address %s:%s receive data: %s" % (ctime(), client_addr[0], client_addr[1], data)

AFTER (no error): 
print ("[%s]: From Address %s:%s receive data: %s" % (ctime(), client_addr[0], client_addr[1], data))

**Comment by ToddKopriva** [comment]
@hongalex , I'm tagging you so that you can see this issue reported about a tutorial that you submitted.

**Comment by hongalex** [comment]
Hi,

Thanks for the feedback! The reason why you encountered that error is likely because you are using python3 which changed `print` to be a function and is not compatible with python2 print statements. The article specifies needing to use python2, but we can keep this issue open until the code is updated to be compatible with both versions of python.

**Comment by stevebramhall** [comment]
Alex, got it, thank you!
I have another question. I have followed every instruction (have tested the Raspberry Pi/DHT22 functionality in standalone mode) but publishing telemetry through the Gateway is not working. The console on the Raspberry Pi holds steady at "Waiting for response" and the Gateway console continues to print "connect status False". Any ideas? Thanks in advance for your help!

**Comment by stevebramhall** [comment]
Ok I think I know my issue. I thought the sensor+Pi together were one device but the DHT22 sensor is the device and the Pi is the Gateway.

**Comment by hongalex** [comment]
So if the gateway output is constantly printing out "connect status False", that generally means that the gateway is not connected to Cloud IoT Core properly. The gateway code should start independently of the devices, and should look something like this:

```
Creating JWT using RS256 from private key file rsa_private.pem
connect status False
on_connect Connection Accepted.
on_subscribe: mid 1, qos (1,)
Unable to find key 1
Received message 'test' on topic '/devices/test-gateway/config' with Qos 1
Nobody subscribes to topic /devices/test-gateway/config
Received message 'test' on topic '/devices/test-gateway/config' with Qos 1
Nobody subscribes to topic /devices/test-gateway/config
```

With that said, for troubleshooting, I recommend posting on a forum like StackOverflow with the `google-cloud-iot` tag, where it will have better visibility and where others (including myself) monitor. The issues for this repo are more for tracking specific issues with the tutorials themselves :)

**Comment by ToddKopriva** [comment]
I agree with Alex that the forums are a better place for troubleshooting.

We provide some links to useful forums here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

I'm going to close this issue, but feel free to continue the conversation here if you need to, or if you want to give a link to a forum thread where you're continuing the conversation.
