### ISSUE TITLE
Tutorial request: Connecting Google Sheets to Cloud SQL (postgres)

### ISSUE THREAD

**Issue by vyayoy** [GoogleCloudPlatform/community#809]
I have a google sheet that I want uploaded or deployed to Cloud SQL postgres as a table(s). Any changes or updates on the google sheets should be reflected on the Cloud SQL postgres.

**Comment by vyayoy** [comment]
Used BigQuery for this instead. Thanks!

**Comment by ToddKopriva** [comment]
Thanks for following up with what worked for you.
