### ISSUE TITLE
Issue with data-science-preprocessing

### ISSUE THREAD

**Issue by baseonballs** [GoogleCloudPlatform/community#818]
#Issue Description:
- Sample seems to require python2 environment; should be noted as such in walkthrough
- Code execution fails at running the clean.py 
Please note the <your-project-id> is correctly bound to the billable gcp proiect. 

Running the data-science-proprocessing results in an error @ the step:
> python clean.py meteors.json your-project-id:meteor_dataset.cleansed
------------------------------
Command Execution Yields:
(venv) user-id:data-science-prepprocessing user-id$ python clean.py gs://$BUCKET/meteors.json $PROJECT:meteor_dataset.cleansed     --project $PROJECT     --job_name $PROJECT-meteors     --runner DirectRunner     --staging_location $BUCKET/staging     --temp_location $BUCKET/temp     --output $BUCKET/output
Traceback (most recent call last):
  File "clean.py", line 199, in <module>
    main(args.src_path, args.dest_table, pipeline_args=pipeline_args)
  File "clean.py", line 138, in main
    value = p | 'Read JSON' >> apache_beam.Read(JsonFileSource(src_path))
AttributeError: 'module' object has no attribute 'Read'
(venv) user-id:data-science-prepprocessing user-id$

**Comment by ToddKopriva** [comment]
@jerjou , could you have a look at this report of a potential problem in a tutorial that you contributed?

**Comment by ToddKopriva** [comment]
closing issue for now, since document is being archived
