### ISSUE TITLE
Issue with run-wordpress-on-appengine-standard

### ISSUE THREAD

**Issue by adebnar** [GoogleCloudPlatform/community#820]
When running 
php vendor/bin/wp-gae create

I receive the following error 

> We will use the directory: wordpress-project. If the directory exists, we will overwrite the contents. Do you want to continue? (Y/n)y
> Downloading the WordPress archive...
> Re-using a directory /home/andrew/wordpress-project.
> Downloaded the WordPress archive.
> Re-using a directory /home/andrew/wordpress-project.
> Downloading the GCS plugin...
> PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /home/andrew/vendor/google/cloud-tools/src/Utils/Project.php:83
> Stack trace:
> #0 /home/andrew/vendor/google/cloud-tools/src/Utils/WordPress/Project.php(221): Google\Cloud\Utils\Project->downloadArchive('GCS plugin', 'https://downloa...', '/home/andrew/wo...')
> #1 /home/andrew/vendor/google/cloud-tools/src/Utils/WordPress/wp-gae(63): Google\Cloud\Utils\WordPress\Project->downloadGcsPlugin()
> #2 /home/andrew/vendor/symfony/console/Command/Command.php(253): Closure->{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #3 /home/andrew/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #4 /home/andrew/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\Command), Object(Symfony\ in /home/andrew/vendor/google/cloud-tools/src/Utils/Project.php on line 83

**Comment by ToddKopriva** [comment]
@bshaffer , could you have a look at this report of a potential issue with a tutorial that you submitted?

**Comment by justAnotherDev** [comment]
+1. Having this issue as well, any solution? The [tutorial](https://cloud.google.com/community/tutorials/run-wordpress-on-appengine-standard#setup) specifically mentions installing `zip`, but does not explain how:

**Note: If you receive an error about extensions, install phar and zip PHP extensions and retry.**

**Comment by flashadvocate** [comment]
`sudo apt-get install php7.2-zip` ought to get you past this.

**Comment by bshaffer** [comment]
You need to install and enable the PHP zip extension. This can be done using pecl (`pecl install zip`), or can be compiled when you install PHP using the `--with-libzip=DIR` flag. If you're on MAC, PECL will come installed if you install PHP via homebrew (`brew install php@7.1`).

https://www.php.net/manual/en/zip.installation.php
