### ISSUE TITLE
Issue with nginx-ingress-gke

### ISSUE THREAD

**Issue by ThanhTuNguyen** [GoogleCloudPlatform/community#824]
I follow this tutorial: https://cloud.google.com/community/tutorials/nginx-ingress-gke

But it didn't work. It's can’t be reached and refuse to connect. Anyone help.

**Comment by ToddKopriva** [comment]
@ThanhTuNguyen , the Issues section of this GitHub repository is not the best place to get troubleshooting help.

I recommend bringing your issue, with as much detail as possible, to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

If you have specific feedback about this tutorial, please do give it here.
