### ISSUE TITLE
Deploy a vuejs app bootstrapped with vue cli

### ISSUE THREAD

**Issue by geniusit** [GoogleCloudPlatform/community#827]
I like to start my viejs project with https://cli.vuejs.org

However when I try to deploy it to AppEngine I have the following error :

**Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.**

This is because a start script was't found by Appengine : 

Error: Cannot find module '/srv/server.js' 

I tried to follow these instructions with no success : 

https://mozy-ok.hatenablog.com/entry/2018/11/08/132904

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
