### ISSUE TITLE
Issue with run-laravel-on-appengine-flexible

### ISSUE THREAD

**Issue by kwaychal** [GoogleCloudPlatform/community#847]
Issue Description

I follow the steps perfectly it works the first step.

but when I use a migration table is created migration is successful.
but while deploying following error occured.
Step #1: > chmod -R 755 bootstrap/cache
Step #1: > php artisan cache:clear
Step #1: 
Step #1: In Connection.php line 664:
Step #1:                                                                                
Step #1:   SQLSTATE[HY000] [2002] No such file or directory (SQL: delete from `cache`)  
Step #1:                                                                                
Step #1: 
Step #1: In Connector.php line 70:
Step #1:                                                     
Step #1:   SQLSTATE[HY000] [2002] No such file or directory  

after removing php artisan cache:clear from composer.json
app deploy succesful but on web browsing it shows error 500

**Comment by kwaychal** [comment]
![Screenshot 2019-04-17 at 10 56 49 PM](https://user-images.githubusercontent.com/43039528/56308258-78092580-6164-11e9-905e-1166c62bc66b.png)
![Screenshot 2019-04-17 at 10 56 49 PM](https://user-images.githubusercontent.com/43039528/56308268-7dff0680-6164-11e9-881d-034eb2920df5.png)

**Comment by kwaychal** [comment]
![Screenshot 2019-04-17 at 10 56 17 PM](https://user-images.githubusercontent.com/43039528/56308284-8e16e600-6164-11e9-9f40-3dc2e74c7ea1.png)

**Comment by ToddKopriva** [comment]
@bshaffer : Could you have a look at this issue regarding a tutorial that you contributed?

@kwaychal : The Issues section of this GitHub repository is not the best place to get troubleshooting help. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
