### ISSUE TITLE
mount-path not being respected - gcloud beta compute instances create-with-container

### ISSUE THREAD

**Issue by millergarym** [GoogleCloudPlatform/community#849]
Trying to create a disk and mount it to /var/lib/docker .
The disk gets created and mounted by not a the specified path.

```
gcloud beta compute  \
  instances create-with-container ${NAME} \
...
  --image=cos-stable-73-11647-163-0 \
  --image-project=cos-cloud \
  --create-disk=mode=rw,auto-delete=yes,size=100,type=projects/XXX/zones/australia-southeast1-b/diskTypes/pd-ssd,name=${NAME}docker,device-name=${NAME}docker \
  --container-image=asia.gcr.io/xxx/yyy \
  --container-mount-disk=mount-path=/var/lib/docker,name=${NAME}docker,mode=rw \
  --labels=container-vm=cos-stable-73-11647-163-0
```

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
