### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by colinbarr1965** [GoogleCloudPlatform/community#850]
Issue Description
account accessed again by michael crawford and his team who have taken every cent from all my google accounts including google cloud please can someone assist

**Comment by ToddKopriva** [comment]
Colin, the Issues section of this GitHub repository is for reporting issues with the community tutorials in this repository.

I recommend bringing your question to Google Support through the channels described here:
https://cloud.google.com/support-hub/

**Comment by ToddKopriva** [comment]
If your question is a billing or account question, it's best to bring it here:
https://support.google.com/cloud/contact/cloud_platform_billing/
