### ISSUE TITLE
AppEngine Tasks with Django

### ISSUE THREAD

**Issue by geoffwalmsley** [GoogleCloudPlatform/community#854]
Problems with the documentation for tasks on app engine mean we haven't been able to deploy tasks for our app. This is an important piece of functionality for many applications, so it would be really helpful to have some detailed guidance on setting up push and pull tasks with python

**Comment by ToddKopriva** [comment]
Are you requesting a tutorial on this site about setting up push and pull tasks with Python?

Can you give more infomation about the "problems with the documentation for tasks on app engine" that are blocking you? Have you submitted a bug report about those problems? Here is information about submitting bug reports:
https://cloud.google.com/support/docs/issue-trackers

In general, the fastest way to get help with questions like this isn't the Issues section of this GitHub repository. For your immediate needs, I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
