### ISSUE TITLE
Issue with using-cloud-vpn-with-strongswan

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#857]
https://cloud.google.com/community/tutorials/using-cloud-vpn-with-strongswan

This is an awesome article. Thank you for putting this together
I found I needed to ensure that the network with the strongswan instance needed port
udp:500,
udp-4500
protocol: esp

opened.
Might be a good idea to document that.

[Details redacted. Google employees see b/130900898 for more information.]

**Comment by ToddKopriva** [comment]
@Civil , could you have a look at this issue about a tutorial that you contributed?

**Comment by Civil** [comment]
Technically, the tutorial talks about using Strongswan on the on-prem side (as for GCP side it will also require extra work, like something that will add routes on a GCP side). There is a pre-requirement mentioned in the doc:
"Your on-premises firewall allows UDP port 500, UDP port 4500, and ESP packets."

I would say it should be a feature request to add a section about using strongswan to connect from GCP to something else and there I can mention `gcloud` commands to add required firewall rules and publish a script.

**Comment by ToddKopriva** [comment]
Thanks for the response. I'll close this bug report and leave it to you whether you want to add a section with the additional information that you mentioned.
