### ISSUE TITLE
Issue with run-spring-petclinic-on-app-engine-cloudsql

### ISSUE THREAD

**Issue by gunjan-oberoi** [GoogleCloudPlatform/community#863]
Issue Description

Hello, 
I do not see the 'mysql' profile in pom.xml.
Can you please help.

**Comment by ToddKopriva** [comment]
The pom.xml file does not include the 'mysql' profile. The updated pom.xml file includes the Cloud SQL MySQL Socket Factory.

In general, the Issues section of this GitHub repository is not the best place to get troubleshooting assistance.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
