### ISSUE TITLE
Connect to Snowflake DB using Cloud Data Fusion

### ISSUE THREAD

**Issue by gdgworkoutfun** [GoogleCloudPlatform/community#864]
Unable to determine source plugins for Snowflake DB in Cloud DataFusion, are there any good solutions?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
