### ISSUE TITLE
Sigfox-gw python code error

### ISSUE THREAD

**Issue by JulianSensand** [GoogleCloudPlatform/community#867]
When running 
`python sigfox-api.py --callbacks create`
I get the following output:
```
Traceback (most recent call last):
  File "sigfox-api.py", line 247, in <module>
    main(sys.argv)
  File "sigfox-api.py", line 239, in main
    cf_service, cf_auth, callbacks_config_file)
  File "sigfox-api.py", line 161, in create_callbacks
    callbacks.append(dict_to_callback(d, cf_data, cf_service, name, cf_auth))
  File "sigfox-api.py", line 202, in dict_to_callback
    callback = swagger_client.CallbackCreation(
AttributeError: 'module' object has no attribute 'CallbackCreation'
```
I've followed all the steps outlined at https://cloud.google.com/community/tutorials/sigfox-gw, and have re-performed steps 1-5 under 'Generating the Sigfox API V2 Python client' but that didn't help.

Running on
- macOS 10.13.6
- python 2.7.16

NOTE: I switched to python2 from 3.7 in my venv as I got this error when using python 3:
/Users/xxx/git/community/tutorials/sigfox-gw/venv/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "sigfox-api.py", line 22, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by ToddKopriva** [comment]
@lepistom , can you have a look at this issue reported about a tutorial that you contributed?

**Comment by lepistom** [comment]
Hi, the issue is in the upstream dependency - the Sigfox API code repository. Sigfox have a bug in the code, which prevents the compilation of the Python Sigfox API client with swagger. More information: the Sigfox API V2 doc JSON contains an unescaped: ' which triggers an error. We cannot generate a Python client with generator.swagger.io now because of that. The file is: swagger_client/models/bulk_device_asynchronous_request.py", line 51

We have asked Sigfox to look into it, fix the bug, and push an updated version of their API. Until they do, this tutorial's steps will not work.

Meanwhile there is a workaround. Please email me at markku@google.com for a temporary fix if this Sigfox API definition bug prevents you from compiling the Python API client.

**Comment by JulianSensand** [comment]
Hi @lepistom, thanks for your response. As this is a sigfox bug and not with your code, I will close this issue.

**Comment by ToddKopriva** [comment]
Thanks for following up, Marrku.

**Comment by Neylton-Nascimento** [comment]
Hi, I am facing  the same issue. Is the mentioned workaround available? Can you please share it if avaiable?

**Comment by fiska0210** [comment]
Hi, I also encountered the same problem. Could you please share the workaround if it was available? Thanks.

**Comment by Neylton-Nascimento** [comment]
Hi All,

any feedback for the workaround?

**Comment by piovewira** [comment]
hii all
hii. i follow the tutorial https://cloud.google.com/community/tutorials/sigfox-gw. i have an issued when try follow the step. error when i generated python client from sigfox api v2.
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"https://support.sigfox.com/api/apidocs"}' https://generator.swagger.io/api/gen/clients/python

the error code is 400, type: unknown , message: bad input

anybody know what the problem and solution

**Comment by ChamacoKiller** [comment]
I supposed you are in windows, thats because the error comes up to you (the same happened to me), follow this solution: 

https://develop.zendesk.com/hc/en-us/articles/360001068567-Installing-and-using-cURL

**Comment by ChamacoKiller** [comment]
Has anyone found a solution for the sigfox bug yet? I also have the same error: 

Traceback (most recent call last):
  File "sigfox-api.py", line 247, in <module>
    main(sys.argv)
  File "sigfox-api.py", line 239, in main
    cf_service, cf_auth, callbacks_config_file)
  File "sigfox-api.py", line 161, in create_callbacks
    callbacks.append(dict_to_callback(d, cf_data, cf_service, name, cf_auth))
  File "sigfox-api.py", line 202, in dict_to_callback
    callback = swagger_client.CallbackCreation(
AttributeError: 'module' object has no attribute 'CallbackCreation'

**Comment by mfalkvidd** [comment]
> Hi, the issue is in the upstream dependency - the Sigfox API code repository. Sigfox have a bug in the code, which prevents the compilation of the Python Sigfox API client with swagger. 

I tried to locate the problem, but the validator at https://validator.swagger.io/ says that https://support.sigfox.com/api/apidocs is valid. Can the definition be valid and still contain unescaped ' ?

**Comment by ToddKopriva** [comment]
See PR #1225 for updates to the Sigfox tutorial that are meant to address this issue.
