### ISSUE TITLE
Send soil moisture sensor data from Arduino MKR FOX & Sim 7000e Module to Google Cloud Platform using MQTT on the module 

### ISSUE THREAD

**Issue by chilu18** [GoogleCloudPlatform/community#875]
Arduino MKR Fox 1200 - https://store.arduino.cc/arduino-mkrfox1200
https://www.waveshare.com/wiki/SIM7000E_NB-IoT_HAT
https://www.itead.cc/wiki/Moisture_Sensor

**Comment by chilu18** [comment]
This is for areas where Sigfox coverage is not available. The GPRS(EDGE) module would be the module used to send data from the Arduino via MQTT to GCP.

**Comment by ToddKopriva** [comment]
Chilumba, is this a request for a tutorial on this subject. I've tagged this issue as a tutorial request, because that is what it seems to be, but I just wanted to make sure that I understood you correctly.

**Comment by chilu18** [comment]
Hello Todd, yes it is a tutorial request. Thanks for understanding.

**Comment by ToddKopriva** [comment]
This tutorial covers a similar situation and should be a good starting point for you:
https://cloud.google.com/community/tutorials/ardu-pi-serial-part-1
