### ISSUE TITLE
AVR-IOT

### ISSUE THREAD

**Issue by teransantiago** [GoogleCloudPlatform/community#876]
Hello, 
There is an AVR-IOT board, but the Microchip tutorial is not working, would you mind to clarify it just to send, data from a microprocessor to the Google Cloud. it would be awesome!

**Comment by ToddKopriva** [comment]
You say that a tutorial is not working. Are you referring to a tutorial on the GCP Community site? If so, which one?

Is this a request for a new tutorial on the GCP Community site?
