### ISSUE TITLE
Issue with run-wordpress-on-appengine-standard

### ISSUE THREAD

**Issue by flashadvocate** [GoogleCloudPlatform/community#877]
When attempting to resolve the `Failed opening required 'google/appengine/api/urlfetch_service_pb.php'` error, the suggested solution is `$ export WP_CLI_PHP_ARGS='-d include_path=vendor/google/appengine-php-sdk'`.

The problem with this is that you are never instructed to install this dependency anywhere in the tutorial. When you do install the package via composer, the plugin still doesn't seem to be able to find the path...

Not sure if anyone else is running into this particular issue, but the tutorial itself could use some fine-tuning. It also doesn't appear that anyone is actively maintaining the appengine-wordpress-plugin repository.

**Comment by ToddKopriva** [comment]
@bshaffer , could you have a look at this issue regarding a tutorial that you contributed?

**Comment by bshaffer** [comment]
I cannot duplicate this. I went through the whole tutorial successfully and ran the `vendor/bin/wp` commands. I also searched the codebase and could not find any reference to `urlfetch_service_pb`.

@flashadvocate can you provide the output for the command you're running with the full stack trace?

**Comment by ToddKopriva** [comment]
Since this doesn't seem to be a problem with the tutorial, I'm going to close this issue.

In general, the Issues section of this GitHub repository is not the best place for troubleshooting. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by flashadvocate** [comment]
Just to follow up - I was able to get this working, and @bshaffer was correct. The issue rested with an outdated plugin that is actually no longer even needed. Thanks for the help, and sorry for the premature report!

**Comment by ToddKopriva** [comment]
I'm glad that you got it sorted. Don't worry about the issue report; better to ask for help than not.
