### ISSUE TITLE
Unable to get this tutorial to work

### ISSUE THREAD

**Issue by paragc** [GoogleCloudPlatform/community#888]
https://cloud.google.com/community/tutorials/cloud-functions-twilio-voice-record
I deployed the code as cloud functions. One of the cloud functions fails to load its dependencies. Is the tutorial still valid?

Thanks,
P

0{
 insertId:  "000000-920a22af-66d9-42f1-94af-41dc086449f1"  
 labels: {…}  
 logName:  "projects/polar-office-241404/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp:  "2019-05-24T23:51:04.586727976Z"  
 resource: {…}  
 severity:  "ERROR"  
 textPayload:  "TypeError: require(...) is not a function
    at exports.getRecording (/srv/index.js:44:51)
    at /worker/worker.js:783:7
    at /worker/worker.js:766:11
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)"  
 timestamp:  "2019-05-24T23:50:58.109Z"  
 trace:  "projects/polar-office-241404/traces/2a55c20440b35ef410d95a026b88ed32"  
}

**Comment by ToddKopriva** [comment]
I'll get someone to look into this.

**Comment by variance02** [comment]
Hi there - is there an update here? I'm getting the same error.

**Comment by ToddKopriva** [comment]
It looks like the problem is this line:

    const storage = require('@google-cloud/storage')();

See this change:
https://github.com/googleapis/nodejs-storage/releases/tag/v2.0.0

That makes it seem like the change needed is to remove the `()` at the end of the line, for this:

    const storage = require('@google-cloud/storage');

Try that out. If that works for you, I'll make the fix in the tutorial.
