### ISSUE TITLE
Issue with cloud-functions-oauth-gmail

### ISSUE THREAD

**Issue by ChaitanyaGollapudi** [GoogleCloudPlatform/community#895]
Trying to implement the below tutorial
https://cloud.google.com/community/tutorials/cloud-functions-oauth-gmail

I am not able to add 
Authorized JavaScript origins: 
https://[YOUR_GCF_REGION]-[YOUR_GCP_PROJECT_ID].cloudfunctions.net/oauth2callback
to my oauth credentials.

As it can't contain a wildcard (https://*.example.com) or a path (https://example.com/subdir)

**Comment by ToddKopriva** [comment]
Are you replacing [YOUR_GCF_REGION] with your region and replacing [YOUR_GCP_PROJECT_ID] with your project ID?

Example:
https://us-central1-myprojectid.cloudfunctions.net/oauth2callback



In general, the Issues section of this GitHub repository is not the best place to get troubleshooting help. I recommend bringing troubleshooting questions to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by ChaitanyaGollapudi** [comment]
> Are you replacing [YOUR_GCF_REGION] with your region and replacing [YOUR_GCP_PROJECT_ID] with your project ID?
> 
> Example:
> https://us-central1-myprojectid.cloudfunctions.net/oauth2callback
> 
> In general, the Issues section of this GitHub repository is not the best place to get troubleshooting help. I recommend bringing troubleshooting questions to one of the forums described here:
> https://cloud.google.com/support/docs/community
> 
> Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by ChaitanyaGollapudi** [comment]
I did replace region and project id. Thanks for thr information. I am going to post it in forum now. Thanks

**Comment by ToddKopriva** [comment]
Happy to help. I hope that you get it sorted. If you learn anything that might be of value to others using this tutorial, don't hesitate to report back here.
