### ISSUE TITLE
open cv integration with google cloud 

### ISSUE THREAD

**Issue by laksh-lp** [GoogleCloudPlatform/community#901]
i have a open cv python code that runs perfectly on my local machine. it computes on live video feed via webcam and detects face and then saves the video to the local machine. now i want to put it to cloud. like run the code on google compute engine and then save the video in google storage bucket. can you help me out with this ???

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
