### ISSUE TITLE
Tutorial on Firebase Cloud Function with Kotlin

### ISSUE THREAD

**Issue by sodiqOladeni** [GoogleCloudPlatform/community#917]
Any tutorial on the above topic will be appreciated, specifically on sending Notification when Firestore data changes. The tutorial I have seen are writing in Javascript. Thanks

**Comment by Timtech4u** [comment]
> Any tutorial on the above topic will be appreciated, specifically on sending Notification when Firestore data changes. The tutorial I have seen are writing in Javascript. Thanks

Hi @sodiqOladeni , if you're looking for something on Cloud Function, kindly checkout [this](https://cloud.google.com/community/tutorials/slack-bot-cloud-functions-scheduler)

@amoora can we collaborate on this?

**Comment by sodiqOladeni** [comment]
Thanks @Timtech4u, the tutorial you pointed at was written in js, am looking for the one written in Kotlin. Thanks

**Comment by Timtech4u** [comment]
> Thanks @Timtech4u, the tutorial you pointed at was written in js, am looking for the one written in Kotlin. Thanks

Hi @sodiqOladeni , currently Firebase Cloud Functions only supports JavaScript/TypeScript, however, you could integrate Kotlin with any of the available [triggers](https://firebase.google.com/docs/functions)

Can you explain your use case, that will help me in coming up with something. Thanks

**Comment by sodiqOladeni** [comment]
Hello @Timtech4u , I want to be handling firebase notification on firebase event i.e onAdded and onUpdate, I don't want to be doing sending it from client because of maintainability. Google announced in recent I/O that cloud function now support Kotlin but they seem not to provide support material/documentation  Thanks for your concern.

**Comment by ToddKopriva** [comment]
Here are some documents that should get you started:

https://cloud.google.com/functions/docs/concepts/jvm-langs

https://firebase.google.com/docs/functions/callable#kotlin+ktx
