### ISSUE TITLE
Tutorial run-expressjs-on-google-app-engine doesn't work

### ISSUE THREAD

**Issue by Nearoo** [GoogleCloudPlatform/community#920]
Fails in the cloud with

    Error: Cannot find module 'express'

**Comment by Nearoo** [comment]
[Link to Tutorial](https://cloud.google.com/community/tutorials/run-expressjs-on-google-app-engine)

**Comment by ToddKopriva** [comment]
Thanks for the report.

**Comment by tjwebb** [comment]
I was not able to reproduce this issue

**Comment by ToddKopriva** [comment]
Thanks, Travis.

I'm going to close this issue report for now.

Silas, if you need help, I recommend bringing your issue to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

If you are certain that there is a problem with this tutorial, and you can give more detailed information about how to reproduce the problem, please re-open this issue report and let us know.
