### ISSUE TITLE
How to handle local data files for submitting a training job?

### ISSUE THREAD

**Issue by datistiquo** [GoogleCloudPlatform/community#924]
I hope i can get a simple answer to this very simple question. On stackoverflow I don't get any answer. This is simple but it pulls back my work for days now.

I want to submit a custom keras model with training data as json. I have my folder like

```
trainer
  -- model.py
  -- task.py
  -- training_data.json
```
Training locally works but submitting to ai cloud fails because of (from the logs):

`master-replica-0 Traceback (most recent call last): File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "main", mod_spec) File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals) File "/root/.local/lib/python3.5/site-packages/trainer/task.py", line 162, in with io.open('tokenizer.json',encoding='utf-8') as f: FileNotFoundError: [Errno 2] No such file or directory: 'training_data.json'`

How do I handle data needed in task.py? Do I have to put the directionary folder for the cloud bucket instead of the path like above in the log?

**Comment by datistiquo** [comment]
Found a solution.

http://liufuyang.github.io/2017/04/02/just-another-tensorflow-beginner-guide-4.html

**Comment by ToddKopriva** [comment]
Great! I'm glad that you got it sorted.
