### ISSUE TITLE
Deploy Nodejs App with Angular frontend?

### ISSUE THREAD

**Issue by aman1403** [GoogleCloudPlatform/community#925]
I didn't find any tutorial on it.I have 2 ports 3000 and 4200 for backend and frontend respectively.
But while deploying ,It is giving me an error that ng :Not found .My app.yaml looks like this:
runtime: nodejs
env: flex
I don't know how to handle two ports as I am using two commands to run my Project :
1) ng serve
2) npm run start:server
In Package.json file It reads 1st command ng serve and throw an error that ng : Not found.
I don't know how to solve it?
Any suggestions will be appreciated

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
