### ISSUE TITLE
A way to automate spark/shell/hive actions through Apache Oozie

### ISSUE THREAD

**Issue by akhileshborgaonkar** [GoogleCloudPlatform/community#929]
Looking for a way to use Apache Oozie on GCP server instance. The Oozie workflow will help to run spark actions through Dataproc and have better logging abilities.

**Comment by medb** [comment]
You can use [Google Cloud Dataproc](https://cloud.google.com/dataproc) with [Oozie initialization action](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/oozie) to achieve this.

**Comment by ToddKopriva** [comment]
Thanks for that, @medb .
