### ISSUE TITLE
Issue with mongodb-atlas-visionapi-nodejs

### ISSUE THREAD

**Issue by hrntrn** [GoogleCloudPlatform/community#932]
Hi there,
I follow your description step by step on https://cloud.google.com/community/tutorials/mongodb-atlas-visionapi-nodejs.  The example fnihsed but when I made test application give a bug. I don't know how can we solve. I run node server.js. See on web page. The page is opening. Click to button.  After that take the bug.
Issue Description

Shell which are not supported by the vision.googleapis.com. We recommend that most server applications use service accounts instead. For more information about service accounts and how to use them in your application
    at Http2CallStream.call.on (/home/cloudharun/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/home/cloudharun/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
![Opera Anlık Görüntü_2019-06-29_180037_console cloud google com](https://user-images.githubusercontent.com/16059472/60385928-e0934d80-9a97-11e9-8cb2-5ae668c60be9.png)

**Comment by ToddKopriva** [comment]
@smithkent , I'm tagging you so that you can see this bug reported against a tutorial that you submitted.
