### ISSUE TITLE
Issue with run-laravel-on-appengine-standard

### ISSUE THREAD

**Issue by SamuelAlev** [GoogleCloudPlatform/community#939]
Issue Description:

Hello,
I succeeded on deploying Laravel in Flexible mode (working perfectly) but I can't figure out how on Standard mode as I don't have access to the "public" folder once I deployed it, so my website doesn't have any ressources (CSS, images, videos, ...).

Here is my app.yaml for flex which is deployed and running : https://pastebin.com/5bGswhxR

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
