### ISSUE TITLE
Google Elixir Cloud Old Mix Commands failing 

### ISSUE THREAD

**Issue by fantypants** [GoogleCloudPlatform/community#940]
hello everyone, trying to use the following tutorial:

```https://cloud.google.com/community/tutorials/elixir-phoenix-on-google-app-engine```

It keeps failing at:
```tep #1: Step 11/14 : RUN mix release --env=prod --verbose
Step #1:  ---> Running in 7f99feb86be5
Step #1: ** (Mix) The task "release" could not be found. Did you mean "release.version"?
Step #1: The command '/bin/sh -c mix release --env=prod --verbose' returned a non-zero code: 1
```

located in file: 
```
https://github.com/GoogleCloudPlatform/elixir-runtime/blob/master/elixir-generate-dockerfile/app/Dockerfile-release.eex
```
Specifically: line 130
```
## Create the release.
RUN mix release --env=<%= @mix_env %> --verbose
```

Anyone else tried it recently?

**Comment by ToddKopriva** [comment]
@dazuma , could you have a look at this report of an issue with a tutorial that you submitted?

**Comment by fantypants** [comment]
Due to the release of 1.9 the command 'mix release.init' for distillery is now 'mix distillery.init' as mix has its own release system integrated.

Ideally, a tutorial on how to build the custom docker containers for elixir would be ideal, then we could run seeds.exs at build time as well.

**Comment by fantypants** [comment]
Also reverted back and tested with elixir 1.8 and distillery 1.5 and the tutorial works, so its 99% the distillery changes with mix

**Comment by ToddKopriva** [comment]
Thanks for that additional information.

**Comment by johninvictus** [comment]
Can we create a custom elixir runtime to bypass this issue?

**Comment by dazuma** [comment]
I am working on updating the Elixir runtime to handle the various cases (Distillery < 2.1.0, Distillery >= 2.1.0, and Elixir 1.9 without Distillery). Should be ready in a day or two.

**Comment by johninvictus** [comment]
Thanks, we will all appreciate

**Comment by ToddKopriva** [comment]
Thanks, Daniel.

**Comment by dazuma** [comment]
The Elixir runtime has now been updated, and should fix the task-not-found issue with Distillery 2.1. Leaving this open to update the text of the tutorial to call for Distillery 2.1 and use the new `mix distillery.init` command.

**Comment by fantypants** [comment]
Solid work, will make things smooth as butter :)

**Comment by ToddKopriva** [comment]
With Daniel's fix, I'm going to close this issue. Feel free to comment if there's still a problem.
