### ISSUE TITLE
Issue with sigfox-gw

### ISSUE THREAD

**Issue by piovewira** [GoogleCloudPlatform/community#941]
hii. i have an issued when try follow the step. error when i generated python client from sigfox api v2. 
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"https://support.sigfox.com/api/apidocs"}' https://generator.swagger.io/api/gen/clients/python

the error code is 400, type: unknown ,  message: bad input

anybody know what the isuues and solution

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by ToddKopriva** [comment]
@lepistom , I'm tagging you so that you can this issue regarding a tutorial that you submitted.

**Comment by piovewira** [comment]
Thanks toddkopriva

**Comment by ToddKopriva** [comment]
@lepistom , should we close this now that PR #1225 is closed?

**Comment by lepistom** [comment]
Yes please! PR 1225 fixes these issues. We can close this
