### ISSUE TITLE
Issue with cloud-iot-gateways-rpi

### ISSUE THREAD

**Issue by kaumodaki** [GoogleCloudPlatform/community#954]
As documented, I following all the steps, However, I ending up with the following error while I am trying to perform the 'Set up your gateway' section. I am getting error at step number 12(pip install -r requirements-gateway.txt).

Error Description: ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pycparser-2.19.dist-info'
Consider using the `--user` option or check the permissions.

![1](https://user-images.githubusercontent.com/37953162/61182480-6941ea00-a651-11e9-9be0-efa15007cd66.JPG)
![2](https://user-images.githubusercontent.com/37953162/61182481-6941ea00-a651-11e9-85bf-155afa7efc11.JPG)

Please help me in resolving this issue.

Best regards,
Venu.

**Comment by ToddKopriva** [comment]
@hongalex , I'm tagging you so that you can see this issue reported against a tutorial that you submitted.

**Comment by ToddKopriva** [comment]
@kaumodaki , in case this is a more general issue with permissions for installation, you might have better luck asking the question in a different forum. The Issues section of this GitHub repository is not the best place for getting troubleshooting help. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by hongalex** [comment]
Hi @kaumodaki,

I believe your issue can be resolved if you use a virtual environment instead of installing the python packages directly on your system. I'll likely update the tutorial with the following steps to make this more clear, but you would do something like the following:

```
virtualenv env
source env/bin/activate
pip install -r requirements-gateway.txt
```

**Comment by ToddKopriva** [comment]
Thanks for following up, Alex.

**Comment by ToddKopriva** [comment]
It seems that Alex's PR #962 deals with this issue, so I'm closing this issue report.

If you find that this issue isn't resolved, re-open the issues and let us know.
