### ISSUE TITLE
Issue with run-laravel-on-appengine-[standard || flexible]

### ISSUE THREAD

**Issue by asadnafees** [GoogleCloudPlatform/community#961]
Add sections for using Cloud Build and Cloud Source Repository with Laravel.

Some GCloud commands generate a .gcloudignore that includes .gitignore. This inclusion prevents successful deployments using Cloud Build when pulling from Google Cloud Source Repostitories as some of the files ignored are needed for deployments and there are several .gitignore files present in the framework [1]. 

This .gcloudignore file has the .gitignore file commented out to prevent this from happenning.

[1] https://github.com/asadnafees/php-docs-samples/commit/a5fc6f01a839c62090a43dadc4d9c86dcc0247f5

**Comment by ToddKopriva** [comment]
@bshaffer , I tagged you so that you see this request for an improvement in a couple of tutorials that you submitted.
