### ISSUE TITLE
Unable to see CPU and Memory dashboards for Kubernetes deployments in a private cluster (Although CPU/Memory dashboard data available for containers present in deployments)

### ISSUE THREAD

**Issue by varshama** [GoogleCloudPlatform/community#966]
Production GCP Environment Issue
We have a private cluster in which there are 40+ deployments, we are unable to see CPU, memory, disk IO etc dashboard data for deployments (workloads) in GKE console.
NOTE: The aggregated data is not available.
Whereas, for containers in that deployments CPU. Memory dashboard data is available.
Could someone please help if there is anything we need to incorporate for private cluster in order to get data for deployments.

![image](https://user-images.githubusercontent.com/47240729/61452091-973c6c80-a978-11e9-9c3f-1d426545c4be.png)
IT'S URGENT, PLEASE HELP!

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get troubleshooting questions like this answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
