### ISSUE TITLE
need help with loading data to Bigquery

### ISSUE THREAD

**Issue by vsbmadhav** [GoogleCloudPlatform/community#974]
Can some one help me with understanding how I can do Incremental loads into Big query database / table for the scenario as mentioned below

Source table, say A, has 
- 10 new records
- 5 records updated
- 2 records deleted

there is some data already loaded into big query table(say BQT1) coming from table A

i would need to write a program that i can schedule to do these delta loads on a frequent basis.

thanks in advance,
MAV

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
