### ISSUE TITLE
Issue with using-stackdriver-uptime-checks-for-scheduling-cloud-functions

### ISSUE THREAD

**Issue by MrTrustor** [GoogleCloudPlatform/community#976]
This tutorial has been made obsolete by https://cloud.google.com/scheduler/docs/tut-pub-sub

**Comment by ToddKopriva** [comment]
@MrTrustor , is your recommendation that this tutorial be removed because it's obsolete, or are you suggesting some other solution?
https://cloud.google.com/community/tutorials/using-stackdriver-uptime-checks-for-scheduling-cloud-functions

@sujoyg , I'm tagging you since you are the original author of the tutorial in question, so I thought that you might want to be part of this conversation.

**Comment by sujoyg** [comment]
@ToddKopriva thank you for looping me in. I agree with @MrTrustor . My tutorial was written before Cloud Scheduler was released. It is time to deprecate my tutorial in favor of the one referenced by @MrTrustor. However, I no longer work for Cloud and will not be able to find time to do this myself. Highly appreciate any help with this.

**Comment by MrTrustor** [comment]
@ToddKopriva I don't know what's the process for community tutorials, but I can think of two solutions: either we unpublish it completely, or we add a note/warning at the top saying it's been deprecated in favor of the official Cloud Scheduler tutorial.

**Comment by ToddKopriva** [comment]
I'll move this document to the archives, which will unpublish it from cloud.google.com. The document will continue to exist here on GitHub in our archive folder, with a note at the top of the document pointing to the new document.

**Comment by ToddKopriva** [comment]
This PR moves the obsolete tutorial to the "archived" folder and adds a note at the top of the archived document to point to the new document:
https://github.com/GoogleCloudPlatform/community/pull/987

In a moment, I'll unpublish the document from the cloud.google.com/community site.

**Comment by ToddKopriva** [comment]
All fixed. The old URL now redirects to the new tutorial.
