### ISSUE TITLE
Get contacts from contacts api in firebase function

### ISSUE THREAD

**Issue by adrielwerlich** [GoogleCloudPlatform/community#988]
Hello there I´m trying to retrieve my contacts list from the contacts api using a firebase function

I´ve created a stackoverflow post (https://stackoverflow.com/questions/57345184/error-node-js-module-defined-by-file-index-js-is-expected-to-export-function-na)

It´s possible to find a working snnipet that clearly shows how to retrieve the contacts list from the contacts api inside a firebase function?

This could be considered a tutorial request submission

**Comment by ToddKopriva** [comment]
Thanks for the tutorial request.

**Comment by Timtech4u** [comment]
> Hello there I´m trying to retrieve my contacts list from the contacts api using a firebase function
> 
> I´ve created a stackoverflow post (https://stackoverflow.com/questions/57345184/error-node-js-module-defined-by-file-index-js-is-expected-to-export-function-na)
> 
> It´s possible to find a working snnipet that clearly shows how to retrieve the contacts list from the contacts api inside a firebase function?
> 
> This could be considered a tutorial request submission

I could try to write something on this soon.

**Comment by ToddKopriva** [comment]
Thanks, Timothy.

**Comment by ToddKopriva** [comment]
@Timtech4u , are you still interested in writing a tutorial along these lines?
