### ISSUE TITLE
Bokeh Serve with Flask in Google Ap Engine

### ISSUE THREAD

**Issue by BryceWayne** [GoogleCloudPlatform/community#992]
A simple canonical example which deploys a Bokeh server dashboard in a Flask web app would be great. The Bokeh + BigQuery does not work and is too complicated. It would be nice to see a Flask Web Ap with a Bokeh Server Dashboard that has Python callbacks for realtime updates. This should then be deployed on the Google App Engine. Thank you.

**Comment by BryceWayne** [comment]
I am very close to getting the Bokeh Server to work with Flask but I am not entirely sure how to put everything together. I am trying to open the 5006 port for the Bokeh Serve to be on and have the flask app reference localhost:5006 for the Bokeh server. I am attaching the GitHub repo link to clone and check.

GitHub Repo: https://github.com/BryceWayne/mlcdashboard.git

**Comment by ToddKopriva** [comment]
If you need help moving forward, I recommend bringing your questions to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by BryceWayne** [comment]
Thank you.
