### ISSUE TITLE
Issue with cloud-functions-firestore

### ISSUE THREAD

**Issue by rbannist** [GoogleCloudPlatform/community#993]
Change 'Prerequisites' --> 'Enable the Google Cloud Firestore API (Datastore mode)' to 'Enable the Google Cloud Firestore API (Firestore/Native mode)'.

**Comment by ToddKopriva** [comment]
Thanks for the report. 

If you want to create a pull request to make this change yourself, I'll review it and get it merged.

**Comment by zeroasterisk** [comment]
Thanks. I'll get to this today, if you don't.

**Comment by zeroasterisk** [comment]
@rbannist have you completed the tutorial with firestore in native mode?  When I wrote this, I picked datastore mode...  I have not done this tutorial in firestore native mode... have you?  can you confirm it all works?

Here's a comparison of the two:
https://cloud.google.com/firestore/docs/firestore-or-datastore
Reading that, they look compatible, but I would want to be sure.

**Comment by rbannist** [comment]
@zeroasterisk, yes, I initially followed the prompt to select Datastore mode but I had difficulties and then, upon reading the word 'Collection', I tried switching to Native (Firestore) mode and worked.  I still have the environment running and can screenshot, etc. if that's of help.  Thanks

**Comment by ToddKopriva** [comment]
Thanks for the report, @rbannist . And thanks, @zeroasterisk , for the fix.
