### ISSUE TITLE
Change python version

### ISSUE THREAD

**Issue by HessTaha** [GoogleCloudPlatform/community#994]
Hello,

I'm new to cloudcomputing and I have been playing with GCP for couple of weeks now, 

I have developped some python3  scripts that I wanted to execute on the cloud, but I can't find how to change the default version of python !! It's set to 2.7 

Can anyone help a young cloud padawan ? 

thank you in advance for your help

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered. It’s for issues regarding documents hosted in this repository. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

That said, here is a good place to start for learning how to set up Python for GCP:
https://cloud.google.com/python/setup

**Comment by HessTaha** [comment]
Oupss sorry ! 

Thank you !

**Comment by ToddKopriva** [comment]
No need to apologize.

You're welcome.
