### ISSUE TITLE
Issue with Community Tutorial on Data Cleaning using Cloud Dataflow

### ISSUE THREAD

**Issue by yerlikovboy** [GoogleCloudPlatform/community#995]
Trying to go through this tutorial: https://cloud.google.com/community/tutorials/data-science-preprocessing#running_on_cloud_dataflow

Getting the following error: 
$ python2.7 clean.py $BUCKET/meteors.json $PROJECT:meteor_dataset.cleansed --project $PROJECT --job_name $PROJECT-meteors --runner BlockingDataflowPipelineRunner --staging_location $BUCKET/staging --temp_location $BUCKET/temp --output $BUCKET/output 
Traceback (most recent call last):
  File "clean.py", line 195, in <module>
    main(args.src_path, args.dest_table, pipeline_args=pipeline_args)
  File "clean.py", line 132, in main
    p = apache_beam.Pipeline(argv=pipeline_args)
  File "/Users/ali/Library/Python/2.7/lib/python/site-packages/apache_beam/pipeline.py", line 146, in __init__
    runner = create_runner(runner)
  File "/Users/ali/Library/Python/2.7/lib/python/site-packages/apache_beam/runners/runner.py", line 111, in create_runner
    runner_name, ', '.join(_ALL_KNOWN_RUNNERS)))
ValueError: Unexpected pipeline runner: BlockingDataflowPipelineRunner. Valid values are DirectRunner, BundleBasedDirectRunner, SwitchingDirectRunner, DataflowRunner, TestDataflowRunner, TestDirectRunner, PortableRunner or the fully qualified name of a PipelineRunner subclass.

If I try the dataflowrunner, i get the following error: 
$ python2.7 clean.py $BUCKET/meteors.json $PROJECT:meteor_dataset.cleansed --project $PROJECT --job_name $PROJECT-meteors --runner DataFlowRunner --staging_location $BUCKET/staging --temp_location $BUCKET/temp --output $BUCKET/output
Traceback (most recent call last):
  File "clean.py", line 195, in <module>
    main(args.src_path, args.dest_table, pipeline_args=pipeline_args)
  File "clean.py", line 134, in main
    value = p | 'Read JSON' >> apache_beam.Read(JsonFileSource(src_path))
AttributeError: 'module' object has no attribute 'Read'

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get questions answered. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

That said, I'll tag the author of this tutorial to see if they can see what might be causing your issue.

**Comment by ToddKopriva** [comment]
@jerjou , I'm tagging you so that you cna see this issue with a tutorial that you authored.
