### ISSUE TITLE
Issue with managing-gcp-projects-with-terraform

### ISSUE THREAD

**Issue by glappen** [GoogleCloudPlatform/community#996]
This article got me started with terraform on GCP but I ran into some issues and wanted some clarification. I made a terraform admin project, and made a service account in that project with the roles/viewer and roles/storage.admin. I thought that it would be sufficient to enable services for the project created with terraform like this:
```
resource "google_project_service" "container_service" {                                                                                                                                                            
  project = "${google_project.project.project_id}"                                                                                                                                                                 
  service = "container.googleapis.com"                                                                                                                                                                             
}
```

However, I still got errors that the container service was not enabled, and it referenced the terraform admin project ID (not the project created with the google_project resource!). It seems that I have to enable the services on the terraform admin project in order for the service account to access those services on any projects created by the service account. Is there some parent/child relationship between the projects where services in one project are inherited by projects created from a service account in the parent project? This seems to be the case, but I cannot find any documentation about this anywhere. 

Thanks for listening!

**Comment by ToddKopriva** [comment]
@glappen , the Issues section of this GitHub repository is not the best place to get questions answered. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

That said, I have tagged the authour of the tutorial, @danisla , to see if he can help.

**Comment by glappen** [comment]
@ToddKopriva Thank you for answering! I thought asking here would be appropriate as the pattern I'm trying to implement (i.e. having a terraform admin project that creates other projects) was the one suggested in the tutorial. I will also try to ask my question on one of the forums though to try to get some more information there.

**Comment by ToddKopriva** [comment]
I understand. No problem. I'm just warning you that the turnaround time on questions here isn't as low as on most forums.
