### ISSUE TITLE
Error from server (NotFound): services "iotmonitor-grafana" not found

### ISSUE THREAD

**Issue by TKtong84** [GoogleCloudPlatform/community#998]
I put the script:
"kubectl get service iotmonitor-grafana -o jsonpath={.statu
s.loadBalancer.ingress[0].ip}"                                                                                                                                             
Bu there are error:
"Error from server (NotFound): services "iotmonitor-grafana" not found"

How to search the cause?
Thank you very much.

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get questions answered. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

That said, I have tagged the author of the [Grafana for IoT monitoring tutorial](https://cloud.google.com/community/tutorials/cloud-iot-prometheus-monitoring), @ptone , to see if he can help.
